#![allow(clippy::from_str_radix_10)]
//! Cross-check the Rust StableSwap math against a frozen Python oracle.
//
// Test-crate lint allows: throwaway parser code where short closures, range
// loops, and match-or-panic read clearer than the idioms clippy prefers.
#![allow(clippy::doc_markdown)]
#![allow(clippy::redundant_closure_for_method_calls)]
#![allow(clippy::manual_let_else)]
//!
//! The oracle snapshot (`oracle_snapshot.txt`) was generated by
//! `src/degenbot/calculations/stableswap.py` over a fixture sweep covering
//! the D/Y/Y_D/Newton-Y variants and the reduction coefficient (ADR-005
//! slice 11c). Each line is `<fn_tag> <args...> = <expected>` (or
//! `= ERROR:<reason>`). This test parses each line, replays it through the
//! Rust functions, and asserts the Rust result matches the Python oracle
//! byte-for-byte — the "direct port of the Vyper contract logic" contract.
//!
//! To regenerate the snapshot:
//!   uv run python /tmp/oracle_dump.py | grep -E '^(get_d|get_y|get_y_d|newton_y|reduction) ' \
//!     > rust/crates/degenbot-curve-math/tests/oracle_snapshot.txt

use alloy::primitives::U256;
use degenbot_curve_math::{
    stableswap_get_d, stableswap_get_y, stableswap_get_y_d, stableswap_newton_y,
    stableswap_reduction_coefficient, CurveMathError, DVariant, YDVariant, YVariant,
};

fn u(x: u128) -> U256 {
    U256::from(x)
}

/// Parse a decimal int list like `[a, b, c]` into `Vec<U256>`.
fn parse_list(s: &str) -> Vec<U256> {
    let trimmed = s.trim().trim_start_matches('[').trim_end_matches(']');
    trimmed
        .split(',')
        .map(|t| t.trim())
        .filter(|t| !t.is_empty())
        .map(|t| U256::from_str_radix(t, 10).unwrap())
        .collect()
}

/// Categorize the expected RHS: either a value or an error.
enum Expected {
    Ok(U256),
    Err,
}

fn parse_expected(rhs: &str) -> Expected {
    let rhs = rhs.trim();
    if rhs.starts_with("ERROR:") {
        Expected::Err
    } else {
        Expected::Ok(U256::from_str_radix(rhs, 10).unwrap())
    }
}

#[test]
fn rust_matches_python_oracle_snapshot() {
    let snapshot = include_str!("oracle_snapshot.txt");
    for (lineno, line) in snapshot.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        // Split into tag + RHS on " = " (the last occurrence — args may contain
        // spaces only between the list elements; the value is the final token).
        let (lhs, rhs) = match line.rsplit_once(" = ") {
            Some(pair) => pair,
            None => panic!("line {}: malformed (no ' = '): {line}", lineno + 1),
        };
        let expected = parse_expected(rhs);
        let mut tok = lhs.split_whitespace();
        let tag = tok.next().unwrap();
        let tail: Vec<&str> = tok.collect();
        let actual = match tag {
            "get_d" => {
                // get_d <tag> <xp-list> <amp> <n> <a_prec> <d_variant_u8>
                let xp = parse_list(tail[1]);
                let amp = u128::from_str_radix(tail[2], 10).unwrap();
                let n = u128::from_str_radix(tail[3], 10).unwrap();
                let ap = u128::from_str_radix(tail[4], 10).unwrap();
                let dv = DVariant::try_from_u8(tail[5].parse().unwrap()).expect("d_variant");
                stableswap_get_d(&xp, u(amp), u(n), u(ap), dv)
            }
            "get_y" => {
                // get_y <tag?> <i> <j> <x> <xp> <amp> <n> <ap> <yv> <dv>
                // Note tail[0] is the human tag like "3-ystd".
                let i: usize = tail[1].parse().unwrap();
                let j: usize = tail[2].parse().unwrap();
                let x = U256::from_str_radix(tail[3], 10).unwrap();
                let xp = parse_list(tail[4]);
                let amp = u128::from_str_radix(tail[5], 10).unwrap();
                let n = u128::from_str_radix(tail[6], 10).unwrap();
                let ap = u128::from_str_radix(tail[7], 10).unwrap();
                let yv = YVariant::try_from_u8(tail[8].parse().unwrap()).unwrap();
                let dv = DVariant::try_from_u8(tail[9].parse().unwrap()).unwrap();
                stableswap_get_y(i, j, x, &xp, u(amp), u(n), u(ap), yv, dv)
            }
            "get_y_d" => {
                // get_y_d <tag?> <a> <i> <xp> <d> <n> <ap> <ydv>
                let a = u128::from_str_radix(tail[1], 10).unwrap();
                let i: usize = tail[2].parse().unwrap();
                let xp = parse_list(tail[3]);
                let d = U256::from_str_radix(tail[4], 10).unwrap();
                let n = u128::from_str_radix(tail[5], 10).unwrap();
                let ap = u128::from_str_radix(tail[6], 10).unwrap();
                let ydv = YDVariant::try_from_u8(tail[7].parse().unwrap()).unwrap();
                stableswap_get_y_d(u(a), i, &xp, d, u(n), u(ap), ydv)
            }
            "newton_y" => {
                // newton_y <xp> = <result>  (single fixed fixture; params below)
                let xp = parse_list(tail[0]);
                stableswap_newton_y(
                    u(2_700_000),
                    u(10u128.pow(14)),
                    &xp,
                    u(4) * u(10).pow(u(18)) * u(100),
                    0,
                    u(3),
                    u(100),
                )
            }
            "reduction" => {
                // reduction <xp> <fee_gamma> <n> = <result>
                let xp = parse_list(tail[0]);
                let fee_gamma = U256::from_str_radix(tail[1], 10).unwrap();
                let n = u128::from_str_radix(tail[2], 10).unwrap();
                stableswap_reduction_coefficient(&xp, fee_gamma, u(n))
            }
            other => panic!("line {}: unknown tag {:?}", lineno + 1, other),
        };
        match (actual, expected) {
            (Ok(got), Expected::Ok(want)) => assert_eq!(
                got,
                want,
                "line {}: {tag} mismatch (got {got}, want {want})",
                lineno + 1
            ),
            (Ok(got), Expected::Err) => panic!(
                "line {}: {tag} expected oracle ERROR, Rust returned {got}",
                lineno + 1
            ),
            (Err(_e), Expected::Err) => { /* both error — the Vyper-revert contract */ }
            (Err(e), Expected::Ok(want)) => panic!(
                "line {}: {tag} expected {want}, Rust errored: {e:?}",
                lineno + 1
            ),
        }
    }
}

#[test]
fn get_d_returns_zero_for_empty_xp() {
    let empty: [U256; 0] = [];
    assert_eq!(
        stableswap_get_d(&empty, u(2000), u(3), u(100), DVariant::Standard).unwrap(),
        U256::ZERO
    );
}

#[test]
fn get_y_rejects_i_equals_j() {
    let xp = [u(1500) * u(10).pow(u(18)); 3];
    let err = stableswap_get_y(
        1,
        1,
        u(1),
        &xp,
        u(2000),
        u(3),
        u(100),
        YVariant::Standard,
        DVariant::Standard,
    )
    .unwrap_err();
    assert_eq!(err, CurveMathError::IndexOutOfBounds);
}

#[test]
fn get_y_rejects_out_of_range_index() {
    let xp = [u(1500) * u(10).pow(u(18)); 2];
    let err = stableswap_get_y(
        0,
        5,
        u(1),
        &xp,
        u(2000),
        u(2),
        u(100),
        YVariant::Standard,
        DVariant::Standard,
    )
    .unwrap_err();
    assert_eq!(err, CurveMathError::IndexOutOfBounds);
}

#[test]
fn variant_u8_round_trips() {
    assert_eq!(DVariant::try_from_u8(1), Some(DVariant::Standard));
    assert_eq!(DVariant::try_from_u8(6), Some(DVariant::VariantGammaDp));
    assert_eq!(DVariant::try_from_u8(7), None);
    assert_eq!(YVariant::try_from_u8(3), Some(YVariant::Variant1));
    assert_eq!(YDVariant::try_from_u8(2), Some(YDVariant::Variant0));
}

#[test]
fn reduction_coefficient_zero_fee_gamma_returns_k() {
    // fee_gamma == 0 -> returns K (the raw prod term), not the reduced form.
    let xp = [u(3) * u(10).pow(u(18)), u(3) * u(10).pow(u(18))];
    let k = stableswap_reduction_coefficient(&xp, U256::ZERO, u(2)).unwrap();
    // K = 1e18 * n * x0 / s * n * x1 / s ... with x0=x1, s=2*x0, n=2:
    //   1e18 * 2 * x0 / (2*x0) = 1e18; then 1e18 * 2 * x0 / (2*x0) = 1e18.
    assert_eq!(k, u(10).pow(u(18)));
}
