"""Strategy-signal catalogs and candidate metadata."""

from .arbitrum_atomic_flash_research import (
    ATOMIC_FLASH_TARGETS,
    AtomicFlashStatus,
    AtomicFlashTarget,
    atomic_flash_target,
    ranked_atomic_flash_targets,
    workflow_required_atomic_flash_targets,
)
from .eigenphi_transaction_taxonomy import (
    EIGENPHI_TRANSACTION_PATTERNS,
    EigenPhiPatternFamily,
    EigenPhiTransactionPattern,
    PatternOperationalMode,
    high_risk_patterns,
    pattern_for_slug,
    patterns_for_family,
)
from .github_reference_catalog import (
    TOP_GITHUB_REFERENCE_REPOS,
    GithubReferenceRepo,
    GithubReferenceRisk,
    github_reference_repo,
    ranked_github_reference_repos,
    references_for_import_surface,
)
from .institutional_solver_intelligence import (
    AdaptationCandidate,
    InstitutionalAction,
    InstitutionalBatchEvaluation,
    InstitutionalSolverDecision,
    InstitutionalSolverIntelligence,
    InstitutionalSolverResponsibilities,
    PolicyCorrectionBatch,
    PolicyCorrectionProposal,
    PolicyObservation,
)
from .jaredbot_poc_catalog import (
    JAREDBOT_POCS,
    CapitalMode,
    JaredBotPoc,
    PocStage,
    PocStatus,
    executable_pocs,
    poc_for_skill,
    pocs_for_status,
    workflow_required_pocs,
)

__all__ = (
    "ATOMIC_FLASH_TARGETS",
    "EIGENPHI_TRANSACTION_PATTERNS",
    "JAREDBOT_POCS",
    "TOP_GITHUB_REFERENCE_REPOS",
    "AdaptationCandidate",
    "AtomicFlashStatus",
    "AtomicFlashTarget",
    "CapitalMode",
    "EigenPhiPatternFamily",
    "EigenPhiTransactionPattern",
    "GithubReferenceRepo",
    "GithubReferenceRisk",
    "InstitutionalAction",
    "InstitutionalBatchEvaluation",
    "InstitutionalSolverDecision",
    "InstitutionalSolverIntelligence",
    "InstitutionalSolverResponsibilities",
    "JaredBotPoc",
    "PatternOperationalMode",
    "PocStage",
    "PocStatus",
    "PolicyCorrectionProposal",
    "PolicyCorrectionBatch",
    "PolicyObservation",
    "atomic_flash_target",
    "executable_pocs",
    "github_reference_repo",
    "high_risk_patterns",
    "pattern_for_slug",
    "patterns_for_family",
    "poc_for_skill",
    "pocs_for_status",
    "ranked_atomic_flash_targets",
    "ranked_github_reference_repos",
    "references_for_import_surface",
    "workflow_required_atomic_flash_targets",
    "workflow_required_pocs",
)
