version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns: ["*"]

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      python-deps:
        patterns: ["*"]

  - package-ecosystem: "cargo"
    directory: "/rust"
    schedule:
      interval: "weekly"
    groups:
      rust-deps:
        patterns: ["*"]
