"""Regenerate-and-diff drift gate over the committed `degenbot._ffi` stubs.

ADR-066 D2/D3 cutover: `src/degenbot/_ffi/*.pyi` is GENERATOR OUTPUT (the
`degenbot-stubgen` tool reading the introspection chunks embedded by the
binding layer's `experimental-inspect` build), not a hand-maintained set.
Source and stubs may only agree, so this gate regenerates the tree and diffs
it against the committed one — the REGEN pattern of
`docs/rust-config-keys.md` (`REGEN_CONFIG_DOCS=1 cargo test -p
degenbot-config`), here via `just gen-stubs --check` with `REGEN_STUBS=1` as
the deliberate-regeneration opt-in.

Any seam-source change that reaches the Python surface therefore fails a
plain test run until `just gen-stubs` re-records the generator's verdict.
Hand edits over generated output never reconcile a failure: generator gaps
live only in `tests/rust/stubtest_allowlist.txt` (ADR-066 D3), and
`mypy.stubtest` (`just lint-stubtest`) verifies the generated stubs against
the running extension.
"""

from __future__ import annotations

import pathlib
import subprocess

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_STUB_DIR = _REPO_ROOT / "src" / "degenbot" / "_ffi"
# First line of every file the generator emits (`degenbot-stubgen`'s
# GENERATED_HEADER): marks the tree as generator output so a hand-replaced
# stub is detectable without running the generator.
_GENERATED_MARK = "# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2)."


def test_committed_stubs_carry_generator_header() -> None:
    """Every committed stub is marked generator output (ADR-066 D2)."""
    stubs = sorted(_STUB_DIR.glob("*.pyi"))
    assert stubs, f"stub tree missing at {_STUB_DIR}"
    unmarked = [
        str(p.relative_to(_REPO_ROOT))
        for p in stubs
        if not p.read_text(encoding="utf-8").startswith(_GENERATED_MARK)
    ]
    assert not unmarked, (
        "stub files without the generator header (hand-edited or foreign): "
        f"{unmarked} — regenerate with `just gen-stubs`, never hand-edit"
    )


# The regen-and-diff check rebuilds the cdylib with the `experimental-inspect`
# feature before generating, so it carries the workspace's toggle cost; the
# per-test timeout extends pytest-timeout's 300s default to cover a warm
# rebuild without parking the run on a hang.
@pytest.mark.timeout(900)
def test_committed_stubs_match_generator_output() -> None:
    """Committed stubs are byte-identical to `just gen-stubs --check` output.

    Set ``REGEN_STUBS=1`` to let the check rewrite the committed tree
    (deliberate regeneration only — never to reconcile a hand edit).
    """
    assert (_REPO_ROOT / "justfile").is_file(), "recipe run must start at the repo root"
    proc = subprocess.run(
        ["just", "gen-stubs", "--check"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, (
        f"`just gen-stubs --check` failed (rc={proc.returncode});\n{proc.stdout}\n{proc.stderr}"
    )
