#![allow(clippy::from_str_radix_10)]
//! Cross-check the Rust Balancer math against the frozen Python oracle.
//
// Test-crate lint allows: throwaway parser code (mirror of the curve-math
// oracle_crosscheck.rs pattern).
#![allow(clippy::doc_markdown)]
#![allow(clippy::redundant_closure_for_method_calls)]
#![allow(clippy::manual_let_else)]
#![allow(clippy::needless_range_loop)]
//!
//! The oracle snapshot (`oracle_snapshot.txt`) was generated by
//! `/tmp/balancer_oracle_dump.py` running the Python
//! `balancer/libraries/{fixed_point,log_exp_math,weighted_math,stable_math}`
//! oracles over a fixture sweep covering the variant axes (PowVersion V1 /
//! V2 for `pow_down`/`pow_up` + WeightedMath; round_up True / False for the
//! deployed StableMath invariant) and value sweeps + edge cases
//! (zero, overflow, MAX_IN_RATIO). Each line is `<fn_tag> <args...> =
//! <result>` (or `= ERROR:<reason>`). This test parses each line, replays
//! it through the Rust functions, and asserts byte-for-byte equality against
//! the Python oracle — the "direct port of the deployed contract logic"
//! contract (ADR-005 slice 12e).

use alloy::primitives::{I256, U256};
use degenbot_balancer_math::{
    fixed_point, log_exp_math, stable_math, weighted_math, BalancerMathError, PowVersion,
};

/// Parse a decimal int list like `[a, b, c]` into `Vec<U256>`.
fn parse_list_u256(s: &str) -> Vec<U256> {
    let trimmed = s.trim().trim_start_matches('[').trim_end_matches(']');
    trimmed
        .split(',')
        .map(|t| t.trim())
        .filter(|t| !t.is_empty())
        .map(|t| U256::from_str_radix(t, 10).unwrap())
        .collect()
}

/// Categorize the expected RHS: either a value or an error.
enum Expected {
    OkU(U256),
    OkI(I256),
    Err,
}

fn parse_expected(rhs: &str) -> Expected {
    let rhs = rhs.trim();
    if rhs.starts_with("ERROR:") {
        return Expected::Err;
    }
    // Non-negative result — try U256 first (the common case); the
    // signed-result tags (lm_ln, lm_log) re-route via parse_expected_signed
    // below for cleaner dispatch.
    Expected::OkU(U256::from_str_radix(rhs, 10).unwrap())
}

fn pow_version(s: &str) -> PowVersion {
    match s {
        "V1" => PowVersion::V1,
        "V2" => PowVersion::V2,
        other => panic!("unknown PowVersion tag {other:?}"),
    }
}

#[test]
fn rust_matches_python_oracle_snapshot() {
    let snapshot = include_str!("oracle_snapshot.txt");
    for (lineno, line) in snapshot.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() {
            continue;
        }
        let (lhs, rhs) = line
            .rsplit_once(" = ")
            .unwrap_or_else(|| panic!("line {}: malformed (no ' = '): {line}", lineno + 1));
        let mut tok = lhs.split_whitespace();
        let tag = tok.next().unwrap();
        let tail: Vec<&str> = tok.collect();
        let result = run_tag(tag, &tail, lineno + 1);
        let expected = parse_expected_signed(tag, rhs, lineno + 1);
        match (result, expected) {
            (Ok(Outcome::U(got)), Expected::OkU(want)) => assert_eq!(
                got,
                want,
                "line {}: {tag} mismatch (got {got}, want {want})",
                lineno + 1,
            ),
            (Ok(Outcome::I(got)), Expected::OkI(want)) => assert_eq!(
                got,
                want,
                "line {}: {tag} mismatch (got {got}, want {want})",
                lineno + 1,
            ),
            (Ok(_), Expected::Err) => panic!(
                "line {}: {tag} expected oracle ERROR, Rust returned a value",
                lineno + 1,
            ),
            (Err(_), Expected::Err) => { /* both error — Vyper-revert contract */ }
            (Err(e), Expected::OkU(want)) => panic!(
                "line {}: {tag} expected {want}, Rust errored: {e:?}",
                lineno + 1,
            ),
            (Err(e), Expected::OkI(want)) => panic!(
                "line {}: {tag} expected {want}, Rust errored: {e:?}",
                lineno + 1,
            ),
            (Ok(Outcome::U(_)), Expected::OkI(_)) | (Ok(Outcome::I(_)), Expected::OkU(_)) => {
                panic!(
                    "line {}: {tag} outcome/expected sign-type mismatch",
                    lineno + 1,
                )
            }
        }
    }
}

/// Result kind: a non-negative U256 (most tags) or a signed I256
/// (`lm_ln`, `lm_log`).
enum Outcome {
    U(U256),
    I(I256),
}

type R = std::result::Result<Outcome, BalancerMathError>;

/// Parse RHS for tags that return signed values (`lm_ln`, `lm_log`).
/// Routes through `parse_expected` for the rest (U256).
fn parse_expected_signed(tag: &str, rhs: &str, lineno: usize) -> Expected {
    let rhs = rhs.trim();
    if rhs.starts_with("ERROR:") {
        return Expected::Err;
    }
    if matches!(tag, "lm_ln" | "lm_log") {
        // Signed result.
        let v = I256::from_dec_str(rhs)
            .unwrap_or_else(|e| panic!("line {lineno}: bad signed RHS {rhs:?}: {e}"));
        return Expected::OkI(v);
    }
    parse_expected(rhs)
}

fn u(s: &str) -> U256 {
    U256::from_str_radix(s, 10).unwrap()
}

fn i(s: &str) -> I256 {
    I256::from_dec_str(s).unwrap_or_else(|e| panic!("bad signed int {s:?}: {e}"))
}

fn run_tag(tag: &str, tail: &[&str], _lineno: usize) -> R {
    match tag {
        "fp_add" => Ok(Outcome::U(fixed_point::add(u(tail[0]), u(tail[1]))?)),
        "fp_sub" => Ok(Outcome::U(fixed_point::sub(u(tail[0]), u(tail[1]))?)),
        "fp_mul_down" => Ok(Outcome::U(fixed_point::mul_down(u(tail[0]), u(tail[1]))?)),
        "fp_mul_up" => Ok(Outcome::U(fixed_point::mul_up(u(tail[0]), u(tail[1]))?)),
        "fp_div_down" => Ok(Outcome::U(fixed_point::div_down(u(tail[0]), u(tail[1]))?)),
        "fp_div_up" => Ok(Outcome::U(fixed_point::div_up(u(tail[0]), u(tail[1]))?)),
        "fp_complement" => Ok(Outcome::U(fixed_point::complement(u(tail[0])))),
        "fp_pow_down" => Ok(Outcome::U(fixed_point::pow_down(
            u(tail[0]),
            u(tail[1]),
            pow_version(tail[2]),
        )?)),
        "fp_pow_up" => Ok(Outcome::U(fixed_point::pow_up(
            u(tail[0]),
            u(tail[1]),
            pow_version(tail[2]),
        )?)),
        "lm_pow" => Ok(Outcome::U(log_exp_math::pow(u(tail[0]), i(tail[1]))?)),
        "lm_ln" => Ok(Outcome::I(log_exp_math::ln(u(tail[0]))?)),
        "lm_exp" => {
            let x = i(tail[0]);
            Ok(Outcome::U(log_exp_math::exp(x)?))
        }
        "lm_log" => Ok(Outcome::I(log_exp_math::log(u(tail[0]), u(tail[1]))?)),
        "wm_invariant" => {
            let w = parse_list_u256(tail[0]);
            let b = parse_list_u256(tail[1]);
            let v = pow_version(tail[2]);
            Ok(Outcome::U(weighted_math::calculate_invariant(&w, &b, v)?))
        }
        "wm_out_given_in" => {
            let bi = u(tail[0]);
            let wi = u(tail[1]);
            let bo = u(tail[2]);
            let wo = u(tail[3]);
            let ai = u(tail[4]);
            let v = pow_version(tail[5]);
            Ok(Outcome::U(weighted_math::calc_out_given_in(
                bi, wi, bo, wo, ai, v,
            )?))
        }
        "wm_in_given_out" => {
            let bi = u(tail[0]);
            let wi = u(tail[1]);
            let bo = u(tail[2]);
            let wo = u(tail[3]);
            let ao = u(tail[4]);
            let v = pow_version(tail[5]);
            Ok(Outcome::U(weighted_math::calc_in_given_out(
                bi, wi, bo, wo, ao, v,
            )?))
        }
        "wm_sub_fee" => Ok(Outcome::U(weighted_math::subtract_swap_fee_amount(
            u(tail[0]),
            u(tail[1]),
        )?)),
        "wm_add_fee" => Ok(Outcome::U(weighted_math::add_swap_fee_amount(
            u(tail[0]),
            u(tail[1]),
        )?)),
        "sm_invariant_d_p" => Ok(Outcome::U(stable_math::calculate_invariant(
            u(tail[0]),
            &parse_list_u256(tail[1]),
        )?)),
        "sm_invariant_p_d_up" => Ok(Outcome::U(stable_math::calculate_invariant_deployed(
            u(tail[0]),
            &parse_list_u256(tail[1]),
            true,
        )?)),
        "sm_invariant_p_d_down" => Ok(Outcome::U(stable_math::calculate_invariant_deployed(
            u(tail[0]),
            &parse_list_u256(tail[1]),
            false,
        )?)),
        "sm_out_given_in" => {
            let amp = u(tail[0]);
            let b = parse_list_u256(tail[1]);
            let token_in: usize = tail[2].parse().unwrap();
            let token_out: usize = tail[3].parse().unwrap();
            let amt = u(tail[4]);
            let inv = u(tail[5]);
            Ok(Outcome::U(stable_math::calc_out_given_in(
                amp, &b, token_in, token_out, amt, inv,
            )?))
        }
        "sm_in_given_out" => {
            let amp = u(tail[0]);
            let b = parse_list_u256(tail[1]);
            let token_in: usize = tail[2].parse().unwrap();
            let token_out: usize = tail[3].parse().unwrap();
            let amt = u(tail[4]);
            let inv = u(tail[5]);
            Ok(Outcome::U(stable_math::calc_in_given_out(
                amp, &b, token_in, token_out, amt, inv,
            )?))
        }
        other => panic!("unknown tag {other:?}"),
    }
}
