// AUTO-GENERATED by tests/fixtures/generate_composers_3hop_parity.py.
// Byte-exact parity vs the Python oracle:
//   examples/eth_backrun_helpers.py::_encode_cmd_3_hop (27 patterns +
//   use_v4_batch / erc6909_profit variants for V4-V4-V4).
// Do not edit by hand — re-run the generator to refresh (§4.2 gate).

#![allow(
    clippy::too_many_lines,
    clippy::unreadable_literal,
    clippy::needless_pass_by_value
)]

use alloy::primitives::address;
use degenbot_executor::composers::{
    encode_cmd_3_hop, EncodeOptions, HopInfo, PathInfo, V2HopInfo, V3HopInfo, V4HopInfo,
};

fn hx(s: &[u8]) -> Vec<u8> {
    s.to_vec()
}

#[test]
fn parity_v2_v2_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\xff\x20\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x00\x1e\x1b\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x21\x00\x01\x01\x00\x1e\x21\x01\x01\x02\x00\x1e")));
}

#[test]
fn parity_v2_v2_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\xff\x30\x02\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x1b\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x21\x00\x01\x01\x00\x1e\x21\x01\x01\x02\x00\x1e")));
}

#[test]
fn parity_v2_v2_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x28\x54\xfe\x52\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x21\x00\x01\x01\x00\x1e\x21\x01\x01\xfc\x00\x1e\x55\x41\xfe\x02\x0b\xb8\x00\x3c\xff\x01\x57")));
}

#[test]
fn parity_v2_v3_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\xff\x20\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x00\x1e\x30\x30\x03\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x02\x1f\x10\xfe\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x22\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x03")));
}

#[test]
fn parity_v2_v3_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\xff\x30\x02\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x30\x30\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x02\x1f\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x22\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x01")));
}

#[test]
fn parity_v2_v3_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[
            2000000000u128,
            2001000000000000000u128,
            2001000000000000000u128,
        ],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x54\xfe\x30\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\xfc\x49\x50\x37\x55\x40\xfe\x02\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x52\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x52\xfe\xfd\x00\x00\x00\x00\x0d\xe4\x44\x32\x4c\x2a\x80\x00\x54\xfe\x55\x22\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x01")));
}

#[test]
fn parity_v2_v4_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\xff\x20\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x00\x1e\x3e\x10\xfe\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x50\x2d\x54\x00\x21\x01\x01\xfc\x00\x1e\x55\x40\x00\xfe\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x52\xfe\x02\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00")));
}

#[test]
fn parity_v2_v4_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\xff\x30\x02\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x3e\x10\xfe\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x50\x2d\x54\x00\x21\x01\x01\xfc\x00\x1e\x55\x40\x00\xfe\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x52\xfe\x02\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00")));
}

#[test]
fn parity_v2_v4_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V2(V2HopInfo {
                pool_address: address!("1111111111111111111111111111111111111111"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\x11\xff\x50\x37\x54\x00\x52\xfe\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x21\x01\x01\xfc\x00\x1e\x55\x40\x00\xfe\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x41\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x57")));
}

#[test]
fn parity_v3_v2_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\xff\x30\x02\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x00\x2f\x22\x00\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x01\x22\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x10\xfe\x02\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00")));
}

#[test]
fn parity_v3_v2_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 500u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\xff\x30\x02\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x30\x30\x01\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x00\x1f\x22\x00\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x02\x10\xfe\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00")));
}

#[test]
fn parity_v3_v2_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x30\x00\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x01\x4a\x20\x01\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x00\x1e\x28\x50\x26\x40\xfe\x02\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x52\xfe\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\x56\xfe\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00")));
}

#[test]
fn parity_v3_v3_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\xff\x30\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x00\x30\x30\x01\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x02\x1f\x22\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x10\xfe\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00")));
}

#[test]
fn parity_v3_v3_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\xff\x30\x02\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x22\x30\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x02\x11\x30\x00\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x01\x00")));
}

#[test]
fn parity_v3_v3_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x54\xfe\x30\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\xfc\x21\x30\x00\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x01\x10\x50\x0e\x55\x41\xfe\x02\x0b\xb8\x00\x3c\xff\x01\x53\xfe\x00\x57")));
}

#[test]
fn parity_v3_v4_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x54\x02\x30\x00\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\xfc\x2f\x50\x0e\x55\x41\x02\xfe\x01\xf4\x00\x0a\xff\x01\x53\xfe\x01\x57\x22\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00")));
}

#[test]
fn parity_v3_v4_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x54\x02\x30\x01\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x30\x30\x00\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\xfc\x1f\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x50\x0e\x55\x41\x02\xfe\x01\xf4\x00\x0a\xff\x01\x53\xfe\x01\x57")));
}

#[test]
fn parity_v3_v4_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V3(V3HopInfo {
                pool_address: address!("4444444444444444444444444444444444444444"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x44\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x30\x00\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\xfd\x4b\x50\x3a\x55\x40\x01\xfe\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x40\xfe\x01\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x52\xfe\xfd\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\x10\xfe\x00\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00")));
}

#[test]
fn parity_v4_v2_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\xff\x50\x32\x40\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x52\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x21\x01\x01\x02\x00\x1e\x21\x02\x01\xfd\x00\x1e\x56\xfe")));
}

#[test]
fn parity_v4_v2_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 500u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\xff\x30\x00\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x2e\x50\x2c\x40\xfe\x01\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x52\x01\x02\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x21\x02\x01\x00\x00\x1e\x56\xfe")));
}

#[test]
fn parity_v4_v2_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("2222222222222222222222222222222222222222"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 30u16,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\x22\xff\x50\x40\x40\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x52\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x21\x01\x01\xfd\x00\x1e\x40\xfe\x00\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x57")));
}

#[test]
fn parity_v4_v3_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\xff\x50\x47\x40\xfe\x01\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x30\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x02\x1f\x52\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x22\x02\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x56\xfe")));
}

#[test]
fn parity_v4_v3_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x48\x40\xfe\x02\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x30\x01\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x20\x30\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x01\x0f\x52\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x56\xfe")));
}

#[test]
fn parity_v4_v3_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("5555555555555555555555555555555555555555"),
                token0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                token1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x55\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x4e\x40\xfe\x01\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x54\xfe\x30\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\xfc\x0f\x52\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x77\x35\x94\x00\x55\x40\xfe\x01\x0b\xb8\x00\x0a\xff\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x57")));
}

#[test]
fn parity_v4_v4_v2() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V2(V2HopInfo {
                pool_address: address!("3333333333333333333333333333333333333333"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 30u16,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x33\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x3e\x40\xfe\x01\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x41\x01\xfe\x01\xf4\x00\x0a\xff\x01\x52\xfe\x00\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x22\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x77\x44\xd6\x40\xfd\x57")));
}

#[test]
fn parity_v4_v4_v3() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V3(V3HopInfo {
                pool_address: address!("6666666666666666666666666666666666666666"),
                token0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                token1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x66\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x3f\x40\xfe\x01\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x41\x01\xfe\x01\xf4\x00\x0a\xff\x01\x30\x00\x01\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\xfd\x0f\x52\xfe\x00\x00\x00\x00\x00\x1b\xc4\xfa\xe5\xf3\x8e\x80\x00\x57")));
}

#[test]
fn parity_v4_v4_v4() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions::default(),
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x2b\x40\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x41\x00\xfe\x01\xf4\x00\x0a\xff\x01\x41\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x53\x00\xfd\x57")));
}

#[test]
fn parity_v4_v4_v4_batch() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[2000000000u128, 2001000000000000000u128, 2001000000u128],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions {
            erc6909_profit: false,
            use_v4_batch: true,
        },
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x42\x42\x03\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x00\xfe\x01\xf4\x00\x0a\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x53\x00\xfd\x57")));
}

#[test]
fn parity_v4_v4_v4_erc6909() {
    let rust = encode_cmd_3_hop(
        &PathInfo::new(vec![
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                currency1_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                fee: 500u32,
                tick_spacing: 10i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
            HopInfo::V4(V4HopInfo {
                pool_manager_address: address!("000000000004444c5dc75cB358380D2e3dE08A90"),
                pool_id_hex: "0x1111111111111111111111111111111111111111111111111111111111111111"
                    .to_string(),
                currency0_address: address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
                currency1_address: address!("A0b86991c6218b36c1D19D4a2e9Eb0cE3606eB48"),
                fee: 3000u32,
                tick_spacing: 60i32,
                hook_address: address!("0000000000000000000000000000000000000000"),
                zfo: true,
            }),
        ]),
        1000000000000000000u128,
        &[
            2000000000u128,
            2001000000000000000u128,
            2001000000000000000u128,
        ],
        address!("DeAd0000000000000000000000000000000000Be"),
        address!("000000000004444c5dc75cB358380D2e3dE08A90"),
        address!("C02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2"),
        EncodeOptions {
            erc6909_profit: true,
            use_v4_batch: false,
        },
    );
    assert_eq!(rust, Some(hx(b"\x00\xa0\xb8\x69\x91\xc6\x21\x8b\x36\xc1\xd1\x9d\x4a\x2e\x9e\xb0\xce\x36\x06\xeb\x48\xff\x50\x2b\x40\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x00\x00\x00\x00\x0d\xe0\xb6\xb3\xa7\x64\x00\x00\x41\x00\xfe\x01\xf4\x00\x0a\xff\x01\x41\xfe\x00\x0b\xb8\x00\x3c\xff\x01\x53\x00\xfd\x57")));
}
