//! Generated key-reference documentation.
//!
//! [`render_key_reference`] renders EVERY schema key with its env name,
//! TOML path, type, default, and description — straight from [`SCHEMA`],
//! never hand-maintained. The doc-generation test keeps
//! `docs/rust-config-keys.md` in lockstep (regenerate with
//! `REGEN_CONFIG_DOCS=1 cargo test -p degenbot-config`).

use std::fmt::Write;

use crate::schema::{BaseKind, SCHEMA};

/// Path of the committed doc, relative to this crate's manifest dir.
pub const DOC_RELATIVE_PATH: &str = "../../../../docs/rust-config-keys.md";

/// Render the full key-reference document (deterministic; declaration
/// order). The precedence contract is recorded in the header because the
/// generated doc is the operator-facing source of truth.
#[must_use]
pub fn render_key_reference() -> String {
    let mut out = String::new();
    out.push_str("# Bot configuration keys (Rust core, generated)\n\n");
    out.push_str("<!-- GENERATED by the degenbot-config doc-generation test; DO NOT edit. -->\n");
    out.push_str("<!-- Regenerate: REGEN_CONFIG_DOCS=1 cargo test -p degenbot-config -->\n\n");
    out.push_str("One typed `BotConfig` value is the single source of truth for all runtime ");
    out.push_str(
        "configuration (crate `degenbot-config`, schema constant `SCHEMA`). Every key is ",
    );
    out.push_str("settable from the config file OR the environment with the same name tree.\n\n");
    out.push_str("## Precedence\n\n");
    out.push_str("Highest wins (12-factor parity; recorded here by the schema and asserted by the loader tests):\n\n");
    out.push_str(
        "1. CLI / explicit argument (loader override keys accept the env name or the TOML path)\n",
    );
    out.push_str("2. Environment variable (`DEGENBOT_*`)\n");
    out.push_str("3. Config file (TOML tree selected by `--config <path>`)\n");
    out.push_str("4. Built-in defaults (shown below)\n\n");
    out.push_str("The loader is fail-closed: unparsable values and unknown file keys are reported, never silently ignored.\n\n");

    let mut current_section: Option<&str> = None;
    for key in SCHEMA {
        if Some(key.section) != current_section {
            current_section = Some(key.section);
            let _ = writeln!(out, "## `{}`", key.section);
            out.push_str("\n| Env var | TOML key | Type | Default | Description |\n");
            out.push_str("| --- | --- | --- | --- | --- |\n");
        }
        let default_display = if key.default_repr.is_empty() {
            "(empty)"
        } else {
            key.default_repr
        };
        let description = key.description.replace('|', "\\|");
        let _ = writeln!(
            out,
            "| `{}` | `{}.{}` | `{}` | `{}` | {} |",
            key.env, key.section, key.field, key.kind, default_display, description
        );
    }
    out
}

/// Type label used per base kind in the rendered table (kept simple;
/// `ValueKind`'s `Display` is the single implementation of the label).
#[must_use]
pub fn base_type_label(base: BaseKind) -> String {
    base.to_string()
}

/// Render and (when `regen` is set) write the committed doc file.
/// Returns the rendered text and, when written, the path.
///
/// # Errors
///
/// I/O failure writing the regenerated doc.
pub fn render_and_maybe_write(
    regen: bool,
) -> Result<(String, Option<std::path::PathBuf>), std::io::Error> {
    let text = render_key_reference();
    if regen {
        let manifest = env!("CARGO_MANIFEST_DIR");
        let path = std::path::Path::new(manifest).join(DOC_RELATIVE_PATH);
        std::fs::write(&path, &text)?;
        Ok((text, Some(path)))
    } else {
        Ok((text, None))
    }
}
