"""Aerodrome pool calculations and address generation.

Routes the Solidly-stable swap calc through the Rust ``degenbot-solidly-math``
leaf (via ``degenbot._ffi.solidly_calc_exact_in_stable_solidly``) and retains
address-generation helpers (CREATE2 deterministic pool address).
"""

from collections.abc import Sequence
from fractions import Fraction

import eth_abi.packed
from eth_typing import ChecksumAddress
from eth_utils.crypto import keccak
from hexbytes import HexBytes

from degenbot.abi import encode as abi_encode
from degenbot.aerodrome.math import (
    calc_exact_in_stable_solidly as solidly_calc_exact_in_stable_solidly,
)
from degenbot.contract.addresses import eip_1167_clone_address


def calc_exact_in_stable(
    *,
    amount_in: int,
    token_in: int,
    reserves0: int,
    reserves1: int,
    decimals0: int,
    decimals1: int,
    fee: Fraction,
) -> int:
    """Aerodrome-specific stable exact-in calculation.

    Routes through the Rust ``degenbot-solidly-math`` leaf via
    :func:`degenbot._ffi.solidly_calc_exact_in_stable_solidly`, which wraps the
    Solidly/Aerodrome pre-baked orchestration
    (``calc_k`` + ``get_y_solidly``). The Solidly/Camelot invariant math
    (``calc_d`` / ``calc_k`` / ``calc_f`` / ``get_y_solidly``) is computed in
    pure Rust (cross-checked by ``degenbot-solidly-math/tests/oracle_crosscheck.rs``).

    The Python ``Fraction`` fee is split into ``numerator`` + ``denominator``
    integers at the seam (the Rust leaf takes two ``U256``s to avoid pulling
    ``num-rational`` into the pure-math core).

    Returns:
        The computed integer value.

    """
    return solidly_calc_exact_in_stable_solidly(
        amount_in,
        token_in,
        reserves0,
        reserves1,
        decimals0,
        decimals1,
        fee.numerator,
        fee.denominator,
    )


def generate_aerodrome_v2_pool_address(
    *,
    deployer_address: str | bytes,
    token_addresses: Sequence[str | bytes],
    implementation_address: str | bytes,
    stable: bool,
) -> ChecksumAddress:
    """Get the deterministic V2 pool address generated by CREATE2.

    Uses the token address to generate the salt.
    The token addresses can be passed in any order.

    Adapted from https://github.com/aerodrome-finance/contracts/blob/main/contracts/factories/PoolFactory.sol
    and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol

    Returns:
        The computed value.

    """
    sorted_token_addresses = sorted([HexBytes(address) for address in token_addresses])

    salt = keccak(
        eth_abi.packed.encode_packed(
            ("address", "address", "bool"),
            [*sorted_token_addresses, stable],
        ),
    )

    return eip_1167_clone_address(
        deployer=deployer_address,
        implementation_contract=implementation_address,
        salt=salt,
    )


def generate_aerodrome_v3_pool_address(
    deployer_address: str | bytes,
    token_addresses: Sequence[str | bytes],
    implementation_address: str | bytes,
    tick_spacing: int,
) -> ChecksumAddress:
    """Get the deterministic V3 pool address generated by CREATE2.

    Uses the token address to generate the salt.
    The token addresses can be passed in any order.

    Adapted from https://github.com/aerodrome-finance/slipstream/blob/main/contracts/core/CLFactory.sol
    and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol

    Returns:
        The computed value.

    """
    sorted_token_addresses = sorted([HexBytes(address) for address in token_addresses])

    salt = keccak(
        abi_encode(
            ("address", "address", "int24"),
            [*sorted_token_addresses, tick_spacing],
        ),
    )

    return eip_1167_clone_address(
        deployer=deployer_address,
        implementation_contract=implementation_address,
        salt=salt,
    )
