"""Aerodrome deterministic CREATE2 pool-address derivation (EIP-1167 clones).

Delegating shells over the Rust ``degenbot._ffi.compute_aerodrome_v2_pool_address``
/ ``compute_aerodrome_v3_pool_address`` pyfunctions (the pure-Rust
``degenbot_uniswap::create2::compute_aerodrome_v2_address`` /
``compute_aerodrome_v3_address`` leaves). The Solidly-stable swap calc is now
invoked in-line at its sole call site (``aerodrome/pools.py::to_hop_state``)
via the Rust leaf re-exported by ``degenbot.aerodrome.math``; the redundant
Fraction-splitting wrapper that lived here was deleted (ergo S5SJXF /
NFYOWI). These address helpers were routed through the Rust seam and their
pure-Python ``eip_1167_clone_address`` / ``keccak256`` / ``encode_packed`` /
``abi_encode`` bodies deleted (ergo S5SJXF / WLJD2Y — the Python functions
are now thin pass-throughs; the Rust ``#[cfg(test)]`` corpus is the §4.2
regression set).
"""

from collections.abc import Sequence

from eth_typing import ChecksumAddress

from degenbot._ffi import (
    compute_aerodrome_v2_pool_address as _rs_compute_aerodrome_v2_pool_address,
)
from degenbot._ffi import (
    compute_aerodrome_v3_pool_address as _rs_compute_aerodrome_v3_pool_address,
)
from degenbot.checksum_cache import get_checksum_address


def generate_aerodrome_v2_pool_address(
    *,
    deployer_address: str | bytes,
    token_addresses: Sequence[str | bytes],
    implementation_address: str | bytes,
    stable: bool,
) -> ChecksumAddress:
    """Get the deterministic V2 pool address generated by CREATE2.

    Uses the token addresses to generate the salt.
    The token addresses can be passed in any order.

    Adapted from https://github.com/aerodrome-finance/contracts/blob/main/contracts/factories/PoolFactory.sol
    and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol

    Returns:
        The computed value.

    """
    t0, t1 = token_addresses  # type: ignore[misc]
    return get_checksum_address(
        _rs_compute_aerodrome_v2_pool_address(
            str(deployer_address),
            str(t0),
            str(t1),
            stable,
            str(implementation_address),
        )
    )


def generate_aerodrome_v3_pool_address(
    deployer_address: str | bytes,
    token_addresses: Sequence[str | bytes],
    implementation_address: str | bytes,
    tick_spacing: int,
) -> ChecksumAddress:
    """Get the deterministic V3 pool address generated by CREATE2.

    Uses the token addresses to generate the salt.
    The token addresses can be passed in any order.

    Adapted from https://github.com/aerodrome-finance/slipstream/blob/main/contracts/core/CLFactory.sol
    and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol

    Returns:
        The computed value.

    """
    t0, t1 = token_addresses  # type: ignore[misc]
    return get_checksum_address(
        _rs_compute_aerodrome_v3_pool_address(
            str(deployer_address),
            str(t0),
            str(t1),
            tick_spacing,
            str(implementation_address),
        )
    )
