"""Aerodrome pool calculations and address generation.

.. deprecated::
    Calculation functions have been moved to :mod:`degenbot.calculations.solidly_stable`.
    This module retains address-generation functions and backwards-compatible re-exports.
"""

from collections.abc import Sequence

import eth_abi.abi
import eth_abi.packed
from eth_typing import ChecksumAddress
from eth_utils.crypto import keccak
from hexbytes import HexBytes

from degenbot.calculations.solidly_stable import (
    calc_d as _calc_d,
    calc_exact_in_stable as _calc_exact_in_stable,
    calc_f as _f_aerodrome,
    calc_k as _k_aerodrome,
    get_y_solidly as _get_y_aerodrome,
)
from degenbot.contract.addresses import eip_1167_clone_address


def calc_exact_in_stable(*args, **kwargs):
    """Aerodrome-specific stable exact-in calculation.

    Delegates to :func:`degenbot.calculations.solidly_stable.calc_exact_in_stable`
    with Aerodrome's k_func and get_y_func.
    """
    return _calc_exact_in_stable(
        *args,
        **kwargs,
        k_func=_k_aerodrome,
        get_y_func=_get_y_aerodrome,
    )


def generate_aerodrome_v2_pool_address(
    *,
    deployer_address: str | bytes,
    token_addresses: Sequence[str | bytes],
    implementation_address: str | bytes,
    stable: bool,
) -> ChecksumAddress:
    """
    Get the deterministic V2 pool address generated by CREATE2. Uses the token address to generate
    the salt. The token addresses can be passed in any order.

    Adapted from https://github.com/aerodrome-finance/contracts/blob/main/contracts/factories/PoolFactory.sol
    and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol
    """

    sorted_token_addresses = sorted([HexBytes(address) for address in token_addresses])

    salt = keccak(
        eth_abi.packed.encode_packed(
            ("address", "address", "bool"),
            [*sorted_token_addresses, stable],
        )
    )

    return eip_1167_clone_address(
        deployer=deployer_address,
        implementation_contract=implementation_address,
        salt=salt,
    )


def generate_aerodrome_v3_pool_address(
    deployer_address: str | bytes,
    token_addresses: Sequence[str | bytes],
    implementation_address: str | bytes,
    tick_spacing: int,
) -> ChecksumAddress:
    """
    Get the deterministic V3 pool address generated by CREATE2. Uses the token address to generate
    the salt. The token addresses can be passed in any order.

    Adapted from https://github.com/aerodrome-finance/slipstream/blob/main/contracts/core/CLFactory.sol
    and https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/proxy/Clones.sol
    """

    sorted_token_addresses = sorted([HexBytes(address) for address in token_addresses])

    salt = keccak(
        eth_abi.abi.encode(
            ("address", "address", "int24"),
            [*sorted_token_addresses, tick_spacing],
        )
    )

    return eip_1167_clone_address(
        deployer=deployer_address,
        implementation_contract=implementation_address,
        salt=salt,
    )
