#![allow(unused_imports, unused_attributes, clippy::all, rustdoc::all)]
//! This module contains the sol! generated bindings for solidity contracts.
//! This is autogenerated code.
//! Do not manually edit these files.
//! These files may be overwritten by the codegen system at any time.
pub mod base_mev_paymaster;
pub mod i_executor;
pub mod i_path_finder;
pub mod path_finder_venue;
pub mod i_reactor_callback;
pub mod i_uniswap_v4_hook;
pub mod lp_transfer_lib;
pub mod mev_bot_delegate;
pub mod mev_paymaster_v9;
pub mod i_mev_safe_account;
pub mod i_mev_safe_erc1271;
pub mod mev_safe;
pub mod mev_safe_factory;
pub mod multi_hop_caller;
pub mod path_finder;
pub mod permission_token;
pub mod router_registry;
pub mod strategy_ledger;
pub mod token_standard_ids;
pub mod transient_storage;

/// Number of generated binding modules. Tripwire for the curated
/// `DEFAULT_SELECTED_CONTRACTS` set in
/// `degenbot.devtools.foundry_bindings` silently shrinking; injected
/// after `forge bind` (not produced by `forge bind` itself).
pub const SELECTED_CONTRACT_BINDING_COUNT: usize = 20;
