from degenbot.uniswap.abi import (
    CAMELOT_POOL_ABI,
    SUSHISWAP_V2_POOL_ABI,
    UNISWAP_UNIVERSAL_ROUTER_ABI,
    UNISWAP_V2_FACTORY_ABI,
    UNISWAP_V2_POOL_ABI,
    UNISWAP_V2_ROUTER_ABI,
    UNISWAP_V3_FACTORY_ABI,
    UNISWAP_V3_POOL_ABI,
    UNISWAP_V3_ROUTER2_ABI,
    UNISWAP_V3_ROUTER_ABI,
    UNISWAP_V3_TICKLENS_ABI,
)
