from degenbot.uniswap.abi import (
    CAMELOT_LP_ABI,
    SUSHISWAP_LP_ABI,
    UNISWAP_UNIVERSAL_ROUTER_ABI,
    UNISWAPV2_FACTORY_ABI,
    UNISWAPV2_ROUTER_ABI,
    UNISWAPV2_ROUTER,  # alias for older scripts that may be floating around
    UNISWAPV2_LP_ABI,
    UNISWAP_V3_TICKLENS_ABI,
    UNISWAP_V3_FACTORY_ABI,
    UNISWAP_V3_POOL_ABI,
    UNISWAP_V3_ROUTER_ABI,
    UNISWAP_V3_ROUTER2_ABI,
)
