// ADR-066 D2: writes the committed `src/degenbot/_ffi/` stub tree from the
// introspection chunks embedded in a cdylib built with the binding layer's
// `experimental-inspect` feature. Chunk parsing is static (object-file
// symbols only), so the cdylib is never loaded or executed here.
use std::path::Path;

use anyhow::{anyhow, bail, Context, Result};

mod config_projection;
mod exception_manifest;
use exception_manifest::EXCEPTION_ISLANDS;
use pyo3_introspection::model::Module;
use pyo3_introspection::{introspect_cdylib, module_stub_files};

// The header prepended to every generated stub: marks the tree as generator
// output so hand edits over it (ADR-066 D3's drift blind spot) are detectable.
const GENERATED_HEADER: &str = "# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).\n# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).\n\n";

// A stub cannot spell a parameter with a Python keyword: PyO3 registers
// `#[pyo3(signature = (..., from=None, ...))]` with the literal keyword
// "from" (callable at runtime only via `**`-unpacking), and
// `pyo3-introspection` emits that name verbatim, making
// `def estimate_gas(..., from: str | None = None)` a SyntaxError. The
// generator mangles such parameter names to the typeshed convention
// (`from_`) — the only stub-expressible spelling of the same position.
const PY_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield",
];

// Rewrites keyword-spelled parameter names in `def` signature lines. Only
// top-level parameter segments (comma-split at bracket depth 1 inside the
// signature parens) are inspected, so default-value text such as `{1: 2}`
// is never touched. The generator emits single-line signatures; a line whose
// parens do not close is passed through unchanged.
fn mangle_keyword_params(stub: &str) -> String {
    let mut out = String::with_capacity(stub.len());
    for line in stub.lines() {
        if line.trim_start().starts_with("def ") {
            out.push_str(&mangle_signature_line(line));
        } else {
            out.push_str(line);
        }
        out.push('\n');
    }
    out
}

fn mangle_signature_line(line: &str) -> String {
    let Some(open) = line.find('(') else {
        return line.to_string();
    };
    let bytes = line.as_bytes();
    let mut depth = 0usize;
    let mut result = String::with_capacity(line.len());
    let mut segment_start = open + 1;
    result.push_str(&line[..=open]);
    for (i, &b) in bytes.iter().enumerate().skip(open) {
        match b {
            b'(' | b'[' | b'{' => depth += 1,
            b')' if depth == 1 => {
                result.push_str(&mangle_segment(&line[segment_start..i]));
                result.push_str(&line[i..]);
                return result;
            }
            b')' | b']' | b'}' => depth -= 1,
            b',' if depth == 1 => {
                result.push_str(&mangle_segment(&line[segment_start..i]));
                result.push(',');
                segment_start = i + 1;
            }
            _ => {}
        }
    }
    line.to_string()
}

fn mangle_segment(segment: &str) -> String {
    let trimmed = segment.trim_start();
    if trimmed.starts_with('*') || trimmed.starts_with('/') || trimmed.is_empty() {
        return segment.to_string();
    }
    let ident_len = trimmed
        .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
        .unwrap_or(trimmed.len());
    let ident = &trimmed[..ident_len];
    if PY_KEYWORDS.contains(&ident) {
        let leading = &segment[..segment.len() - trimmed.len()];
        return format!("{leading}{ident}_{}", &trimmed[ident_len..]);
    }
    segment.to_string()
}

// pyo3-introspection emits write-only attributes (PyO3 `#[setter]` without a
// getter, e.g. DyCalculationInputs) as an orphan `@name.setter` block, which
// mypy rejects at build time (`Name "name" is not defined` — unallowlistable,
// it blocks stub compilation outright). Rewrite each orphan setter to the
// plain-attribute declaration the stub-expressible surface allows (the hand
// set's prior shape); a setter paired with a `@property` in the same file is
// left untouched. Property-set detection is file-level: the generator emits
// one class per property group and no seam file shares a property name across
// classes.
fn rewrite_orphan_setters(stub: &str) -> String {
    let lines: Vec<&str> = stub.lines().collect();
    let mut properties = std::collections::HashSet::new();
    for (i, line) in lines.iter().enumerate() {
        if line.trim() == "@property" {
            if let Some(def) = lines.get(i + 1) {
                if let Some(name) = def_name(def) {
                    properties.insert(name.to_string());
                }
            }
        }
    }
    let mut out = String::with_capacity(stub.len());
    let mut i = 0;
    while i < lines.len() {
        if let Some(name) = setter_decorator_name(lines[i]) {
            let orphan = !properties.contains(name);
            if orphan {
                if let Some((attr_line, consumed)) =
                    attribute_from_setter_block(name, &lines[i + 1..])
                {
                    out.push_str(&attr_line);
                    out.push('\n');
                    i += consumed;
                    continue;
                }
            }
        }
        out.push_str(lines[i]);
        out.push('\n');
        i += 1;
    }
    out
}

// The `def <name>(` of a signature line, if the line is a plain def.
fn def_name(line: &str) -> Option<&str> {
    let rest = line.trim_start().strip_prefix("def ")?;
    let end = rest.find('(')?;
    Some(rest[..end].trim())
}

// The `<name>` of an `@<name>.setter` decorator line.
fn setter_decorator_name(line: &str) -> Option<&str> {
    let trimmed = line.trim_start();
    let rest = trimmed.strip_prefix('@')?;
    let dot = rest.rfind(".setter")?;
    if dot + ".setter".len() != rest.len() {
        return None;
    }
    Some(rest[..dot].trim())
}

// The attribute declaration replacing an orphan setter block: the indented
// `@name.setter` line plus its `def name(self, /, v: T) -> None:` (with any
// docstring lines) becomes `name: T`. Returns the replacement line and the
// number of input lines consumed.
fn attribute_from_setter_block(name: &str, rest: &[&str]) -> Option<(String, usize)> {
    let mut indent = None;
    let mut param_type = None;
    let mut consumed = 1; // the decorator line itself
    let mut in_docstring = false;
    for line in rest {
        let trimmed = line.trim_start();
        if in_docstring {
            let closes = trimmed.contains("\"\"\"");
            consumed += 1;
            if closes {
                in_docstring = false;
            }
            continue;
        }
        if trimmed.is_empty() {
            break;
        }
        if indent.is_none() {
            indent = Some(line.len() - trimmed.len());
        }
        if let Some(def) = trimmed.strip_prefix("def ") {
            // def name(self, /, v: T) -> None:  [+ " ..."]
            let after_name = def.strip_prefix(name)?.strip_prefix('(')?.trim_start();
            let after_self = after_name.strip_prefix("self")?.trim_start();
            let after_slash = after_self.strip_prefix(", /")?.trim_start();
            let after_v = after_slash.strip_prefix(", v:")?.trim_start();
            let arrow = after_v.find("->")?;
            // after_v is `T) -> None:` — the parameter list's close paren
            // bounds the type (stub types carry no bare `)`).
            param_type = Some(
                after_v[..arrow]
                    .trim()
                    .strip_suffix(')')?
                    .trim()
                    .to_string(),
            );
        } else if let Some(body) = trimmed.strip_prefix("\"\"\"") {
            // docstring of the setter body — consumed, never carried over
            in_docstring = !body.contains("\"\"\"");
        } else {
            break;
        }
        consumed += 1;
    }
    let param_type = param_type?;
    let indent = indent?;
    Some((
        format!("{}{}: {param_type}", " ".repeat(indent), name),
        consumed,
    ))
}

// PyO3's `#[pymodule]` sets a runtime `__all__` from every added member,
// and stubtest compares the stub's exported-name set against it (with a
// declared `__all__`, mypy marks names absent from the list non-public, so
// the list also scopes re-exports). The generator's ground truth is the
// emitted top-level declarations, so `__all__` is derived from exactly
// those: module-level `def`/`class`/attribute lines, docstrings excluded.
// Modules whose runtime `__all__` carries members outside introspection
// (the root's `create_exception!` islands, cl-math's imperative boundary
// constants) keep their `__all__` gap in tests/rust/stubtest_allowlist.txt.
fn append_dunder_all(stub: &str) -> String {
    let mut names: Vec<&str> = Vec::new();
    let mut in_docstring = false;
    for line in stub.lines() {
        let quote_count = line.matches("\"\"\"").count();
        // Only lines wholly outside a docstring can start a declaration; a
        // line opening or closing a docstring carries prose at best.
        if !in_docstring && quote_count == 0 {
            if let Some(name) = exported_name(line) {
                names.push(name);
            }
        }
        in_docstring ^= quote_count % 2 == 1;
    }
    if names.is_empty() {
        return stub.to_string();
    }
    names.sort_unstable();
    let mut out =
        String::with_capacity(stub.len() + names.iter().map(|n| n.len() + 8).sum::<usize>() + 16);
    out.push_str(stub);
    out.push_str("\n__all__ = [\n");
    for name in names {
        out.push_str("    \"");
        out.push_str(name);
        out.push_str("\",\n");
    }
    out.push_str("]\n");
    out
}

// The name exported by a top-level declaration line: `def name(`, `class
// name` (generics or `:`), or an attribute (`NAME: T` / `NAME = ...`).
// Imports (`from x import y`, `import x`) never match: their identifier
// is followed by whitespace instead of `:` or ` =`. Private declarations
// (a leading underscore, e.g. the config projection's `@type_check_only`
// face classes) are skipped: `__all__` carries public exports, and mypy
// treats names absent from `__all__` as non-public.
fn exported_name(line: &str) -> Option<&str> {
    let name = if let Some(rest) = line.strip_prefix("def ") {
        let end = rest.find('(')?;
        rest[..end].trim()
    } else if let Some(rest) = line.strip_prefix("class ") {
        let end = rest.find([':', '(', ' '])?;
        rest[..end].trim()
    } else {
        let ident_len = line
            .find(|c: char| !(c.is_ascii_alphanumeric() || c == '_'))
            .unwrap_or(line.len());
        if ident_len == 0 {
            return None;
        }
        let rest = &line[ident_len..];
        if rest.starts_with(':') || rest.starts_with(" =") {
            &line[..ident_len]
        } else {
            return None;
        }
    };
    if name.starts_with('_') {
        None
    } else {
        Some(name)
    }
}

// The dotted Python module path of one emitted stub file: `__init__.pyi` is
// the module itself, `<name>.pyi` (at any depth) the leaf submodule of the
// same shape `module_stub_files` emits.
fn stub_file_module(rel: &Path, root: &str) -> String {
    let mut segments: Vec<String> = rel
        .iter()
        .map(|part| part.to_string_lossy().to_string())
        .collect();
    let file = segments.pop().unwrap_or_default();
    let stem = file.strip_suffix(".pyi").unwrap_or(file.as_str());
    if stem != "__init__" {
        segments.push(stem.to_owned());
    }
    if segments.is_empty() {
        root.to_owned()
    } else {
        format!("{root}.{}", segments.join("."))
    }
}

// The introspected module tree's dotted paths, rooted at the distribution
// package (`degenbot`): the manifest gate's module-existence half.
fn collect_module_paths(
    module: &Module,
    prefix: &str,
    out: &mut std::collections::BTreeSet<String>,
) {
    let path = format!("{prefix}.{}", module.name);
    out.insert(path.clone());
    for sub in &module.modules {
        collect_module_paths(sub, &path, out);
    }
}

// CLI progress diagnostics go to stderr; the tool is a recipe helper, not a
// library, so the workspace-wide print_stderr denial is scoped to this binary.
#[expect(clippy::print_stderr)]
fn dump(module: &pyo3_introspection::model::Module, depth: usize) {
    let pad = "  ".repeat(depth);
    eprintln!(
        "{pad}{}: {} classes, {} functions, {} submodules, {} attributes, incomplete={}",
        module.name,
        module.classes.len(),
        module.functions.len(),
        module.modules.len(),
        module.attributes.len(),
        module.incomplete
    );
    for sub in &module.modules {
        dump(sub, depth + 1);
    }
}

// See `dump`: stderr diagnostics are this binary's progress channel.
#[expect(clippy::print_stderr)]
fn main() -> Result<()> {
    let mut args = std::env::args().skip(1);
    let Some(binary) = args.next() else {
        bail!("usage: degenbot-stubgen <cdylib> <module-name> <outdir>")
    };
    let Some(module_name) = args.next() else {
        bail!("usage: degenbot-stubgen <cdylib> <module-name> <outdir>")
    };
    let Some(outdir) = args.next() else {
        bail!("usage: degenbot-stubgen <cdylib> <module-name> <outdir>")
    };

    let module = introspect_cdylib(Path::new(&binary), &module_name)
        .with_context(|| format!("introspect {binary} as {module_name}"))?;
    dump(&module, 0);

    // Manifest-vs-runtime gate (ADR-066 D3): the exception-island manifest
    // below only describes islands the runtime actually exports. A drifted
    // manifest entry (renamed create_exception! arm, dropped m.add) fails
    // generation here instead of emitting a class the runtime never had;
    // stubtest gates the reverse direction.
    let root_path = format!("degenbot.{module_name}");
    let mut module_paths = std::collections::BTreeSet::new();
    collect_module_paths(&module, "degenbot", &mut module_paths);
    let symbols = exception_manifest::symbol_blob(Path::new(&binary))
        .map_err(|err| anyhow!("exception manifest gate: {err}"))?;
    exception_manifest::validate(EXCEPTION_ISLANDS, &module_paths, &symbols)
        .map_err(|err| anyhow!("{err}"))?;

    let stubs = module_stub_files(&module);
    let out = Path::new(&outdir);
    std::fs::create_dir_all(out).with_context(|| format!("create output dir {}", out.display()))?;

    // Determinism: emit files in sorted order so two runs of the same cdylib
    // produce byte-identical trees (the drift gate diffs the committed set).
    let mut paths: Vec<_> = stubs.iter().collect();
    paths.sort();
    for (rel, content) in paths {
        let dest = out.join(rel);
        if let Some(parent) = dest.parent() {
            std::fs::create_dir_all(parent)
                .with_context(|| format!("create dir {}", parent.display()))?;
        }
        let projected = config_projection::apply(content)
            .map_err(|err| anyhow!("config projection splice failed: {err}"))?;
        let islands: Vec<exception_manifest::ExceptionIsland> = EXCEPTION_ISLANDS
            .iter()
            .filter(|island| island.python_module == stub_file_module(rel, &root_path))
            .copied()
            .collect();
        let spliced = exception_manifest::splice(&projected, &islands)
            .map_err(|err| anyhow!("exception island splice failed: {err}"))?;
        let stamped = format!(
            "{GENERATED_HEADER}{}",
            append_dunder_all(&rewrite_orphan_setters(&mangle_keyword_params(&spliced)))
        );
        std::fs::write(&dest, &stamped).with_context(|| format!("write {}", dest.display()))?;
        eprintln!("wrote {} ({} bytes)", dest.display(), stamped.len());
    }
    eprintln!("TOTAL: {} files", stubs.len());
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn keyword_param_is_mangled() {
        // The real emission that broke stubtest (src/degenbot/_ffi/provider.pyi).
        let stub = "    def estimate_gas(self, /, to: str, data: bytes, from: str |None = None, value: int |None = None) -> int:\n";
        assert_eq!(
            mangle_keyword_params(stub),
            "    def estimate_gas(self, /, to: str, data: bytes, from_: str |None = None, value: int |None = None) -> int:\n"
        );
    }

    #[test]
    fn non_keyword_params_pass_through() {
        let stub = "    def get_logs(self, /, *, from_block: int, to_block: int) -> list:\n";
        assert_eq!(mangle_keyword_params(stub), stub);
    }

    #[test]
    fn braced_colon_in_default_is_untouched() {
        let stub = "    def f(self, x: int = {1: 2}) -> None:\n";
        assert_eq!(mangle_keyword_params(stub), stub);
    }

    #[test]
    fn orphan_setter_becomes_plain_attribute() {
        let stub = concat!(
            "    @a_precision.setter\n",
            "    def a_precision(self, /, v: Any) -> None: ...\n",
            "    @address.setter\n",
            "    def address(self, /, v: str) -> None: ...\n",
        );
        assert_eq!(
            rewrite_orphan_setters(stub),
            concat!("    a_precision: Any\n", "    address: str\n")
        );
    }

    #[test]
    fn paired_property_setter_is_untouched() {
        let stub = concat!(
            "    @property\n",
            "    def snapshot_seed_block(self, /) -> int:\n",
            "        \"\"\"doc.\"\"\"\n",
            "    @snapshot_seed_block.setter\n",
            "    def snapshot_seed_block(self, /, v: int) -> None:\n",
            "        \"\"\"doc. more \"\"\" spans.\"\"\"\n",
            "        and more\n",
        );
        assert_eq!(rewrite_orphan_setters(stub), stub);
    }

    #[test]
    fn orphan_setter_with_docstring_is_fully_consumed() {
        let stub = concat!(
            "    @xp.setter\n",
            "    def xp(self, /, v: Any) -> None:\n",
            "        \"\"\"\n",
            "        Set xp.\n",
            "        \"\"\"\n",
            "\n",
            "def calculate_dy(i: int) -> Any:\n",
        );
        assert_eq!(
            rewrite_orphan_setters(stub),
            concat!("    xp: Any\n", "\n", "def calculate_dy(i: int) -> Any:\n")
        );
    }

    #[test]
    fn orphan_setter_single_line_docstring_is_fully_consumed() {
        let stub = concat!(
            "    @xp.setter\n",
            "    def xp(self, /, v: Any) -> None:\n",
            "        \"\"\"Set xp.\"\"\"\n",
            "\n",
            "def calculate_dy(i: int) -> Any:\n",
        );
        assert_eq!(
            rewrite_orphan_setters(stub),
            concat!("    xp: Any\n", "\n", "def calculate_dy(i: int) -> Any:\n")
        );
    }

    #[test]
    fn non_signature_lines_pass_through() {
        let stub = "class AlloyProvider:\n    from_ = 1\n\n";
        assert_eq!(mangle_keyword_params(stub), stub);
    }

    #[test]
    fn dunder_all_lists_top_level_exports_sorted() {
        let stub = concat!(
            "\"\"\"Module doc.\n",
            "\n",
            "prose line:\n",
            "def not_a_decl_in_docstring(x) -> None: ...\n",
            "\"\"\"\n",
            "from typing import Any, Final\n",
            "\n",
            "MAX_TICK: Final[int]\n",
            "\n",
            "@final\n",
            "class Widget:\n",
            "    def method(self, /) -> int: ...\n",
            "\n",
            "def make_widget(count: int) -> Widget: ...\n",
        );
        let out = append_dunder_all(stub);
        assert!(out.ends_with(
            "__all__ = [\n    \"MAX_TICK\",\n    \"Widget\",\n    \"make_widget\",\n]\n"
        ));
        // Imports and indented members are not module exports.
        assert!(!out.contains("\"Any\""));
        assert!(!out.contains("\"method\""));
        // The docstring's prose `def` is not an export either.
        assert!(!out.contains("not_a_decl_in_docstring\","));
    }

    #[test]
    fn dunder_all_absent_when_no_exports() {
        let stub = "from typing import Any\n";
        assert_eq!(append_dunder_all(stub), stub);
    }

    #[test]
    fn exported_name_handles_class_generics_and_assignment() {
        assert_eq!(exported_name("class Foo(Generic[T]):"), Some("Foo"));
        assert_eq!(exported_name("class Foo:"), Some("Foo"));
        assert_eq!(exported_name("x = 1"), Some("x"));
        assert_eq!(exported_name("MAX_TICK: Final[int]"), Some("MAX_TICK"));
        assert_eq!(exported_name("import sys"), None);
        assert_eq!(exported_name("from typing import Any"), None);
        assert_eq!(exported_name(""), None);
    }

    #[test]
    fn exported_name_skips_private_declarations() {
        // The config projection's face classes are stub-only privates; they
        // must not enter `__all__`.
        assert_eq!(exported_name("@type_check_only"), None);
        assert_eq!(exported_name("class _ConfigValuesFace:"), None);
        assert_eq!(exported_name("_hidden: int"), None);
        assert_eq!(
            exported_name("def __getattr__(name: str) -> Incomplete: ..."),
            None
        );
    }
}
