"""Uniswap V2 constant-product swap math.

See: contract_reference/uniswap/V2/UniswapV2Factory.sol
(UniswapV2Pair, UniswapV2Factory, Math, UQ112x112)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from degenbot.abi import encode_packed
from degenbot.contract.addresses import create2_address
from degenbot.crypto import keccak256
from degenbot.utils.bytes import to_bytes

if TYPE_CHECKING:
    from collections.abc import Iterable

    from degenbot.types.chain import ChecksummedAddress


def generate_v2_pool_address(
    deployer_address: str | bytes,
    token_addresses: Iterable[str | bytes],
    init_hash: str | bytes,
) -> ChecksummedAddress:
    """Get the deterministic V2 pool address generated by CREATE2.

    Uses the token addresses sorted to generate the salt.
    The token addresses can be passed in any order.

    Returns:
        The checksummed pool address.

    Adapted from https://github.com/Uniswap/universal-router/blob/59f1291d3760d2537a7bd1cbf37317922a49efb0/contracts/modules/uniswap/v2/UniswapV2Library.sol#L50

    """
    sorted_token_addresses = sorted([to_bytes(address) for address in token_addresses])

    salt = keccak256(
        encode_packed(
            ["address", "address"],
            [*sorted_token_addresses],
        ),
    )

    return create2_address(
        deployer=deployer_address,
        salt=salt,
        init_code_hash=init_hash,
    )
