"""Uniswap V2 constant-product swap math.

See: contract_reference/uniswap/V2/UniswapV2Factory.sol
(UniswapV2Pair, UniswapV2Factory, Math, UQ112x112)
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from degenbot._ffi import generate_v2_pool_address as _rs_generate_v2_pool_address
from degenbot.utils.bytes import to_0x_hex

if TYPE_CHECKING:
    from collections.abc import Iterable

    from degenbot.types.chain import ChecksummedAddress


def generate_v2_pool_address(
    deployer_address: str | bytes,
    token_addresses: Iterable[str | bytes],
    init_hash: str | bytes,
) -> ChecksummedAddress:
    """Get the deterministic V2 pool address generated by CREATE2.

    Uses the token addresses sorted to generate the salt.
    The token addresses can be passed in any order.

    Returns:
        The checksummed pool address.

    Adapted from https://github.com/Uniswap/universal-router/blob/59f1291d3760d2537a7bd1cbf37317922a49efb0/contracts/modules/uniswap/v2/UniswapV2Library.sol#L50

    """
    t0, t1 = (to_0x_hex(a) for a in token_addresses)
    return _rs_generate_v2_pool_address(
        to_0x_hex(deployer_address),
        t0,
        t1,
        to_0x_hex(init_hash),
    )
