"""Aave V3: make gho_discount column non-nullable

Revision ID: 2d0579b14b94
Revises: 2ed86347e07f
Create Date: 2026-01-28 11:57:58.002541

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2d0579b14b94'
down_revision: str | Sequence[str] | None = '2ed86347e07f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aave_v3_users', schema=None) as batch_op:
        batch_op.alter_column('gho_discount',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""    
    msg = "Downgrade is not supported for this migration."
    raise NotImplementedError(msg)
    