"""Aave V3 (GHO Token): add discount token column

Revision ID: 2ed86347e07f
Revises: d44ed01ad765
Create Date: 2026-01-26 17:02:42.042980

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '2ed86347e07f'
down_revision: str | Sequence[str] | None = 'd44ed01ad765'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aave_gho_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('v_gho_discount_token', sa.String(length=42), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""    
    msg = "Downgrade is not supported for this migration."
    raise NotImplementedError(msg)
    