"""Aave V3: add stkAAVE balance column

Revision ID: 3b62cfcbc261
Revises: 2d0579b14b94
Create Date: 2026-02-04 11:26:13.438530

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3b62cfcbc261'
down_revision: str | Sequence[str] | None = '2d0579b14b94'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aave_v3_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stk_aave_balance', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""    
    msg = "Downgrade is not supported for this migration."
    raise NotImplementedError(msg)
    