"""Aave V3: Add GHO token table

Revision ID: d44ed01ad765
Revises: 25e0cb6efa03
Create Date: 2026-01-24 13:18:35.914451

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd44ed01ad765'
down_revision: str | Sequence[str] | None = '25e0cb6efa03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aave_gho_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('v_gho_discount_rate_strategy', sa.String(length=42), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['erc20_tokens.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aave_gho_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aave_gho_tokens_token_id'), ['token_id'], unique=False)

    with op.batch_alter_table('aave_v3_assets', schema=None) as batch_op:
        batch_op.alter_column('a_token_revision',
               existing_type=sa.BLOB(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""    
    msg = "Downgrade is not supported for this migration."
    raise NotImplementedError(msg)
    