# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the aave-updater seam on `m` (feature = "aave-updater"). Mirrors
the declarative `crate::pool::pool` `#[pymodule]`. `CancelHandle` is
registered separately by the declarative `crate::cancel::cancel`
`#[pymodule]` (shared).

# Errors

Returns a [`PyErr`] if the `add_function` call fails (a name collision);
propagated unchanged to the `#[pymodule]` caller.
The `degenbot._ffi.aave` Python submodule (declarative `#[pymodule]`;
the Python-facing name is `aave`, not `aave_updater`), carrying the Aave
chunk-loop + verify/maintenance pyfunctions. The parent module registers
the submodule itself and its `sys.modules` entry. `CancelHandle` is
registered separately by `crate::cancel::cancel` (shared).
"""

from .cancel import CancelHandle
from collections.abc import Sequence

def activate_aave_market(
    database_path: str,
    chain_id: int,
    pool_address_provider: str,
    gho_token_address: str,
    rpc_url: str,
) -> dict:
    """
    `degenbot._ffi.aave.activate_aave_market(database_path, chain_id,
    pool_address_provider, gho_token_address, rpc_url) -> dict`

    Seed (or re-activate) an Aave V3 market — the ONE-TIME setup the chunk
    loop's `run_aave_update` bootstraps from. Rust-owned replacement for the
    Python `activate_ethereum_aave_v3` (commands.py) — the last ORM writer on
    the Aave path after the §4.2 retirement. Activates the market,
    inserts the `POOL_ADDRESS_PROVIDER` contract row, + seeds the GHO
    `erc20_tokens` + `aave_gho_tokens` rows, all in ONE transaction.

    The GIL is released across the WHOLE call (`py.detach`) — the core owns
    its tokio runtime + does the RPC fetches (`getMarketId()` + GHO metadata)
    + the DB writes internally.

    # Returns

    A `dict` `{market_id, market_name, created}` — `market_id` is the
    `aave_v3_markets.id` to pass to `run_aave_update`; `created` is `True` if
    the market was newly created, `False` if it pre-existed (re-activation).

    # Raises

    `ValueError` on a DB / RPC / address-parse failure.
    """

def cleanup_zero_balance_positions(database_path: str, market_id: int) -> None:
    """
    `degenbot._ffi.aave.cleanup_zero_balance_positions(database_path, market_id)`

    Delete all zero-balance collateral + debt positions for `market_id`.
    Mirrors the Python `cleanup_zero_balance_positions` (verification.py:19).
    Opens the DB for writes, deletes, + commits. The GIL is released across
    the call.
    """

def deactivate_aave_market(database_path: str, market_id: int) -> None:
    """
    `degenbot._ffi.aave.deactivate_aave_market(database_path, market_id) -> None`

    Set `active = False` for `market_id`. Rust-owned replacement for the
    Python `deactivate_mainnet_aave_v3` (commands.py). The GIL is released
    across the call.

    # Raises

    `ValueError` if `market_id` doesn't exist or on a DB failure.
    """

def run_aave_update(
    database_path: str,
    chain_id: int,
    market_id: int,
    to_block: int | None,
    chunk_size: int,
    rpc_url: str,
    cancel_handle: CancelHandle,
    verify_chunk: bool = False,
    max_chunks: int | None = None,
    *,
    verify_all_interval: int | None = None,
    verify_all_at_completion: bool = False,
) -> dict:
    """
    `degenbot._ffi.aave.run_aave_update(database_path, chain_id, market_id, to_block,
    chunk_size, rpc_url, cancel_handle, verify_chunk,
    max_chunks) -> dict`

    Drive the Rust-owned Aave V3 updater chunk loop for `market_id`, advancing
    `aave_v3_markets.last_update_block` to `to_block` (or the chain tip if
    `to_block is None`). See
    [`degenbot_aave::run::run_aave_update`] for the §3.4 atomicity
    invariant (one `Transaction` per chunk; failure mid-chunk → rollback →
    `last_update_block` unchanged → restart re-processes clean).

    The GIL is released across the WHOLE run (`py.detach`) and the core
    emits its own throttled operator progress lines — no per-chunk
    GIL re-acquisition. A Python-side `KeyboardInterrupt` won't pre-empt
    mid-chunk; the SIGINT handler calls `cancel_handle.cancel()` (the
    cooperative flag the loop polls between chunks — §3.3 interrupt contract:
    SIGINT between chunks → honored immediately; SIGINT mid-chunk → the chunk
    completes atomically first).

    # Args

    - `database_path` — the writeable `DegenbotDb` path.
    - `chain_id` — the chain.
    - `market_id` — the `aave_v3_markets.id` to advance.
    - `to_block` — `int` to advance to a specific block; `None` for the tip.
    - `chunk_size` — blocks per chunk.
    - `rpc_url` — the HTTP RPC endpoint.
    - `cancel_handle` — a [`CancelHandle`] (shared with `run_pool_update`);
      a `signal.SIGINT` handler calls `.cancel()`.
    - `verify_chunk` — if `True`, run pre-commit verification on each chunk:
      Rust calls `verify_touched_positions_on_conn` on the uncommitted
      transaction BEFORE `tx.commit()`. A divergence drops the tx (rollback)
      so `last_update_block` does NOT advance + the next run re-processes the
      same chunk. If `False`, verification is skipped (chunks commit without
      checking).
    - `max_chunks` — `None` to advance to `to_block`/tip; `Some(n)` to stop
      after committing `n` chunks (one-chunk mode). `last_update_block` is
      advanced to the last committed chunk's end, so the next run resumes
      from there. Previously the Python `--one-chunk` flag was downgraded to
      a warning by the cutover shell; this restores first-class support.

    # Returns

    A `dict` `{chain_id, market_id, from_block, to_block, chunks_committed,
    total_events_applied}`.

    # Raises

    `ValueError` on a DB / RPC / config-dispatch / parse failure (the in-flight
    chunk is rolled back before returning; committed chunks stay durable).
    `RuntimeError` if cancelled.
    `AssertionError` if `verify_chunk=True` and pre-commit verification found
    divergences (the in-flight chunk is rolled back — the chunk's data is NOT
    committed; `last_update_block` did NOT advance).

    # Runtime nesting

    Must NOT be called from within an existing `tokio` runtime (the core owns
    its runtime; nesting panics). See the module docs.
    """

def verify_all_positions_on_chain(
    database_path: str,
    rpc_url: str,
    market_id: int,
    chain_id: int,
    block_number: int,
    touched_users: Sequence[str] | None = None,
) -> list[dict]:
    """
    `degenbot._ffi.aave.verify_all_positions_on_chain(database_path, rpc_url,
    market_id, chain_id, block_number, touched_users=None) -> list[dict]`

    Full on-chain-truth verification — the Rust port of Python's
    `verify_all_positions` (verification.py) + `verify_stk_aave_balances` +
    `verify_gho_discount_amounts` (`db_verification.py`). Runs all 4 checks:
    1. Collateral scaled-token balance + `last_index`.
    2. Debt scaled-token balance + `last_index`.
    3. stkAAVE balance (`balanceOf` on the discount token).
    4. GHO discount percent (`getDiscountPercent` on the GHO vToken,
       with the revision-based skip guard).

    Returns a list of divergence dicts (empty = GREEN). Each dict has a
    `check` field (`"scaled_token"`, `"stk_aave_balance"`, or
    `"gho_discount"`) plus the relevant fields for that check type.

    The GIL is released across the whole call. Zero SQL writes —
    [`cleanup_zero_balance_positions`] is the separate write companion.

    # Args

    - `database_path` — the `DegenbotDb` path (opened read-only).
    - `rpc_url` — the HTTP RPC endpoint.
    - `market_id` — the `aave_v3_markets.id` to verify.
    - `chain_id` — the chain ID (needed to resolve the GHO asset row).
    - `block_number` — the block to verify against.
    - `touched_users` — `None` (default) verifies ALL positions/users;
      `Some(["0x...", ...])` verifies only those users.
    """

def verify_touched_positions_on_chain(
    database_path: str,
    rpc_url: str,
    market_id: int,
    chain_id: int,
    block_number: int,
    touched_users: Sequence[str] | None = None,
) -> list[dict]:
    """
    `degenbot._ffi.aave.verify_touched_positions_on_chain(database_path, rpc_url,
    market_id, chain_id, block_number, touched_users=None) -> list[dict]`

    Minimal-slice Rust port of Python's
    `verification.py::verify_scaled_token_positions` (collateral + debt
    dimensions only).

    Loads `aave_v3_collateral_positions` + `aave_v3_debt_positions` from
    `database_path` (filtered by `touched_users` when given) joined to the
    user address + the aToken/vToken erc20 token address, then for each
    position (skipping `DEAD_ADDRESS` / `ZERO_ADDRESS` users, mirroring the
    Python) RPC `scaledBalanceOf(user)` + `getPreviousIndex(user)` on the
    aToken / vToken at `block_number` + asserts equality with the DB `balance`
    + `last_index`.

    Returns a list of divergence dicts (empty = GREEN). Each dict has:
    `kind`, `position_id`, `user_address`, `token_address`, `block_number`,
    `field`, `expected`, `actual` — the same shape the JGQHBX drive harness's
    compare divergences emit, so it's bisect-able.

    Per-position `eth_call`s — acceptable for the touched-users-per-chunk case
    (small set). Multicall3 batching for the market-wide verify is the natural
    extension (BE474R-full, post-HLYWI6).

    The GIL is released across the whole call (`py.detach`); the orchestrator
    drives its RPC fetches/verifies on the process-wide shared runtime
    (`degenbot_core::runtime::get_runtime()`) + owns the
    `AlloyProvider` internally. Zero SQL writes.

    # Args

    - `database_path` — the `DegenbotDb` path (opened read-only).
    - `rpc_url` — the HTTP RPC endpoint.
    - `market_id` — the `aave_v3_markets.id` to verify.
    - `chain_id` — reserved for parity with `run_aave_update`; not used in
      the verify path (the writer-state already filtered to `market_id`).
    - `block_number` — the block to verify against (`chunk_end` in the
      per-chunk gate).
    - `touched_users` — `None` (default) verifies ALL positions;
      `["0x...", ...]` verifies only those users (the JGQHBX drive harness's
      per-chunk path passes the `touched_user_addresses` from
      `run_aave_update`'s progress dict for efficiency).
    """

__all__ = [
    "activate_aave_market",
    "cleanup_zero_balance_positions",
    "deactivate_aave_market",
    "run_aave_update",
    "verify_all_positions_on_chain",
    "verify_touched_positions_on_chain",
]
