# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.abi` Python submodule (declarative `#[pymodule]`).

Carries the ABI decode/encode fns (`decode`/`decode_single`/`encode`/
`encode_packed`/`encode_single`). Unlike the math submodules, no
de-prefixing is needed — these fns were already un-prefixed; the win is
the submodule + companion home (importers reach them via
`degenbot.abi_adapter`, not `degenbot._ffi`). The parent module
registers the submodule itself and its `sys.modules` entry.
"""

from typing import Any

def decode(types: list, data: bytes, checksum: bool = True) -> Any:
    """
    Decode ABI-encoded data for multiple types.

    # Arguments

    * `types` - List of ABI type strings
    * `data` - Raw ABI-encoded bytes
    * `checksum` - If true (default), returns checksummed addresses

    # Returns

    A list of decoded Python values.

    # Architecture

    This PyO3-exposed function is a thin wrapper around the pure Rust `decode_rust`.
    The decoding happens entirely without GIL, then results are converted to Python
    objects in a single pass. This enables:
    - Parallel decoding without GIL contention
    - Pure Rust unit testing
    - Clean separation of concerns
    """

def decode_single(abi_type: str, data: bytes, checksum: bool = True) -> Any:
    """
    Decode a single ABI value.

    Convenience function for decoding a single value.

    # Architecture

    This PyO3-exposed function wraps `decode_single_rust` for consistent architecture.
    """

def encode(types: list, values: list) -> bytes:
    """
    Encode multiple ABI values.

    # Arguments

    * `types` - List of ABI type strings
    * `values` - List of Python values to encode

    # Returns

    The ABI-encoded bytes.
    """

def encode_packed(types: list, values: list) -> bytes:
    """
    Pack-encode multiple ABI values (Solidity `abi.encodePacked`).

    # Arguments

    * `types` - List of ABI type strings
    * `values` - List of Python values to pack-encode

    # Returns

    The packed-encoded bytes (no padding, no length prefixes).
    """

def encode_single(abi_type: str, value: Any) -> bytes:
    """
    Encode a single ABI value.

    # Arguments

    * `abi_type` - ABI type string (e.g., "uint256", "address", "bytes")
    * `value` - The value to encode

    # Returns

    The ABI-encoded bytes.
    """

__all__ = [
    "decode",
    "decode_single",
    "encode",
    "encode_packed",
    "encode_single",
]
