# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the `degenbot._ffi.backrun` submodule (the feed pump).

# Errors

Propagates any `PyResult` failure from the module add calls.
The `degenbot._ffi.backrun` Python submodule (declarative
`#[pymodule]`), carrying the backrun pipeline feed pyclass. The parent
module registers the submodule itself and its `sys.modules` entry.
"""

from typing import Any, final

@final
class BackrunFeed:
    """
    Live `MEVBlocker` searcher feed handle (RSUB-2).

    The struct keeps the Rust-internal `Py` prefix; the Python-facing name is
    the ADR-032 clean form (`BackrunFeed`) — the naming gate extends no
    grandfather list.
    """
    def __new__(
        cls, /, url: str | None = None, watchdog_secs: int = 0, ring_capacity: int = 0
    ) -> BackrunFeed:
        """
        Spawn the feed pump. Watchdog/ring/backoff are config-able; `0`
        watchdog selects the production default.
        """
    def drain(self, /) -> list[Any]:
        """
        Drain all buffered events (plain dicts; lossless fields).
        """
    def status(self, /) -> Any:
        """
        Counters snapshot as a plain dict.
        """
    def stop(self, /) -> None: ...

__all__ = [
    "BackrunFeed",
]
