# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the Balancer-math functions as a real Python submodule.

Creates `degenbot._ffi.balancer_math` (a `PyModule`, not a flat
root-level prefix) and registers the 12 swap-path math functions on it
with un-prefixed names — `fixed_point_mul_down`, not
`balancer_fixed_point_mul_down`. The `balancer_` prefix was an artifact
of the flat root registration; on the submodule it is redundant.

The companion `src/degenbot/balancer/math.py` re-exports these as the
stable import path (`from degenbot.balancer.math import fixed_point_div_down`),
decoupling Python consumers from the `degenbot._ffi` internal module and
letting the Rust crate structure show through to Python.

# Errors

Returns `PyErr` if any function fails to register.
The `degenbot._ffi.balancer_math` Python submodule (declarative
`#[pymodule]`), carrying the weighted / fixed-point / stable math
pyfunctions. The parent module registers the submodule itself; the
`sys.modules["degenbot._ffi.balancer_math"]` entry (needed for the
dotted-path import — the extension module is a single file, not a
package) lives in the parent's shared helper.
"""

from typing import Any

def fixed_point_div_down(a: Any, b: Any) -> Any:
    """
    `FixedPoint._div_down(a, b) = a * ONE / b`, rounding down.

    # Errors

    Returns `ValueError` (`ZERO_DIVISION`) on `b == 0`; `OverflowError`
    (`DIV_INTERNAL`) when `a * ONE` exceeds `MAX_UINT256`.
    """

def fixed_point_div_up(a: Any, b: Any) -> Any:
    """
    `FixedPoint._div_up(a, b) = (a * ONE - 1) / b + 1`, rounding up.

    # Errors

    Returns `ValueError` (`ZERO_DIVISION`) on `b == 0`; `OverflowError`
    (`DIV_INTERNAL`) when `a * ONE` exceeds `MAX_UINT256`.
    """

def fixed_point_mul_down(a: Any, b: Any) -> Any:
    """
    `FixedPoint._mul_down(a, b) = a * b / ONE`, rounding down.

    Uses `widening_mul` + truncation (mirrors Solidity's `uint256` return for
    over-large-but-unreachable inputs); the deployed contract reverts on
    `a * b > MAX_UINT256` — observable only for adversarial inputs the bot
    never feeds in normal swap math. C8d: routes `scaling_helpers` off the
    pure-Python `fixed_point.py` port.

    # Errors

    Never reverts (differs from the Python port's `MUL_OVERFLOW` check,
    which is unreachable for valid scaling factors).
    """

def stable_calc_in_given_out(
    amp: Any,
    balances: Any,
    token_index_in: int,
    token_index_out: int,
    token_amount_out: Any,
    invariant: Any,
) -> Any:
    """
    Stable `calc_in_given_out` (`StableMath._calc_in_given_out`).

    # Errors

    Returns `ValueError` (`STABLE_GET_BALANCE_DIDNT_CONVERGE`/`SUB_OVERFLOW`) on non-convergence or underflow.
    """

def stable_calc_out_given_in(
    amp: Any,
    balances: Any,
    token_index_in: int,
    token_index_out: int,
    token_amount_in: Any,
    invariant: Any,
) -> Any:
    """
    Stable `calc_out_given_in` (`StableMath._calc_out_given_in`).

    # Errors

    Returns `ValueError` (`STABLE_GET_BALANCE_DIDNT_CONVERGE`/`SUB_OVERFLOW`) on non-convergence or underflow.
    """

def stable_calculate_invariant(amp: Any, balances: Any) -> Any:
    """
    `StableSwap` invariant (`StableMath._calculate_invariant`, V1 always-roundDown `D_P`).

    # Errors

    Returns `ValueError` (`STABLE_INVARIANT_DIDNT_CONVERGE`) if Newton iteration fails to converge.
    """

def stable_calculate_invariant_deployed(amp: Any, balances: Any, round_up: bool) -> Any:
    """
    `StableSwap` deployed invariant (`StableMath._calculate_invariant_deployed`, V2 round-up-param `P_D`).

    # Errors

    Returns `ValueError` (`STABLE_INVARIANT_DIDNT_CONVERGE`) if Newton iteration fails to converge.
    """

def weighted_add_swap_fee_amount(amount: Any, fee_percentage: Any) -> Any:
    """
    Add the swap fee (`WeightedMath._add_swap_fee_amount`): `amount + mul_up(amount, fee)`.

    # Errors

    Returns `OverflowError` (`MUL_OVERFLOW`/`ADD_OVERFLOW`) on overflow.
    """

def weighted_calc_in_given_out(
    balance_in: Any,
    weight_in: Any,
    balance_out: Any,
    weight_out: Any,
    amount_out: Any,
    version: int,
) -> Any:
    """
    Weighted `calc_in_given_out` (`WeightedMath._calc_in_given_out`).

    # Errors

    Returns `ValueError` (`MAX_OUT_RATIO`) if `amount_out` exceeds 30% of `balance_out`, plus overflow reverts.
    """

def weighted_calc_out_given_in(
    balance_in: Any, weight_in: Any, balance_out: Any, weight_out: Any, amount_in: Any, version: int
) -> Any:
    """
    Weighted `calc_out_given_in` (`WeightedMath._calc_out_given_in`).

    # Errors

    Returns `ValueError` (`MAX_IN_RATIO`) if `amount_in` exceeds 30% of `balance_in`, plus overflow reverts.
    """

def weighted_calculate_invariant(normalized_weights: Any, balances: Any, version: int) -> Any:
    """
    Weighted-product invariant (`WeightedMath._calculateInvariant`).

    # Errors

    Returns `OverflowError`/`ValueError` (Solidity revert tag) on overflow or a zero invariant.
    """

def weighted_subtract_swap_fee_amount(amount: Any, fee_percentage: Any) -> Any:
    """
    Subtract the swap fee (`WeightedMath._subtract_swap_fee_amount`): `amount - mul_up(amount, fee)`.

    # Errors

    Returns `OverflowError` (`MUL_OVERFLOW`/`SUB_OVERFLOW`) on overflow.
    """

__all__ = [
    "fixed_point_div_down",
    "fixed_point_div_up",
    "fixed_point_mul_down",
    "stable_calc_in_given_out",
    "stable_calc_out_given_in",
    "stable_calculate_invariant",
    "stable_calculate_invariant_deployed",
    "weighted_add_swap_fee_amount",
    "weighted_calc_in_given_out",
    "weighted_calc_out_given_in",
    "weighted_calculate_invariant",
    "weighted_subtract_swap_fee_amount",
]
