# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.cancel` Python submodule (declarative `#[pymodule]`),
carrying the shared [`CancelHandle`] pyclass. Called by the parent module
under `any(feature = "pool", feature = "aave-updater")` — whichever
updater seam is enabled needs the class registered. No-op-safe when both
are enabled (a single declarative export).
"""

from typing import final

@final
class CancelHandle:
    """
    `degenbot._ffi.cancel.CancelHandle` — the cooperative cancel flag for the
    long-running updater loops (`run_pool_update`, `run_aave_update`).

    Construct up front; pass to `run_pool_update` / `run_aave_update`; a
    `signal.SIGINT` handler (installed by the CLI driver) calls `.cancel()` to
    stop the run at the next chunk boundary. The loop polls the flag between
    chunks (NOT mid-chunk) so a cancel never breaks the chunk's atomicity — the
    in-flight chunk completes (commit or rollback) before the run returns, the
    committed chunks stay durable.

    This is preferred over a module-level `set_cancel()` accessor (a
    `OnceLock<Arc<AtomicBool>>`): the handle is per-run (no global mutable
    state, no race between concurrent runs, no stale global stuck "set" after
    a run), + Python owns the lifetime (drop after the run). Mirrors the
    `Arc<AtomicBool>` the core `run_pool_update` / `run_aave_update` take.
    """
    def __new__(cls, /) -> CancelHandle:
        """
        Construct a fresh cancel handle (flag initially `false`).
        """
    def cancel(self, /) -> None:
        """
        Request cancellation. Honored at the next chunk boundary (after the
        current chunk completes atomically). Idempotent.
        """
    def is_cancelled(self, /) -> bool:
        """
        Whether cancellation was requested. Useful for tests + for a CLI
        driver that wants to observe whether its own SIGINT handler fired.
        """
    def reset(self, /) -> None:
        """
        Reset the flag to `false` (reuse the handle for a fresh run).
        Not normally needed (construct a fresh handle per run), but offered
        for the test harness + the "run, observe, re-run" CLI shell.
        """

__all__ = [
    "CancelHandle",
]
