# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.concentrated_liquidity_math` Python submodule
(declarative `#[pymodule]`).

Combines the swap-path math functions in `lib.rs` (`BitMath`/`FullMath`/
`UnsafeMath`/`LiquidityMath`/`SqrtPriceMath`/`SwapMath`/`TickMath` helpers/
`LiquidityMapping`), the 2 `tick_math.rs` entry points
(`get_sqrt_ratio_at_tick` / `get_tick_at_sqrt_ratio`), and the 4
`TickMath` boundary constants (`MIN_TICK`/`MAX_TICK`/
`MIN_SQRT_RATIO`/`MAX_SQRT_RATIO`) — previously all flat on the root
`_ffi` namespace — onto one real submodule with un-prefixed names
(`muldiv`, not `cl_muldiv`). The parent module registers the submodule
itself; the `sys.modules` entry lives in the parent's shared helper.

The companion `src/degenbot/uniswap/math.py` re-exports these as the
stable import path, decoupling Python consumers from `degenbot._ffi`.
"""

from _typeshed import Incomplete
from typing import Any, Final

MAX_TICK: Final[int]
MIN_TICK: Final[int]

def compute_swap_step_v3(
    sqrt_price_current: Any,
    sqrt_price_target: Any,
    liquidity: Any,
    amount_remaining: Any,
    fee_pips: Any,
) -> Any:
    """
    Compute a V3-style swap step.

    # Errors

    Returns `PyValueError` on invalid input, overflow, or if liquidity exceeds int128.
    """

def compute_swap_step_v4(
    sqrt_price_current: Any,
    sqrt_price_target: Any,
    liquidity: Any,
    amount_remaining: Any,
    fee_pips: Any,
) -> Any:
    """
    Compute a V4-style swap step.

    # Errors

    Returns `PyValueError` on invalid input, overflow, or if liquidity exceeds int128.
    """

def get_sqrt_ratio_at_tick(tick: int) -> Any:
    """
    Converts a tick value to its corresponding sqrt price (X96 format).

    This function calculates the sqrt price for a given tick value using the
    Uniswap V3 tick math formula. The result is returned as a native Python int.

    # Arguments

    * `tick` - The tick value in range [-887272, 887272]

    # Returns

    A Python int representing the sqrt price X96 value

    # Errors

    Returns `PyValueError` if the tick value is invalid

    # Example

    ```python
    from degenbot._ffi.concentrated_liquidity_math import get_sqrt_ratio_at_tick

    ratio = get_sqrt_ratio_at_tick(0)
    ```
    """

def get_tick_at_sqrt_ratio(sqrt_price_x96: Any) -> int:
    """
    Converts a sqrt price (X96 format) to its corresponding tick value.

    This function calculates the tick for a given sqrt price using the
    Uniswap V3 tick math formula. The result is returned as a Python `i32`.

    # Arguments

    * `sqrt_price_x96` - The sqrt price X96 value as a Python `int` or `bytes`

    # Returns

    The tick value corresponding to the given sqrt price

    # Errors

    Returns `PyValueError` if:
    - The input is too large (exceeds 20 bytes)
    - The sqrt price is outside the valid [`MIN_SQRT_RATIO`, `MAX_SQRT_RATIO`) range

    [`MIN_SQRT_RATIO`]: degenbot_math::cl::tick_math::MIN_SQRT_RATIO
    [`MAX_SQRT_RATIO`]: degenbot_math::cl::tick_math::MAX_SQRT_RATIO

    Returns `PyTypeError` if the input is not an int or bytes

    # Example

    ```python
    from degenbot._ffi.concentrated_liquidity_math import get_tick_at_sqrt_ratio

    tick = get_tick_at_sqrt_ratio(79228162514264337593543950336)
    ```
    """

def get_tick_word_and_bit_position(tick: int, tick_spacing: int) -> tuple[int, int]:
    """
    Compute the tick word and bit position for a compressed tick.

    Returns `(word, bit)` where `word` is the mapping key (`i32`) and `bit`
    is in `0..=255` (`u8`). Mirrors `degenbot_math::cl::get_tick_word_and_bit_position`.
    """

def least_significant_bit(x: Any) -> int:
    """
    Find the index of the least significant bit set in `x`.

    # Errors

    Returns `PyValueError` if `x` is zero.
    """

def most_significant_bit(x: Any) -> int:
    """
    Find the index of the most significant bit set in `x`.

    # Errors

    Returns `PyValueError` if `x` is zero.
    """

def muldiv(a: Any, b: Any, denominator: Any) -> Any:
    """
    Compute `floor(a * b / denominator)` with full 512-bit precision.

    # Errors

    Returns `PyValueError` on division by zero or overflow.
    """

def muldiv_rounding_up(a: Any, b: Any, denominator: Any) -> Any:
    """
    Compute `ceil(a * b / denominator)` with full 512-bit precision.

    # Errors

    Returns `PyValueError` on division by zero or overflow.
    """

def __getattr__(name: str) -> Incomplete: ...

__all__ = [
    "MAX_TICK",
    "MIN_TICK",
    "compute_swap_step_v3",
    "compute_swap_step_v4",
    "get_sqrt_ratio_at_tick",
    "get_tick_at_sqrt_ratio",
    "get_tick_word_and_bit_position",
    "least_significant_bit",
    "most_significant_bit",
    "muldiv",
    "muldiv_rounding_up",
]
