# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.contract` Python submodule (declarative
`#[pymodule]`), carrying the contract seam pyclass + ABI
call/decode/selector pyfunctions (plus the async contract under
`feature = "async"`). The parent module registers the submodule itself
and its `sys.modules` entry.
"""

from collections.abc import Sequence
from typing import Any, final

from .provider import AlloyProvider

@final
class AsyncContract:
    """
    Async contract wrapper for Python.
    """
    @property
    def address(self, /) -> str:
        """
        Get the contract address.
        """
    def batch_call(
        self, /, calls: Sequence[tuple[str, Sequence[str]]], block_number: int | None = None
    ) -> Any:
        """
        Batch execute multiple contract calls in parallel.

        Args:
            calls: List of (`function_signature`, args) tuples
            `block_number`: Optional block number to query

        Returns:
            List of results, where each result is a list of decoded return values
        """
    def call(
        self, /, function_signature: str, args: Sequence[str], block_number: int | None = None
    ) -> Any:
        """
        Execute a contract call asynchronously.

        Args:
            `function_signature`: Function signature like "balanceOf(address)"
            args: List of arguments as strings
            `block_number`: Optional block number to query

        Returns:
            List of decoded return values as strings
        """
    @staticmethod
    def create(address: str, provider_url: str, max_retries: int | None = None) -> Any:
        """
        Create a new async contract instance.

        Args:
            address: Contract address (hex string)
            `provider_url`: RPC provider URL (HTTP/HTTPS or IPC path)
        """
    @staticmethod
    def from_provider(address: str, provider: AlloyProvider) -> AsyncContract:
        """
        Create an async contract from an existing `AlloyProvider`, sharing
        its connection pool across multiple contract instances.

        Args:
            address: Contract address (hex string)
            provider: An existing `AlloyProvider` instance
        """

@final
class Contract:
    """
    Python wrapper for a Contract.
    """
    def __new__(cls, /, address: str, provider_url: str | None = None) -> Contract:
        """
        Create a new contract instance.

        Args:
            address: Contract address (hex string)
            `provider_url`: RPC provider URL (optional, defaults to localhost)
        """
    @property
    def address(self, /) -> str:
        """
        Get the contract address.
        """
    def call(self, /, function_signature: str, args: list, block_number: int | None = None) -> list:
        """
        Execute a contract call.

        Args:
            `function_signature`: Function signature like "balanceOf(address)"
            args: List of arguments as strings
            `block_number`: Optional block number to query

        Returns:
            List of decoded return values as strings
        """
    def call_typed(
        self, /, function_signature: str, args: list, block_number: int | None = None
    ) -> list:
        """
        Execute a contract call and return decoded values as Python types.

        Unlike `call` which returns strings, this method returns native
        Python types (int, bool, str, bytes, list) avoiding the string
        round-trip overhead.

        Args:
            `function_signature`: Function signature like "balanceOf(address)"
            args: List of arguments as strings
            `block_number`: Optional block number to query

        Returns:
            List of decoded return values as native Python types
        """
    @staticmethod
    def from_provider(address: str, provider: AlloyProvider) -> Contract:
        """
        Create a contract from an existing `AlloyProvider`, sharing its
        connection pool across multiple contract instances.

        This is more efficient than `new` when creating many contracts
        against the same RPC endpoint, since it avoids creating a new
        HTTP connection pool for each contract.

        Args:
            address: Contract address (hex string)
            provider: An existing `AlloyProvider` instance
        """

def decode_return_data(data: bytes, output_types: list) -> list[str]:
    """
    Decode return data.

    Args:
        data: Return data as bytes
        `output_types`: List of output type strings like `["uint256", "address"]`

    Returns:
        List of decoded values as strings
    """

def encode_function_call(function_signature: str, args: list) -> bytes:
    """
    Encode function arguments.

    Args:
        `function_signature`: Function signature like "transfer(address,uint256)"
        args: List of arguments as strings

    Returns:
        Encoded calldata as bytes
    """

def get_function_selector(function_signature: str) -> str:
    """
    Parse a function signature and return its selector.

    Args:
        `function_signature`: Function signature like "transfer(address,uint256)"

    Returns:
        4-byte function selector as hex string
    """

__all__ = [
    "AsyncContract",
    "Contract",
    "decode_return_data",
    "encode_function_call",
    "get_function_selector",
]
