# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the Curve `get_dy` calculator seam on `degenbot._ffi.curve_dy`.

# Errors

Returns `PyErr` if any symbol fails to register.
The `degenbot._ffi.curve_dy` Python submodule (declarative
`#[pymodule]`), carrying the `get_dy` calculator seam. The parent module
registers the submodule itself; the `sys.modules` entry lives in the
parent's shared helper.
"""

from typing import Any, final

@final
class DyCalculationInputs:
    """
    A mutable builder for the pure [`CoreInputs`] snapshot the calculator reads.

    The Python companion fills each field via setters (named after the
    `DyCalculationInputs` dataclass), then passes it to `calculate_dy` /
    `calculate_dy_underlying`.
    """
    def __new__(cls, /) -> DyCalculationInputs:
        """
        Create an empty snapshot; the companion sets every field it needs.
        """
    a_precision: Any
    address: str
    amp: Any
    balances: Any
    block_number: int
    block_timestamp: int
    d: Any | None
    d_variant: int
    effective_balances: Any | None
    fee: Any
    fee_denominator: Any
    fee_gamma: Any
    gamma: Any | None
    metapool: bool
    metapool_rate_style: int
    metapool_underlying_style: int
    mid_fee: Any
    n_coins: int
    offpeg_fee_multiplier: Any
    out_fee: Any
    precision: Any
    precision_multipliers: Any
    price_scale: Any | None
    rate_multipliers: Any
    resolved_rates: Any
    scaled_redemption_price: Any | None
    swap_style: int
    virtual_price: Any | None
    xp: Any
    y_variant: int

def calculate_dy(i: int, j: int, dx: Any, inputs: DyCalculationInputs) -> Any:
    """
    `calculate_dy(i, j, dx, inputs)` — pure `get_dy` across all swap styles +
    metapool fast-path.

    # Errors

    Returns `ValueError` on an invariant failure / bad index / unknown style.
    """

def calculate_dy_underlying(i: int, j: int, dx: Any, inputs: DyCalculationInputs, base: Any) -> Any:
    """
    `calculate_dy_underlying(i, j, dx, inputs, base)` — metapool swap into/out
    of an underlying base-pool coin. `base` is a Python object exposing the
    `BasePoolPort` surface (`tokens`, `fee`, `calc_token_amount`, `get_dy`,
    `calc_withdraw_one_coin`).

    # Errors

    Returns `ValueError` on an invariant failure / base-pool delegation failure.
    """

__all__ = [
    "DyCalculationInputs",
    "calculate_dy",
    "calculate_dy_underlying",
]
