# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
Register all Curve-math functions on a real Python submodule.

Creates `degenbot._ffi.curve_math` (a `PyModule`, not a flat
root-level prefix) and registers the 5 `StableSwap` solver functions on it
with un-prefixed names — `stableswap_get_d`, not `curve_stableswap_get_d`.
The `curve_` prefix was an artifact of the flat root registration; on the
submodule it is redundant.

The companion `src/degenbot/curve/math.py` re-exports these as the stable
import path (`from degenbot.curve.math import stableswap_get_y`),
decoupling Python consumers from the `degenbot._ffi` internal module.

# Errors

Returns `PyErr` if any function fails to register.
The `degenbot._ffi.curve_math` Python submodule (declarative
`#[pymodule]`), carrying the `StableSwap` math pyfunctions. The parent
module registers the submodule itself; the `sys.modules` entry (needed
for the dotted-path import — the extension module is a single file, not
a package) lives in the parent's shared helper.
"""

from typing import Any

def derive_rate_and_precision_multipliers(
    token_decimals: Any, precision_multipliers: Any | None = None, precision_decimals: int = 18
) -> tuple[list, list]:
    """
    `derive_rate_and_precision_multipliers` — Rust-owned Curve
    `rate_multipliers` / `precision_multipliers` derivation (ADR-005
    slice 11c follow-up).

    The single Rust source of truth for the scaling a Curve pool's `xp`
    (rate-adjusted balances) and `get_dy` consume. `token_decimals` are the
    per-coin ERC20 `decimals()`. When `precision_multipliers` is supplied (the
    lending-token override path) it is returned verbatim as the precision
    multipliers and `rate = pm * 10**precision_decimals`; otherwise both derive
    from `token_decimals`. Replaces the deleted Python
    `curve_stableswap_liquidity_pool._compute_rate_and_precision_multipliers`.

    # Errors

    Returns `ValueError` if `precision_multipliers` is not a `list[int]`.
    """

def stableswap_get_d(xp: Any, amp: Any, n_coins: Any, a_precision: Any, d_variant: int) -> Any:
    """
    `stableswap_get_d` — compute the `StableSwap` invariant D from XP + amp.

    # Errors

    Returns `OverflowError` on uint256 overflow; `ValueError` ("Not converged") after 255 iterations.
    """

def stableswap_get_y(
    i: int,
    j: int,
    x: Any,
    xp: Any,
    amp: Any,
    n_coins: Any,
    a_precision: Any,
    y_variant: int,
    d_variant: int,
) -> Any:
    """
    `stableswap_get_y` — compute x[j] given x[i] = x (the swap-solve entry).

    # Errors

    Returns `ValueError` ("Index out of bounds") if `i == j` or out of range; "Not converged" after 255 iterations; `OverflowError` on overflow.
    """

def stableswap_get_y_d(
    amp: Any, i: int, xp: Any, d: Any, n_coins: Any, a_precision: Any, yd_variant: int
) -> Any:
    """
    `stableswap_get_y_d` — compute x[i] given the invariant D.

    # Errors

    Returns `ValueError` ("Index out of bounds") if `i >= n_coins`; "Not converged" after 255 iterations; `OverflowError` on overflow.
    """

def stableswap_newton_y(
    ann: Any, gamma: Any, xp: Any, d: Any, token_index: int, n_coins: Any, a_multiplier: Any
) -> Any:
    """
    `stableswap_newton_y` — the crypto-variant Newton solve (A/gamma/D/frac bounds).

    # Errors

    Returns `ValueError` ("Unsafe value") on an A/gamma/D/frac safety-assertion failure; "Not converged" after 255 iterations; `OverflowError` on overflow.
    """

def stableswap_reduction_coefficient(x: Any, fee_gamma: Any, n_coins: Any) -> Any:
    """
    `stableswap_reduction_coefficient` — the dynamic-fee reduction multiplier.

    # Errors

    Returns `OverflowError` on uint256 overflow.
    """

__all__ = [
    "derive_rate_and_precision_multipliers",
    "stableswap_get_d",
    "stableswap_get_y",
    "stableswap_get_y_d",
    "stableswap_newton_y",
    "stableswap_reduction_coefficient",
]
