# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.db` Python submodule (declarative `#[pymodule]`),
registering all ~45 `db_*` pyfunctions + ~11 pyclasses. The `db_` prefix
is retained on the submodule names (unlike the math submodules which
dropped their prefix) because (a) the blast radius is much larger (5 Rust
files, ~45 fns) and (b) `db_` functions as a functional namespace marker
is clearer than bare `backup_database` on a `db` submodule.

The companion `src/degenbot/database/_ffi.py` re-exports these as the
stable import path, decoupling Python consumers from `degenbot._ffi`.
The parent module registers the submodule itself and its `sys.modules`
entry.
"""

from collections.abc import Sequence
from typing import Any, final

@final
class CollateralPositionData:
    """
    Collateral position with calculated values (Rust-backed).
    """
    @property
    def actual_balance(self, /) -> Any: ...
    @property
    def asset_address(self, /) -> str: ...
    @property
    def asset_symbol(self, /) -> str | None: ...
    @property
    def emode_category_id(self, /) -> int | None: ...
    @property
    def in_emode(self, /) -> bool: ...
    @property
    def is_enabled_as_collateral(self, /) -> bool: ...
    @property
    def liquidation_threshold(self, /) -> int: ...
    @property
    def ltv(self, /) -> int: ...
    @property
    def price(self, /) -> Any:
        """
        The oracle price (`None` when unavailable — the Rust core treats
        `None` as price = 1).
        """
    @property
    def scaled_balance(self, /) -> Any: ...

@final
class DatabasePositionQuery:
    """
    A read-only Aave V3 position-query handle over a degenbot `SQLite` DB file.

    Opens its own connection (WAL, `query_only=on`) from `database_path`; the
    Python `DatabasePositionQuery` shell constructs one per query and delegates
    every read to it.
    """
    def __new__(cls, /, database_path: str) -> DatabasePositionQuery:
        """
        Open a `query_only` read handle over `database_path`.

        Raises:
            `ValueError`: On a connection / PRAGMA / schema-gate failure.
        """
    def get_asset_addresses(self, /, market_id: int) -> list[str]:
        """
        `get_asset_addresses(market_id: int) -> list[str]` — distinct
        underlying-token addresses (the Python shell wraps into a `set`).
        """
    def get_collateral_config_map(self, /, user_id: int) -> dict:
        """
        `get_collateral_config_map(user_id: int) -> dict[int, bool]` — the
        `asset_id` to `enabled` map.
        """
    def get_collateral_positions(self, /, user_id: int) -> list:
        """
        `get_collateral_positions(user_id: int) -> list[dict]` — keys:
        `asset_id`, `balance`, `underlying_address`, `underlying_symbol`,
        `liquidity_index`, `e_mode_category_id`, `asset_lt`, `asset_ltv`,
        `emode_lt`, `emode_ltv`.
        """
    def get_debt_positions(self, /, user_id: int) -> list:
        """
        `get_debt_positions(user_id: int) -> list[dict]` — keys: `asset_id`,
        `balance`, `underlying_address`, `underlying_symbol`, `borrow_index`,
        `e_mode_category_id`.
        """
    def get_oracle_address(self, /, market_id: int) -> str | None:
        """
        `get_oracle_address(market_id: int) -> str | None` — the
        `PRICE_ORACLE` contract address.
        """
    def get_users_with_debt(self, /, market_id: int, limit: int | None) -> list:
        """
        `get_users_with_debt(market_id: int, limit: int | None = None) ->
        list[dict]` — one dict per user (keys: `id`, `address`, `market_id`,
        `e_mode`, `is_isolation_mode`, `isolation_mode_debt`,
        `isolation_debt_ceiling`).
        """

@final
class DatabaseSnapshot:
    """
    `degenbot._ffi.db.PyDatabaseSnapshot` — a read-only V3/V4 snapshot handle over a
    degenbot `SQLite` DB file. Opens its own connection (WAL, `query_only=on`)
    from `database_path`; the Python `DatabaseSnapshot` shell constructs one
    per chain + delegates every read to it.
    """
    def __new__(cls, /, chain_id: int, database_path: str) -> DatabaseSnapshot:
        """
        `PyDatabaseSnapshot(chain_id, database_path)`.

        Opens the DB read-only (matching the Python `DatabaseSnapshot` which
        operates over a session). Raises `ValueError` if the DB cannot be
        opened or has an unrecognized schema.
        """
    def get_all_liquidity_maps_v3(self, /) -> dict:
        """
        V3 `get_all_liquidity_maps()` → `{pool_address: {tick: (gross, net)}}`.
        """
    def get_all_liquidity_maps_v4(self, /) -> dict:
        """
        V4 `get_all_liquidity_maps()` →
        `{(pool_manager, pool_hash): {tick: (gross, net)}}`.
        """
    def get_liquidity_map_v3(self, /, pool_address: str) -> dict | None:
        """
        V3 `get_liquidity_map(pool_address)` → `LiquidityMap`-shaped dict or
        `None`. Returns `{"tick_bitmap": {word: {"bitmap": int}},
        "tick_data": {tick: {"liquidity_gross": int, "liquidity_net": int}}}`.
        """
    def get_liquidity_map_v4(self, /, pool_manager: str, pool_id: Any) -> dict | None:
        """
        V4 `get_liquidity_map(pool_manager, pool_id)` → `LiquidityMap`-shaped
        dict or `None`. `pool_id` may be `bytes` or a 0x-hex `str` (the pool
        hash).
        """
    def get_newest_block_v3(self, /) -> int | None:
        """
        V3 `get_newest_block()` → newest V3 exchange `last_update_block` or
        `None` (any NULL → `None`, mirroring the Python oracle).
        """
    def get_newest_block_v4(self, /) -> int | None:
        """
        V4 `get_newest_block()` → newest V4 exchange `last_update_block` or
        `None`.
        """
    def get_pools_v3(self, /) -> set:
        """
        V3 `get_pools()` → set of V3 pool addresses.
        """
    def get_pools_v4(self, /) -> set:
        """
        V4 `get_pools()` → set of V4 `pool_hash` hex strings.
        """

@final
class DebtPositionData:
    """
    Debt position with calculated values (Rust-backed).
    """
    @property
    def actual_balance(self, /) -> Any: ...
    @property
    def asset_address(self, /) -> str: ...
    @property
    def asset_symbol(self, /) -> str | None: ...
    @property
    def emode_category_id(self, /) -> int | None: ...
    @property
    def in_emode(self, /) -> bool: ...
    @property
    def price(self, /) -> Any: ...
    @property
    def scaled_balance(self, /) -> Any: ...
    @property
    def stable_debt(self, /) -> bool: ...

@final
class ExchangeRow:
    """
    A typed `exchanges` row (`exchange` relationship hydration).
    """
    @property
    def active(self, /) -> bool: ...
    @property
    def chain_id(self, /) -> int: ...
    @property
    def deployer(self, /) -> str | None: ...
    @property
    def factory(self, /) -> str: ...
    @property
    def id(self, /) -> int: ...
    @property
    def last_update_block(self, /) -> int | None: ...
    @property
    def name(self, /) -> str: ...

@final
class LiquidityPoolRow:
    """
    A typed `pools` table row.

    Mirrors the `SQLAlchemy` `LiquidityPoolTable` scalar + FK-id columns the
    builders hydrate relationships from: `exchange_id` / `token0_id` /
    `token1_id` feed the per-FK fetch methods; `kind` selects the subclass row.
    """
    @property
    def address(self, /) -> str: ...
    @property
    def chain(self, /) -> int: ...
    @property
    def exchange_id(self, /) -> int: ...
    @property
    def id(self, /) -> int: ...
    @property
    def kind(self, /) -> str: ...
    @property
    def token0_id(self, /) -> int: ...
    @property
    def token1_id(self, /) -> int: ...

@final
class LiquidityUpdateEvent:
    """
    One decoded liquidity event the apply loop consumes ).

    Mirrors [`degenbot_db::LiquidityUpdateEvent`]: the
    `(block_number, log_index, tick_lower, tick_upper, liquidity_delta)`
    tuple. The Python `cli/pool.py` apply shells decode the raw `LogReceipt`
    (topics/data → tick bounds + signed delta, with V3 Burn negation) +
    build these records; the Rust core applies them in order.

    `liquidity_delta` is the SIGNED delta — the caller produces it (Burn
    negated for V3; V4 Modify decoded signed). The block/log-index ordering
    invariants (`block >= last; same-block log_index > last`) are enforced in
    the Rust apply loop (panics on violation, matching the Python `assert`s).
    """
    def __new__(
        cls,
        /,
        block_number: int,
        log_index: int,
        tick_lower: int,
        tick_upper: int,
        liquidity_delta: int,
    ) -> LiquidityUpdateEvent:
        """
        Build a liquidity-update event record.

        `liquidity_delta` must fit in i128 (the V3/V4 contract `int128` range);
        raises `OverflowError` otherwise.
        """

@final
class PoolManagerRow:
    """
    A `pool_managers` row (V4). The V4 builder resolves its pool manager by
    `(address, chain)` to obtain the `id` (for the V4 pool join) + the
    `state_view` contract address.
    """
    @property
    def address(self, /) -> str: ...
    @property
    def chain(self, /) -> int: ...
    @property
    def exchange_id(self, /) -> int: ...
    @property
    def id(self, /) -> int: ...
    @property
    def kind(self, /) -> str: ...
    @property
    def state_view(self, /) -> str | None: ...

@final
class UserPositionSummary:
    """
    A user's Aave V3 position summary (health factor, LTV, position lists).

    Rust-backed mirror of the Python `UserPositionSummary` dataclass. The
    Step C cutover swaps the Python dataclass for this `#[pyclass]` — the CLI
    + the parity test read the same attribute names.
    """
    @property
    def collateral_positions(self, /) -> list:
        """
        The collateral positions (as `PyCollateralPositionData` wrappers).

        Returns a fresh `list` each call (the inner field is a `Vec`, not a
        Python object; wrapping each element on demand).
        """
    @property
    def debt_positions(self, /) -> list:
        """
        The debt positions (as `PyDebtPositionData` wrappers).
        """
    @property
    def emode_category_id(self, /) -> int | None:
        """
        The eMode category id (`None` when the user is not in eMode).
        """
    @property
    def has_debt(self, /) -> bool:
        """
        `True` if the user has any debt positions.
        """
    @property
    def health_factor(self, /) -> float | None:
        """
        The health factor (`None` when the user has no debt).
        """
    @property
    def is_at_risk(self, /) -> bool:
        """
        `True` if the position is near liquidation (HF < at-risk threshold).
        """
    @property
    def is_isolation_mode(self, /) -> bool:
        """
        Whether the user is in isolation mode.
        """
    @property
    def is_liquidatable(self, /) -> bool:
        """
        `True` if the position can be liquidated (HF < 1.0).
        """
    @property
    def market_id(self, /) -> int:
        """
        The market id.
        """
    @property
    def max_ltv_ratio(self, /) -> float | None:
        """
        The max-LTV ratio (`None` when no debt or no collateral capacity).
        """
    @property
    def total_collateral_value(self, /) -> Any:
        """
        Total collateral value (price-adjusted, oracle base currency). A
        Python `int` (the `U256` sum) — matches the Python runtime where the
        `float`-typed field holds an `int`.
        """
    @property
    def total_debt_value(self, /) -> Any:
        """
        Total debt value (price-adjusted). A Python `int`.
        """
    @property
    def user_address(self, /) -> str:
        """
        The user's checksummed address.
        """

@final
class V2PoolRowInput:
    """
    One V2 pool-row to upsert. Mirrors [`degenbot_db::V2PoolRowInput`]:
    the `(address, token0_address, token1_address, fee_token0, fee_token1,
    stable)` tuple. The Python `update_v2_pools` shell decodes the
    `PoolCreated` event + builds these records; the `Rust` core get-or-create's
    the tokens + inserts the polymorphic base `pools` row + the subclass detail
    row. `stable` is `None` for all V2 families except `Aerodrome` (the sole
    V2 subclass with a `stable` column).

    The address fields are stored parsed ([`Address`], mirroring the core
    struct); the constructor takes the Python-side hex strings and validates
    them via [`parse_address_field`], so [`From`] conversion to the core row
    is infallible field copying.
    """
    def __new__(
        cls,
        /,
        address: str,
        token0_address: str,
        token1_address: str,
        fee_token0: int,
        fee_token1: int,
        stable: bool | None = None,
    ) -> V2PoolRowInput: ...

@final
class V3PoolRowInput:
    """
    One V3 pool-row to upsert. Mirrors [`degenbot_db::V3PoolRowInput`] (the
    address fields stored parsed, like [`PyV2PoolRowInput`]).
    """
    def __new__(
        cls, /, address: str, token0_address: str, token1_address: str, fee: int, tick_spacing: int
    ) -> V3PoolRowInput: ...

@final
class V4PoolRowInput:
    """
    One V4 pool-row to upsert. Mirrors [`degenbot_db::V4PoolRowInput`] (the
    address fields stored parsed, like [`PyV2PoolRowInput`]; `pool_hash` stays
    the core's `0x`-prefixed hex `String` — the `uniswap_v4_pools.pool_hash`
    column is a hex `VARCHAR`, not a blob). The `pool_id` / `manager_id` is
    resolved inside the `Rust` core from the passed `pool_manager_address`
    (one `SELECT` per batch).
    """
    def __new__(
        cls,
        /,
        pool_hash: str,
        hooks: str,
        currency0_address: str,
        currency1_address: str,
        fee: int,
        tick_spacing: int,
    ) -> V4PoolRowInput: ...

def analyze_aave_user_position(
    user: Any,
    collateral_positions: list,
    debt_positions: list,
    collateral_config_map: dict,
    price_map: dict | None = None,
) -> UserPositionSummary:
    """
    `degenbot._ffi.db.analyze_aave_user_position(user, collateral_positions,
    debt_positions, collateral_config_map, price_map=None) ->
    PyUserPositionSummary`

    Analyze a single user's Aave V3 position for liquidation risk. Pure math
    (no I/O) — delegates to [`degenbot_aave::analysis::analyze_user_position`].

    Args:
        user: A `dict` with keys `id`, `address`, `market_id`, `e_mode`,
            `is_isolation_mode`, `isolation_mode_debt`,
            `isolation_debt_ceiling` (the shape
            `PyDatabasePositionQuery.get_users_with_debt` returns).
        `collateral_positions`: A `list[dict]` (the
            `get_collateral_positions` row shape).
        `debt_positions`: A `list[dict]` (the `get_debt_positions` row shape).
        `collateral_config_map`: A `dict[int, bool]` (`asset_id` -> enabled).
        `price_map`: An optional `dict[str, int]` (address -> oracle price in 8
            decimals). When `None`, prices are treated as 1.

    Returns:
        A `PyUserPositionSummary` with attribute access matching the Python
        `UserPositionSummary` dataclass (`health_factor`, `max_ltv_ratio`,
        `collateral_positions`, …).

    Raises:
        `ValueError`: On a missing dict key, a malformed value, or a scaled-
            balance computation overflow.
    """

def db_apply_v3_liquidity_updates(
    database_path: str, chain_id: int, pool_address: str, events: Sequence[LiquidityUpdateEvent]
) -> bool:
    """
    `degenbot._ffi.db.db_apply_v3_liquidity_updates(database_path, chain_id, pool_address, events) -> bool`

    Apply a sequence of [`PyLiquidityUpdateEvent`]s to the V3 pool identified by
    `(chain_id, pool_address)`: reconstitute the `LiquidityMap` from DB rows →
    apply each event (`apply_liquidity_mapping_update`) → upsert live
    positions/init-maps, delete stale, stamp `liquidity_update_block`/
    `log_index` with the last event. Returns `False` if the pool row isn't found
    (mirrors the Python `if pool_in_db is None: return`); `True` after a
    successful apply. The block/log-index ordering invariant is enforced
    (panics on violation, matching the Python `assert`s).
    """

def db_apply_v4_liquidity_updates(
    database_path: str,
    pool_hash_hex: str,
    pool_manager_chain: int,
    events: Sequence[LiquidityUpdateEvent],
) -> bool:
    """
    `degenbot._ffi.db.db_apply_v4_liquidity_updates(database_path, pool_hash_hex, pool_manager_chain, events) -> bool`

    Apply a sequence of [`PyLiquidityUpdateEvent`]s to the V4 pool identified by
    `(pool_hash, pool_manager_chain)`. Same semantics as
    [`db_apply_v3_liquidity_updates`] (reconstitute → apply → persist → stamp);
    differs only in the row lookups (`uniswap_v4_pools` × `managed_pools` ×
    `pool_managers`) + the tables written (`managed_pool_*`).
    """

def db_backup_database(src: str, dst: str) -> None:
    """
    `degenbot._ffi.db.db_backup_database(src: str, dst: str) -> None`

    Online backup with `PRAGMA integrity_check` assertions on both source and
    destination. Raises `ValueError` on failure.
    """

def db_compact_database(path: str) -> None:
    """
    `degenbot._ffi.db.db_compact_database(path: str) -> None`

    `VACUUM`. A no-op for `:memory:`. Raises `ValueError` on failure.
    """

def db_fetch_exchange(database_path: str, exchange_id: int) -> ExchangeRow | None:
    """
    `degenbot._ffi.db.db_fetch_exchange(database_path, exchange_id) -> ExchangeRow | None`

    Module-level exchange-row read by FK id. The `cli/pool.py::pool_update`
    discovery loop reads `last_update_block` ground-truth here (a fresh
    `DegenbotDb::open` per call → a fresh WAL snapshot) rather than trusting
    the long-lived `SQLAlchemy` session's stale ORM cache: the stamp is written
    by the Rust `db_set_exchange_last_update_block` seam on its own
    connection, which the `SQLAlchemy` read snapshot cannot see. Mirrors
    [`db_fetch_pool_row`] (same `database_path` + fresh-open pattern).
    """

def db_fetch_exchange_by_name(database_path: str, chain_id: int, name: str) -> ExchangeRow | None:
    """
    `degenbot._ffi.db.db_fetch_exchange_by_name(database_path, chain_id, name)
    -> ExchangeRow | None`

    The by-name companion to [`db_fetch_exchange`] — the `(chain_id, name)`
    lookup the `cli/exchange.py` `deactivate` commands use to resolve the row
    to flip `active=False` on. Same fresh-open read path (`DegenbotDb::open` →
    a fresh WAL snapshot). Raises ``ValueError`` on a DB failure.
    """

def db_fetch_graph_edition(database_path: str, chain_id: int) -> tuple[int, int, int, int]:
    """
    Return `(v2v3_count, v2v3_max_id, v4_count, v4_max_id)` for a chain.

    The managed-pool branch is scoped through its pool manager's chain. The
    caller owns the fail-open policy; this seam reports DB/query failures as
    `ValueError` after releasing the GIL.
    """

def db_fetch_pool_row(database_path: str, chain_id: int, address: str) -> LiquidityPoolRow | None:
    """

    Module-level pool-row read by `(chain_id, address)` () — the V3
    `apply_v3_liquidity_updates` shell uses this to fetch the pool's
    `exchange_id` for the `exchanges_in_scope` precondition before delegating
    the math+persist to [`super::liquidity_updater::db_apply_v3_liquidity_updates`].
    Keeps the scope-check orchestration in Python + the apply core in Rust.
    """

def db_heal_database(database_path: str) -> dict:
    """
    `degenbot._ffi.db.db_heal_database(database_path: str) -> dict`

    Out-of-place dump-and-restore "heal" (ADR-011): builds a fresh DB at the
    Rust head schema, copies all user rows from the old DB (preserving PKs +
    FK integrity, in FK-dependency order), stamps `RustOwned` directly (never
    runs Alembic code), then atomically swaps it into place (old DB preserved
    as `*.bak` for full recoverability). Never mutates the old DB in place —
    a read-only open of the old DB feeds the copy, so the old file is left
    byte-identical until the final `rename`.

    Returns a dict:
      `{"old_state": str, "rows_copied": dict[str, int], "bak_path": str,
        "new_state": str, "warnings": list[str]}``
    - `old_state` / `new_state`: `schema_state_label` of the `HealReport` fields.
    - No-op if old is already `rust_owned` (returns `old_state == new_state ==
      "rust_owned"`, empty `rows_copied`, `bak_path == database_path`).
    - Refuses `Unrecognized` (foreign file) + any I/O / copy / verification
      failure via `db_err_to_py` (`ValueError`).

    The GIL is released across the entire read-copy-swap (the
    `py.detach(|| ops::heal_database(&path))` call) so a long copy doesn't
    freeze Python threads.
    """

def db_inspect_schema_state(database_path: str) -> str:
    """
    `degenbot._ffi.db.db_inspect_schema_state(database_path: str) -> str`

    Reports the schema state WITHOUT writing. Never refuses (reports even
    legacy / unrecognized states). Returns one of `"legacy_alembic"`,
    `"fresh_standalone"`, `"rust_owned"`, `"unrecognized"`.
    Raises `ValueError` only on a genuine `SQLite` open/query failure.
    """

def db_resolve_token_ids(database_path: str, chain_id: int, addresses: Sequence[str]) -> dict:
    """
    Resolve chain-scoped ERC-20 addresses to database row ids.

    Addresses are normalized to EIP-55 checksums, duplicate inputs are
    collapsed, and missing rows are omitted from the returned dictionary.
    SQLite open/query work runs with the GIL detached.
    """

def db_schema_version() -> int:
    """
    `degenbot._ffi.db.db_schema_version() -> int`

    The Rust core's schema version ([`degenbot_db::schema::RUST_SCHEMA_VERSION`])
    — the value stamped into `_degenbot_db_schema_version` on create / heal /
    migrate. Exposed so the Python driver (and its parity tests) pin to the
    same constant the core writes instead of hardcoding it.
    """

def db_set_exchange_active(database_path: str, exchange_id: int, active: bool) -> None:
    """
    `degenbot._ffi.db.db_set_exchange_active(database_path, exchange_id, active)
    -> None`

    Flip an `exchanges` row's `active` flag by id — the activate/deactivate
    primitive the `exchange activate` / `exchange deactivate` CLI commands
    delegate to (the Python trajectory's `exchange.active = True/False;
    session.commit()`). Raises `ValueError` (a not-found error surfaced from
    [`degenbot_db::DbError::MissingRow`]) if no row matches `exchange_id`.
    """

def db_set_exchange_last_update_block(
    database_path: str, chain_id: int, exchange_id: int, block: int
) -> None:
    """
    `degenbot._ffi.db.db_set_exchange_last_update_block(database_path, chain_id,
    exchange_id, block) -> None`

    Stamp an `ExchangeTable.last_update_block`. Port of the
    `exchange.last_update_block = working_end_block` trajectory in
    `cli/pool.py::pool_update` (the discovery-writer close-out stamp).
    """

def db_upgrade_database(path: str) -> str:
    """
    `degenbot._ffi.db.db_upgrade_database(path: str) -> str`

    Ensure the DB is at the current Rust schema. Returns `"already_current"` if
    it was already there, `"created_fresh"` if an empty file was brought up, or
    `"healed_legacy"` if a legacy `alembic_version`-marked DB was healed
    out-of-place. Raises `ValueError` for an unrecognized schema.
    """

def db_upsert_exchange(
    database_path: str, chain_id: int, name: str, factory: str, deployer: str | None
) -> ExchangeRow:
    """
    `degenbot._ffi.db.db_upsert_exchange(database_path, chain_id, name, factory,
    deployer) -> ExchangeRow`

    Resolve an `exchanges` row by `(chain_id, name)`, inserting a new
    `active=False`, `last_update_block=None` row if none exists (the substrate
    the `exchange activate/deactivate` CLI delegates to for the get-or-create
    step). If a row already exists it is returned UNCHANGED — `active` is NOT
    touched here (flipping active is a separate concern, see
    [`db_set_exchange_active`]). `exchanges` has no unique index on
    `(chain_id, name)` so this uses the explicit SELECT-then-INSERT dedup the
    Python `cli/exchange.py` trajectory uses (no Alembic migration forced). The
    `factory` / `deployer` are stored EIP-55-checksummed. Raises `ValueError`
    on a parse or DB failure.
    """

def db_upsert_pool_manager(
    database_path: str,
    address: str,
    chain: int,
    kind: str,
    state_view: str | None,
    exchange_id: int,
) -> PoolManagerRow:
    """
    `degenbot._ffi.db.db_upsert_pool_manager(database_path, address, chain, kind,
    state_view, exchange_id) -> PoolManagerRow`

    Upsert a `pool_managers` row by `(address, chain)` (the get-or-create
    substrate for the V4 manager row the `exchange activate uniswap_v4` CLI
    creates). `pool_managers` HAS the unique index on `(address, chain)` so this
    uses `INSERT … ON CONFLICT … RETURNING` — idempotent: re-calling with a
    changed `state_view` updates the row in place (same id), re-calling
    identical leaves it unchanged. `address` / `state_view` are stored
    EIP-55-checksummed. Raises `ValueError` on a parse or DB failure.
    """

def db_upsert_v2_pools(
    database_path: str,
    chain_id: int,
    kind: str,
    exchange_id: int,
    fee_denominator: int,
    rows: Sequence[V2PoolRowInput],
) -> None:
    """
    `degenbot._ffi.db.db_upsert_v2_pools(database_path, chain_id, kind, exchange_id,
    fee_denominator, rows) -> None`

    Insert a batch of V2 pool rows. The `Rust` core get-or-create's the two
    `erc20_tokens` per row + inserts the polymorphic base `pools` row (kind) +
    the subclass detail row (`fee_token0`/`fee_token1`/`fee_denominator`, +
    `stable` for `aerodrome_v2`). Raises `ValueError` if `kind` is not a known
    V2 family discriminator (mirrors the Python
    `config.database_type` dispatch). The address uniqueness constraint raises
    `ValueError` (`SQLITE_CONSTRAINT`) on a duplicate `(address, chain)`,
    matching the Python `session.add` `IntegrityError` trajectory.
    """

def db_upsert_v3_pools(
    database_path: str,
    chain_id: int,
    kind: str,
    exchange_id: int,
    fee_denominator: int,
    rows: Sequence[V3PoolRowInput],
) -> None:
    """
    `degenbot._ffi.db.db_upsert_v3_pools(database_path, chain_id, kind, exchange_id,
    fee_denominator, rows) -> None`

    Insert a batch of V3 pool rows. Same shape as [`db_upsert_v2_pools`];
    subclass detail row carries `tick_spacing` + the fee columns
    (`liquidity_update_block`/`log_index` left `NULL` until the liquidity
    updater stamps them). Raises `ValueError` if `kind` is not a V3 family.
    """

def db_upsert_v4_pools(
    database_path: str,
    chain_id: int,
    pool_manager_address: str,
    fee_denominator: int,
    rows: Sequence[V4PoolRowInput],
) -> None:
    """
    `degenbot._ffi.db.db_upsert_v4_pools(database_path, chain_id, pool_manager_address,
    fee_denominator, rows) -> None`

    Insert a batch of V4 pool rows. The `Rust` core resolves the
    `PoolManagerTable` id from `(chain_id, pool_manager_address)` (one
    `SELECT`), then per row: get-or-create the two currency tokens + insert
    the `managed_pools` polymorphic base (`kind='uniswap_v4', manager_id`) +
    the `uniswap_v4_pools` detail row. Raises `ValueError` if no
    `PoolManager` row matches (mirrors the Python
    `assert manager_in_db is not None`).
    """

__all__ = [
    "CollateralPositionData",
    "DatabasePositionQuery",
    "DatabaseSnapshot",
    "DebtPositionData",
    "ExchangeRow",
    "LiquidityPoolRow",
    "LiquidityUpdateEvent",
    "PoolManagerRow",
    "UserPositionSummary",
    "V2PoolRowInput",
    "V3PoolRowInput",
    "V4PoolRowInput",
    "analyze_aave_user_position",
    "db_apply_v3_liquidity_updates",
    "db_apply_v4_liquidity_updates",
    "db_backup_database",
    "db_compact_database",
    "db_fetch_exchange",
    "db_fetch_exchange_by_name",
    "db_fetch_graph_edition",
    "db_fetch_pool_row",
    "db_heal_database",
    "db_inspect_schema_state",
    "db_resolve_token_ids",
    "db_schema_version",
    "db_set_exchange_active",
    "db_set_exchange_last_update_block",
    "db_upgrade_database",
    "db_upsert_exchange",
    "db_upsert_pool_manager",
    "db_upsert_v2_pools",
    "db_upsert_v3_pools",
    "db_upsert_v4_pools",
]
