# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the `init_hash_for` / `deployer_for` free functions on the
`degenbot._ffi.deployments` submodule.
The `degenbot._ffi.deployments` Python submodule (declarative
`#[pymodule]`), carrying the deployment-identity lookup over the
embedded deployments.json (Fork A, 7FA5EZ). The parent module registers
the submodule itself and its `sys.modules` entry.
"""

def deployer_for(chain_id: int, factory: str) -> str | None:
    """
    Resolve the *effective* CREATE2 deployer for a ``(chain_id, factory)``
    pair from the embedded canonical `deployments.json`.

    The effective deployer is the row's `deployer` when set, else the
    `factory` itself (the `null → factory` convention). Returns the
    EIP-55 checksummed address, or `None` for an unregistered
    ``(chain, factory)``. This is the load-bearing helper for the
    separate-deployer case (`PancakeSwap` V3 uses a deployer distinct from
    its factory).

    # Errors
    Returns `ValueError` if `factory` is not a valid hex address.
    """

def init_hash_for(chain_id: int, factory: str) -> str | None:
    """
    Resolve the CREATE2 init code hash for a ``(chain_id, factory)`` pair from
    the embedded canonical `deployments.json`.

    Returns the hash as a lowercase `0x`-prefixed hex string, or `None` when
    the ``(chain, factory)`` is not a shipped deployment OR the row carries
    no CREATE2 address generation (Aerodrome, Balancer). Address lookup is
    case-insensitive.

    # Errors
    Returns `ValueError` if `factory` is not a valid hex address.
    """

def resolve_deployer(chain_id: int, factory: str) -> str:
    """
    Resolve the effective CREATE2 deployer for a ``(chain_id, factory)`` pair,
    with the `None -> factory` convention applied. Returns the factory itself
    when the ``(chain, factory)`` is not in the shipped JSON (Fork A, P62DKO).
    """

def resolve_v2_init_hash(chain_id: int, factory: str) -> str:
    """
    Resolve the CREATE2 init code hash for a V2 ``(chain_id, factory)`` pair,
    with a documented fallback. Returns the JSON row's `init_hash` when shipped
    with a CREATE2 init hash; otherwise the Uniswap V2 mainnet fallback (the
    retired Python `ClassVar`'s default for non-JSON V2 pools) (Fork A, NSAZ4X).
    """

def resolve_v3_init_hash(chain_id: int, factory: str) -> str:
    """
    Resolve the CREATE2 init code hash for a V3 ``(chain_id, factory)`` pair,
    with a documented fallback. Returns the JSON row's `init_hash` when shipped
    with a CREATE2 init hash; otherwise the Uniswap V3 mainnet fallback (the
    retired Python `ClassVar`'s default for non-JSON V3 pools) (Fork A, P62DKO).
    """

__all__ = [
    "deployer_for",
    "init_hash_for",
    "resolve_deployer",
    "resolve_v2_init_hash",
    "resolve_v3_init_hash",
]
