# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the `dex_identity` free function + the `PyDexIdentity` class on
the `degenbot._ffi.dex_identity` submodule.
The `degenbot._ffi.dex_identity` Python submodule (declarative
`#[pymodule]`), carrying the DEX-identity preset lookup (ADR-005 slice
6). The parent module registers the submodule itself and its
`sys.modules` entry.
"""

from collections.abc import Sequence
from typing import final

@final
class DexIdentity:
    """
    Frozen Python view over a `DexIdentity` preset (ADR-005 slice 6).

    Read-only — all fields are `#[getter]`. Carries the preset's deployment
    identity (factory, deployer, init hash, default fees, reserve ABI shape,
    variant string) so a Python builder can resolve a DEX's deployment data
    without a Python-side preset table. The values mirror the `DexIdentity`
    core struct; only the representation differs (hex strings for addresses +
    init hash, since `pyo3` doesn't expose `alloy::Address`/`B256` directly
    without a converter).
    """
    def __new__(
        cls,
        /,
        factory: str,
        init_hash: str,
        fee_token0: tuple[int, int],
        fee_token1: tuple[int, int],
        variant: str,
        reserves_abi: Sequence[str] | None = None,
    ) -> DexIdentity:
        """
        Construct a custom `DexIdentity` view from explicit Python args.

        Mirrors Polars' builder pattern for codec options — presets are the
        canonical source (resolve via `dex_identity`), but custom identities
        are constructable for tests / ad-hoc deployments.

        # Examples

        ```python
        from degenbot._ffi.dex_identity import PyDexIdentity

        ident = PyDexIdentity(
            factory="0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f",
            init_hash="0x96e8ac4277198ff8b6f785478aa9a39f403cb768dd02cbee326c3e7da348845f",
            fee_token0=(997, 1000),
            fee_token1=(997, 1000),
            variant="uniswap-v2",
        )
        ```
        """
    def __repr__(self, /) -> str: ...
    @property
    def deployer(self, /) -> str:
        """
        CREATE2 deployer address (EIP-55 checksummed hex).
        """
    @property
    def factory(self, /) -> str:
        """
        Factory contract address (EIP-55 checksummed hex).
        """
    @property
    def fee_token0(self, /) -> tuple[int, int]:
        """
        `token0→token1` fee parameters: `(gamma_numer, fee_denom)` — the
        retained post-fee fraction (e.g. `(997, 1000)` for a 0.3% fee). NOT the
        fee numerator. Slice-5 convention; matches `register_v2_pool`'s
        `gamma_numerN` parameter meaning.
        """
    @property
    def fee_token1(self, /) -> tuple[int, int]:
        """
        `token1→token0` fee parameters: `(gamma_numer, fee_denom)`.
        """
    @property
    def init_hash(self, /) -> str:
        """
        CREATE2 init code hash (lowercase hex with `0x` prefix, 64 hex chars).
        """
    @property
    def reserves_abi(self, /) -> list[str]:
        """
        Solidity struct types for `Sync`-event reserve decoding
        (e.g. `["uint112", "uint112"]` for most V2 DEXes; the 3-tuple for
        `PancakeSwap`).
        """
    @property
    def variant(self, /) -> str:
        """
        The kebab-case variant string (the lookup key).
        """

def dex_identity(variant: str) -> DexIdentity | None:
    """
    Look up a `DexIdentity` preset by its kebab-case variant string
    (e.g. `"uniswap-v2"`, `"camelot-v2-stable"`). Case-insensitive. Returns
    `None` for an unrecognized variant so a stray string doesn't raise
    `PanicException`.

    # Examples

    ```python
    from degenbot._ffi.dex_identity import dex_identity

    ident = dex_identity("uniswap-v2")
    assert ident is not None
    assert ident.factory == "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
    assert dex_identity("nonexistent") is None
    ```
    """

__all__ = [
    "DexIdentity",
    "dex_identity",
]
