# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the diagnostics pyfunctions on the module.

# Errors
Returns `PyErr` if a function fails to register.
The `degenbot._ffi.diagnostics` Python submodule (declarative
`#[pymodule]`), carrying the GIL-probe pyfunctions. The parent module
registers the submodule itself and its `sys.modules` entry.
"""

def failure_action(kind: str, reason: str | None) -> str:
    """
    Python-callable: stamp "forward progress happened" (call after each
    block the pump delivers + dispatches). The stuck-watchdog reads this.

    Cheap: one relaxed atomic store. Safe to call from any thread holding
    the GIL (the example's main loop) — no allocation, no I/O.
    The effective reaction for a failure bucket (ADR-040): the closed
    `failure_policy` matrix resolved against boot-time `[failure_policy]`
    overrides. Returns `observe` | `event` | `quarantine` | `exit`.

    Single source of truth for the Python driver's reaction behavior (the
    Rust core owns the matrix; Python must not duplicate the table).
    """

def mark_progress() -> None: ...
def start_gil_probe(interval_ms: int = 50, threshold_ms: int = 100, stuck_ms: int = 30000) -> None:
    """
    Start the GIL-acquire-latency probe + main-loop stuck-watchdog.

    Idempotent: a second call is a no-op (logs once that it's already
    running). Spawns two detached `std::thread`s (daemon-equivalent — they
    exit when the process exits).

    # Arguments
    * `interval_ms` — sampling period (default 50 ms).
    * `threshold_ms` — log `[gil-probe] GIL held` when an acquire exceeds
      this (default 100 ms).
    * `stuck_ms` — log `[gil-probe] *** MAIN LOOP STUCK` when no
      `mark_progress()` call for this long (default 30 000 ms).

    # Errors
    Returns `PyErr` only if thread spawning fails (extremely rare).
    """

__all__ = [
    "failure_action",
    "mark_progress",
    "start_gil_probe",
]
