# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.eip_1559` Python submodule (declarative `#[pymodule]`),
carrying the EIP-1559 `next_base_fee` seam. The parent module registers
the submodule itself and its `sys.modules` entry.
"""

def next_base_fee(
    parent_base_fee: int,
    parent_gas_used: int,
    parent_gas_limit: int,
    min_base_fee: int | None = None,
    base_fee_max_change_denominator: int = 8,
    elasticity_multiplier: int = 2,
) -> int:
    """
    Compute the EIP-1559 next-block base fee, mirroring the pure-Rust
    `degenbot_core::eip_1559::next_base_fee`.

    Args mirror the Python oracle (`degenbot.calculations.evm_math.next_base_fee`):
    `parent_base_fee`, `parent_gas_used`, `parent_gas_limit`, optional
    `min_base_fee`, `base_fee_max_change_denominator` (default 8) and
    `elasticity_multiplier` (default 2). U256 intermediates avoid u128 overflow.
    """

__all__ = [
    "next_base_fee",
]
