# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the executor seam functions on `m` (feature = "executor").

# Errors

Returns a [`PyErr`] if any `add_function` call fails (e.g. a name
collision); propagated unchanged to the `#[pymodule]` caller.
The `degenbot._ffi.executor` Python submodule (declarative
`#[pymodule]`), carrying the command-stream encoding pyfunctions. The
parent module registers the submodule itself and its `sys.modules` entry.
"""

from typing import Any

def compute_simulation_warmup_slots(
    executor_address: str, weth_address: str, pool_manager_address: str
) -> dict:
    """
    `degenbot._ffi.executor.compute_simulation_warmup_slots(executor_address,
    weth_address, pool_manager_address) -> dict`

    Compute the `eth_simulateV1` `stateDiff` overrides replicating
    `cmd_executor.initialize()`'s three warmed storage slots (WETH9
    `balanceOf(executor)`, `PoolManager` ERC6909 `balanceOf(executor, weth_id)`,
    `PoolManager` ERC6909 `balanceOf(executor, native_id)`). Each is set to 1 wei
    to warm the slot and avoid cold-access gas penalties.
    """

def mapping_slot(base_slot: Any, key: Any) -> Any:
    """
    `degenbot._ffi.executor.mapping_slot(base_slot, key) -> int`

    Compute a Solidity mapping storage slot: `keccak256(pad(key,32) || pad(base,32))`.
    Thin wrapper over [`core_mapping_slot`] (the Rust warmup-slot leaf).
    """

def nested_mapping_slot(base_slot: Any, key1: Any, key2: Any) -> Any:
    """
    `degenbot._ffi.executor.nested_mapping_slot(base_slot, key1, key2) -> int`

    Compute a nested Solidity mapping storage slot:
    `keccak256(pad(key2,32) || keccak256(pad(key1,32) || pad(base,32)))`.
    Thin wrapper over [`core_nested_mapping_slot`].
    """

def pack_config(
    check_mode: int, expected_value: Any, *, bribe_bips: int = 0, bribe_recipient_idx: int = 0
) -> Any:
    """
    `degenbot._ffi.executor.pack_config(check_mode=0, expected_value=0, bribe_bips=0,
    bribe_recipient_idx=0) -> int`

    Pack the `execute(commands, config)` ABI `config` `uint256`. Thin wrapper
    over [`config::pack_config`].
    """

__all__ = [
    "compute_simulation_warmup_slots",
    "mapping_slot",
    "nested_mapping_slot",
    "pack_config",
]
