# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the execution-seam classes/functions on `m` (feature =
`"execution"`) as `degenbot._ffi.execution`.

# Errors

Returns a [`PyErr`] if any `add_class`/`add_function` call fails (e.g. a
name collision); propagated unchanged to the `#[pymodule]` caller.
The `degenbot._ffi.execution` Python submodule (declarative
`#[pymodule]`), carrying the `ExecutionAdapter` seam lift (ADR-025). The
parent module registers the submodule itself and its `sys.modules` entry.
"""

from typing import Any, final

class PayloadComposer:
    """
    `PyPayloadComposer` — wrap an arbitrary Python callable
    (`result: PySolveResult -> bytes`) into the core [`PayloadComposer`] seam.

    Construct with a Python callable:

    ```python
    def my_composer(result):
        return abi_encode_call("(bytes32,uint256)", ["0x…", result.optimal_input])

    composer = PyPayloadComposer(my_composer)
    ```

    Rust drives `compose` (under the GIL it builds the [`SolveResult`] view,
    calls the Python callable, and takes back the payload `bytes`). Because the
    seam provides a blanket `PayloadComposer -> ExecutionAdapter` impl, a
    `PyPayloadComposer` is a full `ExecutionAdapter` (built-in Probe/Assess/Fee
    defaults) that a foreign searcher can adopt directly. Nothing here is wired
    into the canonical `dispatch_profitable_*` fan-out (ADR-025 D3).

    The callable's return must be `bytes`/`bytearray` (the payload to submit to
    the composer's own contract).
    """
    def __new__(cls, /, callback: Any) -> PayloadComposer:
        """
        Construct from a Python callable `result -> bytes`.

        # Errors

        `TypeError` when `callback` is not callable.
        """

@final
class SolveResult:
    """
    `PySolveResult` — the typed solve-result **view** passed to a Python
    compose callable (ADR-025 D4).

    Carries the path id, hop count, the integer fixed-point amounts
    (`optimal_input` / `hop_outputs` / `consumed_inputs` / `net_profit`,
    all u256 integers — never floats), and the per-hop descriptors. Constructed
    by [`PyPayloadComposer`] from the core seam's inputs; a Python callable
    reads it (attribute access) to build calldata for its own contract.
    """
    @property
    def consumed_inputs(self, /) -> Any:
        """
        Per-hop consumed input amounts (`consumed_inputs`, list of uint256
        integers). The CL-clamp swap-in matters: an over-fed CL hop is reduced
        to `input_consumed − 1`.
        """
    @property
    def hop_count(self, /) -> int:
        """
        Number of hops in the path (`hop_count`).
        """
    @property
    def hop_descriptors(self, /) -> Any:
        """
        Per-hop descriptors — a list of dicts, one per hop:
        `{family, pool_address, token0, token1, zfo, v4_pool_id}`.
        """
    @property
    def hop_outputs(self, /) -> Any:
        """
        Per-hop output amounts (`hop_outputs`, list of uint256 integers).
        """
    @property
    def net_profit(self, /) -> Any:
        """
        The net profit (`net_profit`, uint256 integer) — `final_output −
        consumed_inputs[0]`.
        """
    @property
    def optimal_input(self, /) -> Any:
        """
        The flash input amount (`optimal_input`, uint256 integer).
        """
    @property
    def path_id(self, /) -> int:
        """
        The path id (`path_id`).
        """

def abi_encode_call(signature: str, values: Any) -> bytes:
    """
    `abi_encode_call(signature, values) -> bytes`

    A `degenbot.abi`-backed helper so a Python user can ABI-encode a **call**
    against their own contract from inside a compose callable. `signature` is a
    Solidity function signature string (`"transfer(address,uint256)"`);
    `values` is the argument list consumed left-to-right.

    Returns the full calldata: the 4-byte function selector (from the parsed,
    canonical signature) followed by the ABI-encoded arguments. The argument
    encoding delegates to the crate's canonical ABI encoder (via
    `degenbot._ffi.abi.encode`); this wrapper only adds the selector prefix and
    the signature-string spelling — it is not a second ABI implementation.

    # Errors

    `ValueError` when the signature cannot be parsed or the values cannot be
    encoded.
    """

__all__ = [
    "PayloadComposer",
    "SolveResult",
    "abi_encode_call",
]
