# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the fleet seam on the real Python submodule
`degenbot._ffi.fleet`.

# Errors

Returns `PyErr` if the submodule, the typed exception, or a function
fails to register on the module.
The `degenbot._ffi.fleet` Python submodule (declarative `#[pymodule]`),
carrying the posture re-tune operator pyfunctions. The parent module
registers the submodule itself and its `sys.modules` entry.

[`PostureRetuneError`] is a `create_exception!` type (no `_PYO3_DEF`), so
it stays on the submodule's one imperative registration line in `init`.
"""

from _typeshed import Incomplete

def current_posture_policy() -> dict:
    """
    `degenbot._ffi.fleet.current_posture_policy() -> dict`

    The read side of the channel: the effective policy (all six fields) +
    the current posture, with no write.

    # Errors

    Only on dict construction failure (never refuses a read).
    """

def set_posture_policy(patch: dict) -> dict:
    """
    `degenbot._ffi.fleet.set_posture_policy(patch: dict) -> dict`

    Apply the operator's partial patch to the LIVE process posture policy
    and echo the effective policy. See the module docs for the full
    contract.

    # Errors

    [`PostureRetuneError`] on an unknown key, a non-dict patch, an empty
    patch, a wrong-typed value, or an out-of-range threshold (all REJECT —
    the live policy is untouched when any of these fire).
    """

def __getattr__(name: str) -> Incomplete: ...

__all__ = [
    "current_posture_policy",
    "set_posture_policy",
]
