# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the `AnvilFork` pyclass on the `degenbot._ffi.fork` submodule.

# Errors
Returns `PyErr` if `add_class` fails (e.g. name collision).
The `degenbot._ffi.fork` Python submodule (declarative `#[pymodule]`),
carrying the `PyAnvilFork` lifecycle + dev-RPC seam. The parent module
registers the submodule itself and its `sys.modules` entry.
"""

from collections.abc import Sequence
from typing import Any, final

@final
class AnvilFork:
    """
    Rust-owned Anvil fork handle: subprocess + IPC `DynProvider` + dev-RPC
    surface. Construct via `AnvilFork(**kwargs)`; see `__new__` for the
    keyword surface.
    """
    def __new__(
        cls,
        /,
        *,
        fork_url: str | None = None,
        fork_block: int | None = None,
        fork_transaction_hash: str | None = None,
        mining_mode: str = "auto",
        mining_interval: int | None = None,
        storage_caching: bool = True,
        base_fee: int | None = None,
        ipc_path: str | None = None,
        port: int | None = None,
        host: str = "127.0.0.1",
        mnemonic: str = ...,
        chain_id: int | None = None,
        anvil_opts: Sequence[str] | None = None,
    ) -> AnvilFork:
        """
        Spawn the `anvil` subprocess + connect the IPC `DynProvider`.

        Mirrors the legacy Python `AnvilFork.__init__` keyword surface for
        spawn-time config; the legacy `mining_mode` string literal
        (`"auto"` / `"interval"` / `"none"`) maps to the Rust
        [`MiningMode`] enum. `mining_interval` only applies when
        `mining_mode == "interval"`.

        # Errors
        - `ValueError` on invalid `mining_mode` value.
        - `RuntimeError` on spawn / IPC / RPC failure.

        Post-spawn state overrides (the legacy `balance_overrides` /
        `code_overrides` / `nonce_overrides` / `storage_overrides` kwargs)
        are NOT exposed on the constructor — apply them after construction
        via the registered `set_balance` / `set_code` / `set_nonce` /
        `set_storage_at` methods. See module-level note.
        """
    @property
    def http_url(self, /) -> str:
        """
        HTTP endpoint of the spawned anvil node (`http://127.0.0.1:PORT`).
        """
    @property
    def ipc_path(self, /) -> str:
        """
        Resolved IPC socket path the spawned anvil process is listening on
        (the requested `--ipc` arg, or anvil's default `/tmp/anvil.ipc`).

        Use this to construct a secondary `AlloyProvider` against the
        same IPC socket (e.g. retry-aware `eth_call` / `get_logs` against
        the in-memory fork). The legacy Python `AnvilFork.w3` handle is
        replaced by that pattern in FF4.
        """
    def mine(self, /) -> None:
        """
        `evm_mine` — mine a single block.

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    @property
    def port(self, /) -> int:
        """
        TCP port the spawned anvil node listens on.
        """
    def reset(self, /, block_number: int | None = None) -> None:
        """
        `anvil_reset` — reset the fork, optionally re-fork to a new block
        number.

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    def revert(self, /, snapshot_id: Any) -> bool:
        """
        `anvil_revert` — revert to a snapshot. Returns `True` if reverted.

        Accepts the `int` returned by [`PyAnvilFork::snapshot`].

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    def set_balance(self, /, address: str, balance: Any) -> None:
        """
        `anvil_set_balance`.

        # Errors
        `ValueError` on invalid address; `RuntimeError` if the RPC call
        fails.
        """
    def set_block_timestamp_interval(self, /, seconds: int) -> None:
        """
        `anvil_set_block_timestamp_interval`.

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    def set_code(self, /, address: str, code: bytes) -> None:
        """
        `anvil_set_code`.

        # Errors
        `ValueError` on invalid address; `RuntimeError` if the RPC call
        fails.
        """
    def set_coinbase(self, /, address: str) -> None:
        """
        `anvil_set_coinbase`.

        # Errors
        `ValueError` on invalid address; `RuntimeError` if the RPC call
        fails.
        """
    def set_next_base_fee(self, /, basefee: int) -> None:
        """
        `anvil_set_next_block_base_fee_per_gas`.

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    def set_next_block_timestamp(self, /, timestamp: int) -> None:
        """
        `anvil_set_next_block_timestamp`.

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    def set_nonce(self, /, address: str, nonce: int) -> None:
        """
        `anvil_set_nonce`.

        # Errors
        `ValueError` on invalid address; `RuntimeError` if the RPC call
        fails.
        """
    def set_storage_at(self, /, address: str, slot: Any, value: Any) -> None:
        """
        `anvil_set_storage_at`.

        # Errors
        `ValueError` on invalid address; `RuntimeError` if the RPC call
        fails.
        """
    def snapshot(self, /) -> Any:
        """
        `anvil_snapshot` — take a snapshot, returning the snapshot id as a
        Python `int`.

        # Errors
        `RuntimeError` if the RPC call fails.
        """
    @property
    def ws_url(self, /) -> str:
        """
        WebSocket endpoint of the spawned anvil node (`ws://127.0.0.1:PORT`).
        """

__all__ = [
    "AnvilFork",
]
