# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
Register the pool-updater seam on `m` (feature = "pool").

# Errors

Returns a [`PyErr`] if any `add_function`/`add_class` call fails (a name
collision); propagated unchanged to the `#[pymodule]` caller.
The `degenbot._ffi.pool` Python submodule (declarative `#[pymodule]`),
carrying the pool-updater chunk-loop + liquidity-map verify pyfunctions.
The parent module registers the submodule itself and its `sys.modules`
entry. `CancelHandle` is registered by `crate::cancel::cancel` (shared
with the Aave updater seam).
"""

from .cancel import CancelHandle

def run_pool_update(
    database_path: str,
    chain_id: int,
    to_block: int | None,
    chunk_size: int,
    rpc_url: str,
    cancel_handle: CancelHandle,
    verify_chunk: bool = False,
    *,
    verify_all_interval: int | None = None,
    verify_all_at_completion: bool = False,
) -> dict:
    """
    `degenbot._ffi.pool.run_pool_update(database_path, chain_id, to_block,
    chunk_size, rpc_url, cancel_handle) -> dict`

    Drive the Rust-owned pool-updater chunk loop for `chain_id`, advancing
    every active exchange's `last_update_block` to `to_block` (or the chain
    tip if `to_block is None`). See
    [`degenbot_pool_updater::run::run_pool_update`] for the
    chunk-atomicity invariants (`docs/architecture/chunk-atomicity.md`;
    atomicity / restart-invariance / idempotent re-run) +
    [`degenbot_pool_updater::run::apply_chunk_writes_on_conn`] for the
    transaction-semantics core.

    The GIL is released across the WHOLE run (`py.detach`) and the core
    emits its own throttled operator progress lines — no per-chunk
    GIL re-acquisition. A Python-side `KeyboardInterrupt` won't pre-empt
    mid-chunk; Task 5's SIGINT handler calls `cancel_handle.cancel()` (the
    cooperative flag the loop polls between chunks — the interrupt contract
    (`docs/architecture/chunk-atomicity.md`):
    SIGINT between chunks → honored immediately; SIGINT mid-chunk → the chunk
    completes atomically first).

    # Args

    - `database_path` — the writeable `DegenbotDb` path (must already be
      migrated to the Rust-owned schema; the chunk loop does NOT migrate).
    - `chain_id` — the chain to advance.
    - `to_block` — `int` to advance to a specific block; `None` to advance to
      the chain tip (resolved via `eth_blockNumber`).
    - `chunk_size` — blocks per chunk (the `MAX_BLOCKS_PER_REQUEST`-aligned
      batch the RPC fetch + the chunk's single transaction cover).
    - `rpc_url` — the HTTP RPC endpoint.
    - `cancel_handle` — a [`CancelHandle`] constructed up front; a
      `signal.SIGINT` handler calls `.cancel()` on it to stop the run at the
      next chunk boundary.

    # Returns

    A `dict` `{chain_id, from_block, to_block, chunks_committed,
    total_pools_written, total_liquidity_applies}`.

    # Raises

    `ValueError` on a DB or RPC failure (the in-flight chunk is rolled back
    before returning; committed chunks stay durable).
    `RuntimeError` if cancelled (the `cancel` flag was set; committed chunks
    durable, in-flight chunk rolled back).

    # Runtime nesting

    Must NOT be called from within an existing `tokio` runtime (the core owns
    its runtime; nesting panics). The CLI driver runs this from a worker
    thread with no ambient runtime. See the module docs.
    """

def verify_v3_liquidity_map(
    database_path: str, rpc_url: str, chain_id: int, pool_address: str, block_number: int
) -> list[dict]:
    """
    `degenbot._ffi.pool.verify_v3_liquidity_map(database_path, rpc_url, chain_id,
    pool_address, block_number) -> list[dict]`

    Standalone on-chain-truth verification of a V3 pool's COMMITTED liquidity
    map (read-only — no SQL writes, no event apply). Opens the DB, fetches the
    pool's `liquidity_positions` + `initialization_maps` rows, builds the
    in-memory map, + compares EVERY tick + bitmap word against on-chain
    `IUniswapV3Pool.ticks(int24)` / `tickBitmap(int16)` at `block_number`, all
    batched through Multicall3. Returns the divergence list (empty = GREEN —
    the DB matches the chain at `block_number`).

    This is the ad-hoc / spot-check sibling of the pre-commit gate
    (`run_pool_update(verify=True)`); the gate runs the SAME core verify
    BEFORE the write commits, while this reads the already-committed state.
    Per-position `eth_call`s are batched via Multicall3.

    The GIL is released across the whole call (`py.detach`); the `AlloyProvider`
    is owned internally and the call runs on the ambient tokio runtime — a
    missing runtime is a typed error, never a per-call runtime build
    ([`no_ambient_runtime_err`]; mirrors the aave verify seam).
    """

def verify_v4_liquidity_map(
    database_path: str,
    rpc_url: str,
    chain_id: int,
    pool_hash: str,
    pool_manager_address: str,
    block_number: int,
) -> list[dict]:
    """
    `degenbot._ffi.pool.verify_v4_liquidity_map(database_path, rpc_url, chain_id,
    pool_hash, pool_manager_address, block_number) -> list[dict]`

    Standalone on-chain-truth verification of a V4 pool's COMMITTED liquidity
    map via the singleton `PoolManager.extsload(bytes32[])` at `block_number`
    (read-only — mirrors [`verify_v3_liquidity_map`]). `pool_hash` is the V4
    `PoolId` (bytes32 hex, `0x…`); `pool_manager_address` is the deployed V4
    `PoolManager` singleton (the chain has one — it's the V4 exchange's
    `factory`). Returns the divergence list (empty = GREEN).

    The GIL is released across the whole call; the provider is owned
    internally and the call runs on the ambient tokio runtime (a missing
    runtime is a typed error, never a per-call runtime build —
    [`no_ambient_runtime_err`]).
    """

__all__ = [
    "run_pool_update",
    "verify_v3_liquidity_map",
    "verify_v4_liquidity_map",
]
