# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.price` Python submodule (declarative `#[pymodule]`),
carrying the price-reader pyclasses. The parent module registers the
submodule itself and its `sys.modules` entry.
"""

from collections.abc import Sequence
from typing import Any, final

from .provider import AlloyProvider

@final
class AavePriceOracle:
    """
    A typed Aave price-oracle reader.

    Constructed with the oracle contract address + a shared `AlloyProvider`;
    `fetch` issues one `getAssetPrice(address)` `eth_call` per asset through
    the Rust path, tolerantly skipping assets that revert or fail to decode.
    """
    def __new__(cls, /, oracle_address: str, provider: AlloyProvider) -> AavePriceOracle:
        """
        Create a new Aave price-oracle reader.

        Args:
            `oracle_address`: Aave price-oracle contract address (hex string)
            provider: An existing `AlloyProvider` instance
        """
    @property
    def address(self, /) -> str:
        """
        The oracle contract address (EIP-55 checksummed hex string).
        """
    def fetch(self, /, asset_addresses: Sequence[str]) -> dict:
        """
        Fetch prices for a batch of assets, tolerantly.

        Mirrors `OraclePriceFetcher.fetch`: a failure on one asset (contract
        revert, decode error, or any other RPC failure) is logged and skipped,
        and the successfully-fetched prices are returned.

        Args:
            `asset_addresses`: Iterable of token addresses (hex strings)

        Returns:
            A dict mapping each checksummed asset address to its price (int).
            Assets that failed to fetch are omitted.
        """
    def get_asset_price(self, /, asset_address: str) -> Any:
        """
        Call `getAssetPrice(asset)` and return the `uint256` price.

        Args:
            `asset_address`: Token address (hex string)

        Returns:
            The price as a Python int.
        """

@final
class ChainlinkPriceFeed:
    """
    A typed Chainlink aggregator price feed.

    Constructed with the aggregator address + a shared `AlloyProvider`; routes
    `decimals()` / `latestRoundData()` through the Rust `eth_call` + ABI decode
    path (no Python `abi_decode` / `provider.call_raw` round-trip).
    """
    def __new__(
        cls, /, address: str, provider: AlloyProvider, chain_id: int | None = None
    ) -> ChainlinkPriceFeed:
        """
        Create a new Chainlink price-feed reader.

        Args:
            address: Aggregator contract address (hex string)
            provider: An existing `AlloyProvider` instance
            `chain_id`: Optional chain id (bookkeeping only; does not affect RPC)
        """
    @property
    def address(self, /) -> str:
        """
        The aggregator contract address (EIP-55 checksummed hex string).
        """
    @property
    def chain_id(self, /) -> int | None:
        """
        The chain id supplied at construction (bookkeeping only).
        """
    def decimals(self, /) -> int:
        """
        Call `decimals()` and return the feed's decimal places (`uint8`).
        """
    def latest_round_data(self, /) -> Any:
        """
        Call `latestRoundData()` and return the decoded tuple as Python ints:
        `(round_id, answer, started_at, updated_at, answered_in_round)`.

        `answer` is the raw `int256` aggregate price (in the feed's native
        decimals); callers apply the decimal correction.
        """
    def price(self, /) -> Any:
        """
        The decimal-corrected nominal price as a `U256` (whole units) — the
        integer analogue of `int(answer // 10**decimals)`. Negative answers
        (never for live USD feeds, but allowed by the `int256` ABI type) clamp
        to zero.

        Note: the Python shell `ChainlinkPriceContract.price` (a float)
        computes `float(answer) / 10**decimals` from `latest_round_data` +
        `decimals` to preserve the prior float-exact behavior *including* the
        fractional part; this `price` truncates and is exposed for direct
        Rust/standalone consumers.
        """

__all__ = [
    "AavePriceOracle",
    "ChainlinkPriceFeed",
]
