# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.provider` Python submodule (declarative
`#[pymodule]`), carrying the sync provider/filter/subscription pyclasses
(plus the async provider under `feature = "async"`). The parent module
registers the submodule itself and its `sys.modules` entry.
"""

from collections.abc import Sequence
from typing import Any, final

@final
class AlloyProvider:
    """
    Python wrapper for `AlloyProvider`.
    """
    def __new__(
        cls,
        /,
        rpc_url: str,
        max_retries: int = 10,
        max_blocks_per_request: int = 5000,
        requests_per_second: int | None = None,
        burst: int | None = None,
        chain_id: int | None = None,
    ) -> AlloyProvider:
        """
        Create a new provider.

        Automatically detects connection type from URL:
        - HTTP/HTTPS URLs use HTTP transport with connection pooling
        - WS/WSS URLs use WebSocket transport
        - File paths (Unix: /path, Windows: \\.\pipe\...) use IPC transport

        # Retry Behavior

        The provider implements exponential backoff with jitter for retryable errors:
        - Initial delay: 100ms
        - Max delay: 30 seconds
        - Backoff multiplier: 2x
        - Jitter: up to 100ms (randomized)
        - Max attempts: `max_retries + 1` (1 initial + retries)

        Retryable errors: rate limits (HTTP 429), timeouts, connection failures.

        # Rate Limiting (HTTP only, opt-in)

        By default, HTTP connections run without transport-level rate limiting.
        Pass `requests_per_second` and `burst` to enable throttling, which avoids
        overwhelming the RPC endpoint. `requests_per_second` controls the sustained
        rate, while `burst` allows temporary spikes. Both must be provided together
        to activate throttling. These parameters are ignored for WS/IPC transports.

        `chain_id` binds the endpoint to a chain: the core reads `eth_chainId`
        once at construction and raises `ValueError` when the endpoint serves
        another chain. `None` constructs the provider with no binding.
        """
    def __repr__(self, /) -> str: ...
    def call(self, /, to: str, data: bytes, block_number: int | None = None) -> Any:
        """
        Execute an `eth_call` to a contract.
        """
    def close(self, /) -> None:
        """
        Close the underlying connection pool and release resources.
        """
    def estimate_gas(
        self,
        /,
        to: str,
        data: bytes,
        from_: str | None = None,
        value: int | None = None,
        block_number: int | None = None,
    ) -> int:
        """
        Estimate gas for a transaction.
        """
    def get_balance(self, /, address: str, block_number: int | None = None) -> Any:
        """
        Get the balance of an address in wei.
        """
    def get_block(self, /, block_number: int) -> Any | None:
        """
        Get a block by number.

        Returns the full block data including header and transactions.
        All field names use `snake_case` for Python consistency.
        """
    def get_block_number(self, /) -> int:
        """
        Get current block number.
        """
    def get_chain_id(self, /) -> int:
        """
        Get chain ID.
        """
    def get_code(self, /, address: str, block_number: int | None = None) -> Any:
        """
        Get contract code at an address.
        """
    def get_gas_price(self, /) -> int:
        """
        Get current gas price.
        """
    def get_logs(
        self,
        /,
        *,
        from_block: int,
        to_block: int,
        addresses: Sequence[str] | None = None,
        topics: Sequence[Sequence[str]] | None = None,
    ) -> list:
        """
        Fetch logs synchronously (blocking).
        """
    def get_storage_at(
        self, /, address: str, position: Any, block_number: int | None = None
    ) -> Any:
        """
        Get storage at a given address and position.
        """
    def get_transaction(self, /, tx_hash: str) -> Any | None:
        """
        Get a transaction by hash.
        """
    def get_transaction_count(self, /, address: str, block_number: int | None = None) -> int:
        """
        Get the transaction count (nonce) for an address.
        """
    def get_transaction_receipt(self, /, tx_hash: str) -> Any | None:
        """
        Get a transaction receipt by hash.
        """
    def make_request(self, /, method: str, params: list) -> Any:
        """
        Make a raw JSON-RPC request.

        This allows calling arbitrary RPC methods that don't have typed wrappers.

        # Arguments
        * `method` - The RPC method name (e.g., "`debug_traceTransaction`")
        * `params` - The parameters as a list (will be serialized to JSON array)

        # Returns
        The raw result as a Python object (deserialized from JSON)
        """
    @staticmethod
    def offline_from_json_file(path: str) -> AlloyProvider:
        """
        Build an offline `AlloyProvider` from a recorded-JSON file.

        The JSON may be either the single-block format (`{chain_id, block_number,
        timestamp, calls, code}`) or the multi-block format (`{chain_id, blocks:
        {"<n>": {…}}}`). All RPCs are served from the in-memory recorded data —
        no network connection is needed.

        # Errors

        `ValueError` if the file cannot be read or is not valid recorded data.
        """
    @staticmethod
    def offline_from_json_string(s: str) -> AlloyProvider:
        """
        Build an offline `AlloyProvider` from a recorded-JSON string.

        See [`offline_from_json_file`](Self::offline_from_json_file) for the
        accepted formats.

        # Errors

        `ValueError` if the string is not valid recorded data.
        """
    @property
    def rpc_url(self, /) -> str: ...
    def subscribe_blocks(self, /) -> AlloySubscription:
        """
        Subscribe to new block headers.

        Returns an `AlloySubscription` that yields block header dicts
        via the async iterator protocol.

        Requires a WebSocket or IPC transport. Raises `RuntimeError` for HTTP providers.
        """
    def subscribe_full_blocks(self, /) -> AlloySubscription:
        """
        Subscribe to full block bodies.

        Returns an `AlloySubscription` that yields full block dicts.
        """
    def subscribe_full_pending_transactions(self, /) -> AlloySubscription:
        """
        Subscribe to full pending transaction bodies.

        Returns an `AlloySubscription` that yields transaction dicts.
        """
    def subscribe_logs(
        self,
        /,
        addresses: Sequence[str] | None = None,
        topics: Sequence[Sequence[str]] | None = None,
    ) -> AlloySubscription:
        """
        Subscribe to logs matching the given filter.

        # Arguments
        * `addresses` - Optional list of contract addresses to filter
        * `topics` - Optional list of topic filters (nested: [[topic0], [topic1], ...])

        Returns an `AlloySubscription` that yields log receipt dicts.
        """
    def subscribe_pending_transactions(self, /) -> AlloySubscription:
        """
        Subscribe to pending transaction hashes.

        Returns an `AlloySubscription` that yields transaction hash hex strings.
        """
    def verify_gil_release(self, /) -> bool:
        """
        Verify that `py.detach()` releases the GIL by spawning an OS thread
        that re-acquires it via `Python::attach()`.

        Returns `True` if the spawned thread successfully acquired the GIL
        while the current thread had released it inside `py.detach()`,
        proving the GIL was actually released. Returns `False` if the spawned
        thread could not acquire the GIL (meaning `py.detach()` did not release it).

        This is a deterministic, timing-free test — no sleep or scheduling
        assumptions required.
        """

@final
class AlloySubscription:
    """
    Python wrapper for a subscription.

    Implements the async iterator protocol so users can write:

    ```python
    async for header in subscription:
        print(header)
    ```

    Also provides `drain()` for bulk consumption:

    ```python
    items = subscription.drain()  # Returns list[dict]
    ```

    And `started()` to await subscription confirmation:

    ```python
    await subscription.started()  # Raises on failure
    ```
    """
    def __aiter__(self, /) -> AlloySubscription:
        """
        Return self as the async iterator.
        """
    def __anext__(self, /) -> Any:
        """
        Return the next item from the subscription as an awaitable.

        Always returns a coroutine (via `future_into_py`) so that
        `await sub.__anext__()` and `async for item in sub` work
        correctly. The fast path (items already in local batch or
        Rust buffer) resolves the future immediately.
        """
    def __repr__(self, /) -> str: ...
    def drain(self, /) -> list[Any]:
        """
        Drain accumulated items from the subscription.

        Swaps the internal double-buffer and bulk-converts all accumulated
        items to Python dicts. Returns a list of items. The list may be
        empty if no items have arrived since the last drain.

        Raises `StopAsyncIteration` if the subscription has ended.
        Raises `RuntimeError` if the subscription has disconnected.
        """
    def started(self, /) -> Any:
        """
        Wait for the subscription to be confirmed by the node.

        Resolves when the WS subscription is active. Raises if the
        subscription failed to establish.
        """
    def unsubscribe(self, /) -> None:
        """
        Unsubscribe from the event stream.

        Stops the background pump task. After calling this,
        `__anext__()` will raise `StopAsyncIteration`.
        """

@final
class AsyncAlloyProvider:
    """
    Python wrapper for async provider operations.
    """
    def __new__(cls, /, sync_provider: AlloyProvider) -> AsyncAlloyProvider:
        """
        Create a new async provider from an existing sync provider.

        This constructor takes a `PyAlloyProvider` and creates an async wrapper
        around it. The async provider uses Python's asyncio event loop instead
        of creating its own runtime.
        """
    def __repr__(self, /) -> str: ...
    def call(self, /, to: str, data: Sequence[int], block_number: int | None = None) -> Any:
        """
        Execute an `eth_call` to a contract asynchronously.
        """
    def close(self, /) -> None:
        """
        Close the provider.
        """
    @staticmethod
    def create(
        rpc_url: str,
        max_retries: int = 10,
        max_blocks_per_request: int = 5000,
        requests_per_second: int | None = None,
        burst: int | None = None,
        chain_id: int | None = None,
    ) -> Any:
        """
        Create a new async provider from RPC URL.

        This is an async factory method that creates both the underlying provider
        and the async wrapper in one call.

        # Arguments
        * `rpc_url` - The RPC endpoint URL
        * `max_retries` - Maximum retry attempts (default: 10)
        * `requests_per_second` - Rate limit for HTTP connections (opt-in, must pair with `burst`)
        * `burst` - Burst size for rate limiting (opt-in, must pair with `requests_per_second`)
        * `chain_id` - Chain the endpoint is bound to; the core reads
          `eth_chainId` once and raises `ValueError` on a disagreement
        """
    def estimate_gas(
        self,
        /,
        to: str,
        data: Sequence[int],
        from_: str | None = None,
        value: int | None = None,
        block_number: int | None = None,
    ) -> Any:
        """
        Estimate gas for a transaction asynchronously.
        """
    def get_balance(self, /, address: str, block_number: int | None = None) -> Any:
        """
        Get the balance of an address in wei asynchronously.
        """
    def get_block(self, /, block_number: int) -> Any:
        """
        Get a block by number asynchronously.
        """
    def get_block_number(self, /) -> Any:
        """
        Get current block number asynchronously.
        """
    def get_chain_id(self, /) -> Any:
        """
        Get chain ID asynchronously.
        """
    def get_code(self, /, address: str, block_number: int | None = None) -> Any:
        """
        Get contract code at an address asynchronously.
        """
    def get_gas_price(self, /) -> Any:
        """
        Get current gas price asynchronously.
        """
    def get_logs(
        self,
        /,
        from_block: int,
        to_block: int,
        addresses: Sequence[str] | None = None,
        topics: Sequence[Sequence[str]] | None = None,
    ) -> Any:
        """
        Get logs asynchronously with chunked fetching.
        """
    def get_storage_at(
        self, /, address: str, position: Any, block_number: int | None = None
    ) -> Any:
        """
        Get storage at a given address and position asynchronously.
        """
    def get_transaction(self, /, tx_hash: str) -> Any:
        """
        Get a transaction by hash asynchronously.
        """
    def get_transaction_count(self, /, address: str, block_number: int | None = None) -> Any:
        """
        Get the transaction count (nonce) for an address asynchronously.
        """
    def get_transaction_receipt(self, /, tx_hash: str) -> Any:
        """
        Get a transaction receipt by hash asynchronously.
        """
    def make_request(self, /, method: str, params: list) -> Any:
        """
        Make a raw JSON-RPC request asynchronously.

        This allows calling arbitrary RPC methods that don't have typed wrappers.
        """
    @property
    def rpc_url(self, /) -> str:
        """
        Get the RPC URL.
        """

@final
class LogFilter:
    """
    Python wrapper for `LogFilter`.
    """
    def __new__(
        cls,
        /,
        from_block: int,
        to_block: int,
        addresses: Sequence[str] | None = None,
        topics: Sequence[Sequence[str]] | None = None,
    ) -> LogFilter:
        """
        Create a new `LogFilter`.
        """
    def __repr__(self, /) -> str: ...
    @property
    def addresses(self, /) -> list[str]: ...
    @property
    def from_block(self, /) -> int | None: ...
    @property
    def to_block(self, /) -> int | None: ...
    @property
    def topics(self, /) -> list[list[str]]: ...

__all__ = [
    "AlloyProvider",
    "AlloySubscription",
    "AsyncAlloyProvider",
    "LogFilter",
]
