# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/ffi/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.simulation` Python submodule (declarative
`#[pymodule]`), carrying the simulation pyclasses + the
dispatch/assembly/probe pyfunctions. The parent module registers the
submodule itself and its `sys.modules` entry.
"""

from collections.abc import Sequence
from typing import Any, Final, final

from _typeshed import Incomplete

from . import ArbitrageEngine, ConfigValues
from .provider import AsyncAlloyProvider
from .submission import Dispatcher, TxSigner

@final
class AssemblyVerdict:
    """
    Stage 1 — the assembly verdict (the core's typed skip taxonomy).
    """

    Assembled: Final[AssemblyVerdict]
    SkipDivergentPool: Final[AssemblyVerdict]
    SkipEmptyHops: Final[AssemblyVerdict]
    SkipFeeOnTransfer: Final[AssemblyVerdict]
    SkipPayloadServed: Final[AssemblyVerdict]
    SkipResolveMiss: Final[AssemblyVerdict]
    SkipSuppressed: Final[AssemblyVerdict]
    SkipThinMargin: Final[AssemblyVerdict]
    def __int__(self, /) -> int: ...

@final
class BatchExecutor:
    """
    The per-session executor over the core batch choreography.
    """
    def enqueue(self, /, work: Incomplete) -> None:
        """
        Enqueue one batch: the rows enter the core's ordered lane (assembly,
        sim, and submit run internally; the records surface on
        `next_outcome`).

        GIL-held path resolution happens HERE (the pre-cut-over seam's resolve
        point, on the driver's loop thread): payload rows resolve LOUD (a miss
        is a `ValueError` — the pinned string survives) and raw rows resolve
        leniently (a miss stays unresolved; the core folds the typed
        `SkipResolveMiss`).

        # Errors

        `ValueError`: a payload dict is malformed, or a payload row's
        `path_id` is not registered in the engine.
        """
    @property
    def enqueued(self, /) -> int:
        """
        How many batches have been enqueued.
        """
    def next_outcome(self, /) -> Any:
        """
        Await the next batch's outcome set (`None` once the executor is shut
        down and drained — the drain loop's terminator).
        """
    def raise_if_failed(self, /) -> None:
        """
        Re-raise the first stored leaf failure in the caller's frame (the
        loud-abort rule).

        # Errors

        `RuntimeError` when a sim or submit leaf failed.
        """
    def shutdown(self, /) -> Any:
        """
        Drain in-flight work and join the submitter.

        # Errors

        `RuntimeError` when a sim or submit leaf failed.
        """
    @property
    def submitted(self, /) -> int:
        """
        How many batches the ordered submitter has processed.
        """

@final
class BatchOutcome:
    """
    The typed result of one candidate's ordered pass through the pipeline
    (the core's `BatchOutcome`).
    """
    @property
    def assembly(self, /) -> AssemblyVerdict:
        """
        The stage-1 assembly verdict.
        """
    @property
    def block(self, /) -> int:
        """
        The block the batch was consumed at (the liveness heartbeat).
        """
    @property
    def path_id(self, /) -> int:
        """
        The candidate's arb path id.
        """
    def path_info_dict(self, /) -> dict:
        """
        The `[profit]`/`[sim-fail]` render dict for this record's path
        (`path_type` + per-hop dicts — the ONE serializer shape
        `DispatchOutcome.path_infos` emits).
        """
    @property
    def path_type(self, /) -> str:
        """
        The combined pool-type label (`"V2-V3"`, `"V4-V2"`, … — the
        renderers' `path_type`).
        """
    @property
    def simulate(self, /) -> SimulateVerdict | None:
        """
        The stage-2 simulate verdict (`None` when the row never reached the
        sim stage).
        """
    @property
    def submit(self, /) -> SubmitVerdict | None:
        """
        The stage-3 submit verdict (`Some` only after a gas-profitable sim
        reaches the submit lane).
        """

@final
class BatchOutcomeSet:
    """
    One drained batch: the candidate outcome records + the RAW submit-lane
    records the Python drain renders (the `[dispatch]` per-record lines +
    the silent-veto smoke FSM).
    """
    @property
    def records(self, /) -> list[BatchOutcome]:
        """
        The per-candidate outcome records, in submit order.
        """
    @property
    def submit_records(self, /) -> list:
        """
        The submit-lane records as the FFI wire dicts (the
        `dispatch_and_submit` shape — `typed_submit_record` decodes them).
        """

@final
class CandidateAssembly:
    """
    The batched assembly result: ready candidates + the skipped empty-hop path
    ids (the display-only `[sim-none]` log's input).
    """
    @property
    def candidates(self, /) -> list:
        """
        The assembled candidates as `list[DispatchCandidate]` (the sim seam's
        input shape), in input-row order.
        """
    @property
    def empty_hop_path_ids(self, /) -> list[int]:
        """
        Path ids skipped for empty hop outputs — the driver logs each.
        """

@final
class DispatchCandidate:
    """
    The pre-simulation candidate builder — the engine result + the resolved
    `PathInfo` + the encode options.

    Ports the Python `EngineResult` tuple `(path_id, opt_input, profit,
    hop_outputs, solve_block)` + the `engine_registry.paths.get(path_id)`
    `PathInfo` resolve. Construct one per solved path, per block.
    """
    def __new__(
        cls,
        /,
        engine: ArbitrageEngine,
        path_id: int,
        optimal_input: int,
        engine_profit: int,
        hop_outputs: Sequence[int],
        consumed_inputs: Sequence[int],
        solve_block: int,
        state_nonces: Sequence[int],
        *,
        erc6909_profit: bool = False,
        use_v4_batch: bool = False,
    ) -> DispatchCandidate:
        """
        Build a candidate from the engine result + a registered `path_id`.

        The candidate resolves its `composers::PathInfo` from `path_id` via
        the engine's `path_info_for_core` projection over the shared
        `BotState` — no Python `PathInfo` dataclass is threaded.

        Args:
            `engine`: the engine wrapper that owns `path_id` (the same
                engine that produced `engine_profit`/`hop_outputs`).
            `path_id`: the unique arb path identifier.
            `optimal_input`: the solver's optimal swap input (u128).
            `engine_profit`: the solver's expected gross profit (u128) — used
                for sorting + the thin-margin filter; NOT the on-chain gross
                (that's `SimResult::gross_profit`).
            `hop_outputs`: the per-hop solver outputs (`list[int]`).
            `consumed_inputs`: the per-hop executable inputs fed into each pool
                (`list[int]`) — the solver's CL-hop clamp; the encoder feeds
                these (not `hop_outputs`) as each CL pool's swap-in. May be
                shorter than `hop_outputs` only in a degenerate/solver-defect
                case, surfaced as `ValueError`.
            `solve_block`: the block the solver produced the result on.
            `state_nonces`: per-hop state nonces captured at solve time
                (the staleness gate — the dispatch seam skips candidates
                whose pool state has advanced since the solve).
            `erc6909_profit`: encode the V4 profit as an ERC6909 transfer
                (default `False`).
            `use_v4_batch`: encode V4 hops as a batched `unlock`-callback
                (default `False`).

        # Errors
        `ValueError`: if `path_id` is not registered in `engine`, or a hop
                has no command-stream encoder arm (Solidly / Balancer / Curve),
                or `hop_outputs`/`consumed_inputs` length ≠ path hops.
        """

@final
class DispatchOutcome:
    """
    The read-only outcome of a block's profitable-dispatch fan-out.

    Constructed by `dispatch_profitable_py` (A4); the cockpit renders the
    `[sim]` summary from the counters + `fail_buckets`, then hands
    `gas_profitable` straight to `dispatch_and_submit_py`.
    """
    @property
    def candidate_count(self, /) -> int: ...
    @property
    def divergent_dropped(self, /) -> int:
        """
        The per-call pool-divergence skip count  — candidates
        dropped pre-sim because they routed through a pool flagged `SolverCalc`
        within the decay window. Mirrors `thin_dropped` / `suppressed_count`.
        """
    @property
    def exception_count(self, /) -> int: ...
    @property
    def fail_buckets(self, /) -> dict:
        """
        The revert/no-profit/overflow bucket tally — `{bucket: count}`.

        Drives the `[sim] … by reason: {breakdown}` summary line (rendered in
        Python — D4 stays-python).
        """
    @property
    def fail_count(self, /) -> int: ...
    @property
    def failures(self, /) -> list:
        """
        The per-path simulation failure detail — `list[dict[str, Any]]`, one
        entry per failed candidate in fan-out order. Each dict carries:
          - `path_id` (`int`),
          - `bucket` (`str`) — the `classify_revert` label for reverts, else
            the orchestration-only bucket (`int128-overflow`, `encode-failed`,
            `rpc-failed`, `balance-decode`, `no-profit`),
          - `fail_index` (`int | None`) — the index of the failing call in the
            7-call vector when attributable to one (the revert branch + the
            balance-decode branch); `None` for orchestration-only buckets,
          - `revert_data` (`str`) — the raw revert bytes as `0x`-prefixed hex;
            `"0x"` (empty) for orchestration-only buckets.
          - `reverting_frame` (`dict | None`) — the inspector-captured deep
            attribution for `execute()` reverts: `depth` (`int`), `target`
            (`str` address), `selector` (`str` 4-byte hex), `revert_data`
            (`str` hex), `label` (`str`). `None` for orchestration-only buckets
            + the balance-decode branch .
          - `captured_swaps` (`list[dict]`) — the V2/V3/V4 swap events captured
            before the revert (per-swap `family`/`emitter`/`amount0`/`amount1`/"+ "
            `sqrt_price_x96`/`liquidity`/`tick`). Empty for orchestration-only
            buckets + the balance-decode branch .

        Consumed by the Python companion's `[sim-fail]` renderer so the
        operator can identify WHICH path reverted against WHICH pools.
        Built at construction (the core-producing `SimFailure`s are owned,
        not rebuilt on access).
        """
    @property
    def fot_dropped(self, /) -> int:
        """
        The per-call candidate count dropped because a hop's input token was
        FoT-confirmed .
        """
    @property
    def gas_profitable(self, /) -> list:
        """
        The gas-profitable candidates — `list[PySubmitCandidate]`, the direct
        handoff to `dispatch_and_submit_py`.

        Each access rebuilds the list from the held core `SubmitCandidate`s
        (the join source-of-truth lives in Rust; Python sees fresh wrappers).
        """
    @property
    def gas_unprofitable_count(self, /) -> int: ...
    @property
    def path_infos(self, /) -> dict:
        """
        The input candidates' `PathInfo` keyed by `path_id` — `{path_id:
        dict}`. Populated from the INPUT batch (every candidate passed in,
        not filtered to survivors). The `[profit]` hop-detail log looks up
        `path_infos[cand.path_id]` per survivor; preserved here (Decision 1=B,
        A5) so the cockpit doesn't thread a separate map.

        Each value is a plain `dict` (the Python `hop_info`
        dataclass render type retired):
          - `path_type` (`str`) — the combined pool-type label,
          - `hops` (`list[dict]`) — one dict per hop, carrying a `family`
            discriminator (`"V2"`/`"V3"`/`"V4"`) + that variant's fields.

        Built directly from the Rust `HopInfo`s (no Python dataclass
        reconstruction — `path_info_to_py`/`hop_to_py` retired).
        """
    @property
    def profitable_captured_swaps(self, /) -> list:
        """
        The SUCCESS-path captured swaps — `list[dict]`, one entry per
        profitable survivor, each dict carrying `path_id` (`int`) +
        `captured_swaps` (`list[dict]` of per-swap `family`/`emitter`/
        `amount0`/`amount1`/`sqrt_price_x96`/`liquidity`/`tick`).

        The matching success-path surface to each `SimFailure.captured_swaps`
        the revert path surfaces via `failures()`. Each entry's swap list is
        the V2/V3/V4 `Swap` events the in-process EVM emitted during the
        survivor's `execute()` — the ground-truth hop output (no
        `getAmountOut` recompute, no Multicall3 reserves re-fetch needed). The
        step-5 classifier (`logs/permutation_analyzer.py` +
        `format_sim_diag_line`) re-points at these to retire
        `diagnostic.rs::recompute_v2/v3_amount_out`. Empty for survivors that
        swapped zero pools (shouldn't happen — `encode_cmd_stream` only builds
        swap commands for paths with hops).
        """
    @property
    def suppressed_count(self, /) -> int: ...
    @property
    def thin_dropped(self, /) -> int: ...

@final
class ExecutorPolicyValues:
    """
    The converted executor policy (see [`executor_policy_py`]). A frozen
    read-only view: the conversion owns every default and clamp, so there is
    nothing for a caller to set.
    """
    @property
    def erc6909_profit(self, /) -> bool:
        """
        The ERC6909 encode axis: `dispatch.erc6909_profit`.
        """
    @property
    def inject_code(self, /) -> bool:
        """
        The sim-injection stance: `simulation.inject_executor_code`.
        """
    @property
    def inject_code_guard(self, /) -> bool:
        """
        The submit-side guard: the SAME inject stance, converted once.
        """
    @property
    def min_profit_margin_bps(self, /) -> int:
        """
        The thin-margin floor: `dispatch.min_profit_margin_bps`.
        """
    @property
    def sim_concurrency(self, /) -> int:
        """
        The in-flight sim bound: `simulation.pipeline_concurrency`, floored
        at 1 by the conversion.
        """

@final
class FailureDetail:
    """
    The per-candidate failure detail (the core's `FailureDetail`). The render
    dicts the `[sim-fail]`/`[sim-diag]` renderers consume decode through
    `record()` — the ONE serializer shape `DispatchOutcome.failures` emits.
    """
    @property
    def bucket(self, /) -> str:
        """
        The failure-bucket label (`classify_revert` output or the
        orchestration-only tag).
        """
    @property
    def path_id(self, /) -> int:
        """
        The path that failed.
        """
    def record(self, /) -> dict:
        """
        The full render record — the `DispatchOutcome.failures` dict shape.
        """

@final
class FailureKind:
    """
    The typed submit-failure taxonomy (the core's `FailureKind`).
    """

    EncodeFailed: Final[FailureKind]
    Int128Overflow: Final[FailureKind]
    NoProfit: Final[FailureKind]
    Other: Final[FailureKind]
    Revert: Final[FailureKind]
    RpcFailed: Final[FailureKind]
    Stale: Final[FailureKind]
    def __int__(self, /) -> int: ...

@final
class PayloadOutcome:
    """
    The merged inline-sim payload record set — the payload arm of
    `PyDispatchOutcome`, built by `merge_payload_results_py`. Rust owns every
    policy fact; Python renders + stitches these getters into the merged
    outcome view.
    """
    @property
    def candidates(self, /) -> list:
        """
        The submit rows — `list[SubmitCandidate]`, the `gas_profitable`
        handoff shape (each element re-extracts as a `PySubmitCandidate`).
        """
    @property
    def failures(self, /) -> list:
        """
        The [sim-fail] rows — list[dict] with the FFI failures row keys
        (`path_id` / `bucket` / `fail_index` / `revert_data`).
        """
    @property
    def path_infos(self, /) -> dict:
        """
        `{path_id: path_info dict}` — the [profit]-render source (the SAME
        one-serializer shape `PyDispatchOutcome.path_infos` emits).
        """
    @property
    def unprofitable_count(self, /) -> int:
        """
        Valid sims whose net profit fell below the threshold — the merged
        outcome's `gas_unprofitable_count` slice.
        """
    @property
    def verdicts(self, /) -> list:
        """
        The per-entry verdicts — `list[PayloadVerdict]` (`path_id` + `kind`).
        """

@final
class PayloadVerdict:
    @property
    def kind(self, /) -> str:
        """
        "submit" | "unprofitable" — the arm tag (the threshold comparison ran
        Rust-side; Python renders the branch, it does not re-apply the rule).
        """
    @property
    def path_id(self, /) -> int:
        """
        The path id the verdict belongs to.
        """

@final
class SimReceipt:
    """
    The renderer-read projection of a profitable sim result (the core's
    `SimReceipt`).
    """
    @property
    def gas_used(self, /) -> int:
        """
        The simulate's raw `gasUsed` (UN-inflated; the 1.5× margin applies at
        submit time).
        """
    @property
    def gross_profit(self, /) -> Any:
        """
        Gross on-chain profit (wei).
        """
    @property
    def net_profit(self, /) -> Any:
        """
        Net profit = gross − gas cost (wei).
        """
    @property
    def priority_fee(self, /) -> int:
        """
        The market-aware priority fee.
        """

@final
class SimulateContext:
    """
    The session-static simulation config bag.

    Construct once per session from a `&PyAsyncAlloyProvider` + the addresses +
    the inject flag + the executor runtime bytecode. Hands to
    `dispatch_profitable_py` (A4) each block alongside the per-block args.
    """
    def __new__(
        cls,
        /,
        provider: AsyncAlloyProvider,
        executor_owner: str,
        executor_address: str,
        weth_address: str,
        pool_manager_address: str,
        multicall3_address: str,
        inject_code: bool,
        executor_runtime_bytecode: bytes,
        injected_address: str | None = None,
    ) -> SimulateContext:
        """
        Build a session-long simulation context.

        Args:
            `provider`: the `AsyncAlloyProvider` the cockpit dispatches over.
                Its inner `Arc<AlloyProvider>` is cloned here; A4 moves it into
                the async block.
            `executor_owner`: the operator key's address (hex string) — the
                `from` of `execute()` + the owner funded with ETH in
                `stateOverrides`.
            `executor_address`: the `cmd_executor` contract address (hex) — the
                `execute()` target + the balance-diff subject.
            `weth_address`: WETH9 contract address (hex).
            `pool_manager_address`: Uniswap V4 `PoolManager` address (hex).
            `multicall3_address`: Multicall3 contract address (hex).
            `inject_code`: whether to inject the executor runtime bytecode
                (the `INJECT_EXECUTOR_CODE` flag).
            `executor_runtime_bytecode`: the executor runtime bytecode bytes
                (the file-load stays Python; the bytes cross here).
            `injected_address`: the fresh address to inject the executor at
                (hex); required when `inject_code` is `True`.

        # Errors
        `ValueError`: if any address string is not a valid EIP-55 address, or
                `inject_code` is `True` and `injected_address` is `None`.
        """
    @property
    def executor_address(self, /) -> str:
        """
        The executor contract address (checksummed hex) — SIMPIPE2 T3: the
        Python payload path constructs `SubmitCandidate`s directly for
        inline-simulated entries, and the submit leaf needs the same
        session-static `executor_address` the FFI join stamps onto each one.
        """
    @property
    def rpc_url(self, /) -> str:
        """
        The RPC URL the held provider points at (for the `[sim]` log line).
        """

class SimulateVerdict:
    """
    Stage 2 — the per-candidate simulation outcome (the core's typed enum).
    """
    def kind(self, /) -> str:
        """
        The stable machine label — the display fold's discriminator.
        """
    @final
    class Exception(SimulateVerdict):
        """
        An unrecoverable per-path exception (counted, not propagated).
        """

        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> SimulateVerdict.Exception: ...

    @final
    class Failed(SimulateVerdict):
        """
        A per-candidate failure record (the `[sim-fail]` input).
        """

        __match_args__: Final = ("detail",)
        def __new__(cls, /, detail: FailureDetail) -> SimulateVerdict.Failed: ...
        @property
        def detail(self, /) -> FailureDetail:
            """
            The failure detail (`record()` decodes the render dict).
            """

    @final
    class GasUnprofitable(SimulateVerdict):
        """
        Onchain-valid but below the net threshold.
        """

        __match_args__: Final = ("receipt",)
        def __new__(cls, /, receipt: SimReceipt) -> SimulateVerdict.GasUnprofitable: ...
        @property
        def receipt(self, /) -> SimReceipt:
            """
            The same receipt value the core sorts on.
            """

    @final
    class Profitable(SimulateVerdict):
        """
        The sim committed and net profit reached the floor.
        """

        __match_args__: Final = ("receipt",)
        def __new__(cls, /, receipt: SimReceipt) -> SimulateVerdict.Profitable: ...
        @property
        def receipt(self, /) -> SimReceipt:
            """
            The renderer-read receipt.
            """

class SubmitVerdict:
    """
    Stage 3 — the submit receipt or typed failure (the core's typed enum; no
    drain reads inside this slot today — the raw submit-lane records the
    Python renderers consume ride `BatchOutcomeSet.submit_records`).
    """
    @final
    class Failed(SubmitVerdict):
        """
        The candidate reached the submit lane and did not broadcast.
        """

        __match_args__: Final = ("kind",)
        def __new__(cls, /, kind: FailureKind) -> SubmitVerdict.Failed: ...
        @property
        def kind(self, /) -> FailureKind:
            """
            The typed failure taxonomy member.
            """

    @final
    class Submitted(SubmitVerdict):
        """
        The tx was broadcast.
        """

        __match_args__: Final = ()
        def __getitem__(self, key: int, /) -> Any: ...
        def __len__(self, /) -> int: ...
        def __new__(cls, /) -> SubmitVerdict.Submitted: ...

def assemble_dispatch_candidates_py(
    engine: ArbitrageEngine,
    results: Sequence[Incomplete],
    *,
    erc6909_profit: bool = False,
    use_v4_batch: bool = False,
    skip_path_ids: Sequence[int] | None = None,
) -> CandidateAssembly:
    """
    Assemble a batch of raw engine-result rows into `DispatchCandidate`s.

    The skip predicates and the shape guard + candidate construction are
    crate-owned (see the module docs); this delegate resolves each surviving
    row's path through the engine and wraps the result.

    # Errors
    `ValueError`: a `path_id` is not registered in `engine`, a resolved path
    failed its `PathInfoBuildError` projection, or a row's
    `hop_outputs`/`consumed_inputs`/`state_nonces` length does not match the
    path's hop count (the crate's loud-abort shape guard).
    """

def build_batch_executor_py(
    context: SimulateContext,
    dispatcher: Dispatcher,
    engine: ArbitrageEngine,
    signer: TxSigner,
    submit_provider: AsyncAlloyProvider,
    operator_nonce: int,
    *,
    dry_run: bool,
    broadcast_providers: Sequence[AsyncAlloyProvider] | None = None,
) -> BatchExecutor:
    """
    Construct the session executor: the core's value-configured module over
    the INSTALLED verdict — the policy values (the cap, the thin-margin
    floor, the ERC6909 encode axis, the inject guards) convert from the same
    resolved config the Python verdict projects, with every default and
    clamp owned by that conversion. The driver injects only the runtime
    handles the verdict cannot name. Choreography code NEVER crosses.

    Args:
        `context`: the session `SimulateContext` (provider, addresses, the
            inject stance's runtime facts, runtime bytecode, warmup slots).
        `dispatcher`: the session `Dispatcher` (the coordination arcs ride it:
            suppression, divergence, `FoT`, priority-fee ring).
        `engine`: the `ArbEngine` (the path resolver projection + the
            `BotState`/warm-code arcs).
        `signer`: the operator `TxSigner` (constructed ONCE; the key never
            leaves Rust).
        `submit_provider`: the read/broadcast provider handle.
        `operator_nonce`: the construction-time chain-read nonce seed (the
            lane's first stamp never re-issues a consumed nonce; the hosted
            per-head reconcile maintains it afterwards).
        `dry_run`: skip live submission (the driver's run-mode stance — a CLI
            fact, not a declared key).
        `broadcast_providers`: the relay fan-out (the `RelayPosture` value's
            endpoints); `None`/empty = the public mempool (read provider
            only).

    # Errors

    `ValueError` on malformed addresses/args.
    """

def dispatch_profitable_py(
    candidates: list,
    context: SimulateContext,
    dispatcher: Dispatcher,
    base_fee_next: int,
    current_block: int,
    block_timestamp: int,
    min_profit_margin_bps: int,
    *,
    engine: ArbitrageEngine | None = None,
) -> Any:
    """
    The signature re-exported so the `#[pyo3(signature)]` reference stays in
    sync with the exposed type (mirrors the convention in `submit.rs`).

    # Errors

    `ValueError`: if `candidates` holds a non-`PyDispatchCandidate` element
    (the GIL-held arg extraction rejects it before the async block is created),
    None — the core `dispatch_profitable_results` is infallible (every
    per-path failure is tallied into `outcome.fail_buckets`, not propagated).

    # Panics

    Panics if the dispatcher or suppression mutex is poisoned (a peer task
    panicked while holding it). Cannot happen under normal operation; a poison
    indicates a bug in a sibling task (the dispatcher/suppression mutexes are
    only ever locked for short synchronous spans).
    """

def executor_policy_py(values: ConfigValues) -> ExecutorPolicyValues:
    """
    The verdict-named executor policy, as the resolution oracle reads it: the
    SAME conversion the executor construction runs, exposed so a Python test
    can pin every knob against the verdict's own values.

    Args:
        `values`: the typed projection (`resolved_config().values`, or a
            hypothetical resolution's) the policy converts from.

    Returns:
        `ExecutorPolicyValues`: the converted policy (the cap with its floor,
        the thin-margin floor, the ERC6909 axis, both inject guards).
    """

def merge_payload_results_py(
    payloads: list, engine: ArbitrageEngine, executor_address: str
) -> PayloadOutcome:
    """
    The payload arm of the sim seam: derive the dispatch-policy
    facts for the engine's inline-sim payload records Rust-side, through the
    SAME row builder the FFI batch join uses.

    Each payload dict is the `result_channel` serializer's primitive field-set
    (`path_id` / `gross_profit` / `net_profit` / `gas_used` / `priority_fee` /
    `base_fee_next` / `execute_calldata` / `access_list` / `failure`). Per entry:

    1. The registered path's typed hops are resolved via the SAME
       engine projection the FFI batch candidates use
       (`PyArbEngine::path_info_for_core`) and routed through
       `join_sim_result` → `derive_path_pools` — the mutual-exclusion set is
       byte-identical to the FFI batch row for the same path id, by
       construction (V4 → `pool_id_hex`; V2/V3 → EIP-55 Display).
    2. Categorization applies the core's `is_gas_profitable` predicate ONCE
       (the same `MIN_PROFIT_NET` floor the FFI batch fan-out applies: a net
       at or above the floor submits; below counts gas-unprofitable). A
       failure payload becomes a sim-fail row.
       Python receives the verdict as a `kind` string only — it never reads
       the threshold value.
    3. The boundary extracts the payload's primitive fields into the crate
       `PayloadRow`, and the crate-owned join reassembles the core row, so the
       submit row shape is the
       exact `PyDispatchOutcome.gas_profitable` handoff.

    Args:
        payloads: list of payload dicts (one per inline-sim entry).
        engine: the `PyArbEngine` (the typed-hop resolver — the same
            engine the payload-producing result batch came from).
        `executor_address`: the session executor contract (the join stamps it
            identically on every row, like `dispatch_profitable_py` does).

    Returns:
        `PayloadOutcome` — the merged record set Python renders (submit rows,
        unprofitable tally, sim-fail rows, `path_infos`, captured swaps are
        empty on the payload arm: the engine's inspector capture rides the
        render dict, not a `CapturedSwap` vector).

    # Errors

    `ValueError`: a payload dict is missing a required field, the calldata is
    not bytes, or a `path_id` is not registered in the engine (the pool-key
    derivation needs the typed hops).
    """

def simulate_in_process_revert_probe(path_id: int, runtime_bytecode: bytes) -> dict:
    """
    Drive the `0xcafebabe`-style REVERT fixture (executor injected with
    caller-supplied runtime bytecode) through the in-process revm EVM —
    ADR-005 Tier-2 dual-driver parity entrypoint for the inspector.

    The fixture (addresses, 2-hop V2 path, block env) is hardcoded to mirror
    the Rust smoke test; the caller supplies only `path_id` (so it round-trips
    through the FFI) + `runtime_bytecode` (the executor's injected bytecode —
    e.g. the `0xcafebabe` REVERT stub or `0xfe` INVALID).

    Returns a dict:
      - `result` (`None`) — the in-process path returns `None` for reverts
        + non-profitable outcomes (the revert is tallied in `failures`).
      - `failures` (`list[dict]`) — one entry per failed candidate, each
        carrying `path_id`, `bucket`, `fail_index`, `revert_data`,
        `reverting_frame`, `captured_swaps`, `optimal_input`, `hop_outputs`
        (same shape as `PyDispatchOutcome.failures()`).
      - `fail_buckets` (`dict[str, int]`) — the bucket tally.

    No RPC. `CacheDB<EmptyDB>` handles all state reads (empty → zero). The
    provider is a mock with an empty queue (errors if somehow called).

    # Errors

    `RuntimeError` only on an unrecoverable revm `transact` error (a DB
    cold-miss RPC failure — cannot happen over `CacheDB<EmptyDB>`, but the
    `ProviderResult` is honored for parity with the production signature).
    """

def simulate_in_process_success_probe(path_id: int) -> dict:
    """
    Drive the SELFDESTRUCT-gift success-path fixture through the in-process
    revm EVM — the ADR-005 Tier-2 dual-driver parity entrypoint for the
    success-path `SimResult` (gross/net/gas).

    The fixture (identical to the Rust `parity_evm_sim.rs` test): the executor
    stub bytecode CALLs a gift contract; the gift `SELFDESTRUCT`s to the
    executor (`CALLER`), sending its 1 ETH balance → `gross_profit = 1 ETH` →
    a non-None `SimResult`. Multicall3 bytecode is deployed so `getEthBalance`
    returns real ETH balances (the pre/post balance reads).

    The caller supplies only `path_id` (round-trips through the FFI); every
    other fixture detail is hardcoded to mirror the Rust parity test.

    Returns a dict:
      - `result` (`dict`) — the `SimResult` as a Python dict (`gross_profit`,
        `net_profit`, `gas_used`, `priority_fee`, `base_fee_next`, `captured_swaps`,
        `hop_count`) when the path is profitable. KeyError-free.
      - `failures` (`list[dict]`) — empty for the success path (same shape as
        `simulate_in_process_revert_probe` for symmetry).
      - `fail_buckets` (`dict`) — empty for the success path.

    No RPC. `CacheDB<EmptyDB>` handles all reads. The provider is a mock with
    an empty queue (errors if somehow called).

    # Errors

    `RuntimeError` only on an unrecoverable revm `transact` error (cannot
    happen over `CacheDB<EmptyDB>`) or if the fixture regresses to a non-None
    bucket (a `debug_assert!` fires + is surfaced as `RuntimeError`).
    """

__all__ = [
    "AssemblyVerdict",
    "BatchExecutor",
    "BatchOutcome",
    "BatchOutcomeSet",
    "CandidateAssembly",
    "DispatchCandidate",
    "DispatchOutcome",
    "ExecutorPolicyValues",
    "FailureDetail",
    "FailureKind",
    "PayloadOutcome",
    "PayloadVerdict",
    "SimReceipt",
    "SimulateContext",
    "SimulateVerdict",
    "SubmitVerdict",
    "assemble_dispatch_candidates_py",
    "build_batch_executor_py",
    "dispatch_profitable_py",
    "executor_policy_py",
    "merge_payload_results_py",
    "simulate_in_process_revert_probe",
    "simulate_in_process_success_probe",
]
