from hexbytes import HexBytes

def flz_compress(uncompressed_data: str | bytes) -> HexBytes: ...
def flz_decompress(compressed_data: bytes | bytearray | str) -> HexBytes: ...

__all__ = ["flz_compress", "flz_decompress"]
