# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.solady` Python submodule (declarative `#[pymodule]`),
carrying the Solady `LibZip` functions `flz_compress` / `flz_decompress`.
The parent module registers the submodule itself and its `sys.modules`
entry.
"""

from typing import Any

def flz_compress(data: Any) -> Any:
    """
    Compress data using Solady's `FastLZ` algorithm.

    Accepts a hex string (with optional `0x` prefix), `bytes`, `bytearray`, or
    `HexBytes` and returns the compressed bytes as a `HexBytes`.

    # Errors

    Returns `PyValueError` if a hex string is malformed, or `PyTypeError` if the
    input is neither a string nor a bytes-like object.
    """

def flz_decompress(data: Any) -> Any:
    """
    Decompress data using Solady's `FastLZ` algorithm.

    Accepts a hex string (with optional `0x` prefix), `bytes`, `bytearray`, or
    `HexBytes` and returns the decompressed bytes as a `HexBytes`.

    # Errors

    Returns `PyValueError` if a hex string is malformed or the compressed data
    is truncated/invalid, or `PyTypeError` if the input is neither a string nor
    a bytes-like object.
    """

__all__ = [
    "flz_compress",
    "flz_decompress",
]
