# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Register all Solidly-math functions on the umbrella module.

Register all Solidly/Aerodrome/Camelot math functions on a real Python
submodule.

Creates `degenbot._ffi.solidly_math` (a `PyModule`, not a flat root-level
prefix) and registers the 10 fns on it with un-prefixed names —
`calc_d`, not `solidly_calc_d`. The `solidly_` prefix was an artifact of
the flat root registration; `camelot_` stays because camelot is a distinct
variant in the same crate (matches `camelot.rs`).

The companion `src/degenbot/aerodrome/math.py` re-exports these as the
stable import path, decoupling Python consumers from `degenbot._ffi`.

# Errors

Returns `PyErr` if any function fails to register.
The `degenbot._ffi.solidly_math` Python submodule (declarative
`#[pymodule]`), carrying the Solidly / Aerodrome / Camelot stable-math
pyfunctions. The parent module registers the submodule itself; the
`sys.modules` entry lives in the parent's shared helper.
"""

from typing import Any

def calc_d(x0: Any, y: Any) -> Any:
    """
    `calc_d` — the Solidly stable `D = 3*x0*y^2 + x0^3*y` analytic.

    # Errors

    Only surfaces `PyErr` if the result-`int` conversion fails (vanishingly
    rare — the value is always a valid `uint256`).
    """

def calc_exact_in_stable_camelot(
    amount_in: Any,
    token_in: int,
    reserves_0: Any,
    reserves_1: Any,
    decimals_0: Any,
    decimals_1: Any,
    fee_numer: Any,
    fee_denom: Any,
) -> Any:
    """
    `calc_exact_in_stable_camelot` — Camelot stable amount-out.
    Pre-baked variant using `k_camelot` + `get_y_camelot`.

    # Errors

    Returns `ValueError` on invalid `token_in`, overflow, or non-convergence.
    """

def calc_exact_in_stable_solidly(
    amount_in: Any,
    token_in: int,
    reserves_0: Any,
    reserves_1: Any,
    decimals_0: Any,
    decimals_1: Any,
    fee_numer: Any,
    fee_denom: Any,
) -> Any:
    """
    `calc_exact_in_stable_solidly` — Solidly / Aerodrome stable
    amount-out. Pre-baked variant using `calc_k` + `get_y_solidly`.

    # Errors

    Returns `ValueError` on invalid `token_in`, overflow, or non-convergence.
    """

def calc_exact_in_volatile(
    amount_in: Any, token_in: int, reserves_0: Any, reserves_1: Any, fee_numer: Any, fee_denom: Any
) -> Any:
    """
    `calc_exact_in_volatile` — Solidly volatile (`x*y >= k`) amount-out.
    Direct port of `solidly_stable.calc_exact_in_volatile`.

    # Errors

    Returns `ValueError` ("Invalid `token_in` identifier") if `token_in` is not
    0 or 1.
    """

def calc_exact_out_stable_solidly(
    amount_out: Any,
    token_in: int,
    reserves_0: Any,
    reserves_1: Any,
    decimals_0: Any,
    decimals_1: Any,
    fee_numer: Any,
    fee_denom: Any,
) -> Any:
    """
    `calc_exact_out_stable_solidly` — Solidly / Aerodrome stable
    amount-in (the inverse of `calc_exact_in_stable_solidly`). Pre-baked
    variant using `calc_k` + `get_y_solidly`.

    # Errors

    Returns `ValueError` on invalid `token_in`, overflow, or non-convergence.
    """

def calc_f(x0: Any, y: Any) -> Any:
    """
    `calc_f` — the Solidly/Aerodrome invariant `f(x0, y) = x0*y^3 + x0^3*y`.

    # Errors

    Only surfaces `PyErr` if the result-`int` conversion fails.
    """

def calc_k(balance_0: Any, balance_1: Any, decimals_0: Any, decimals_1: Any) -> Any:
    """
    `calc_k` — the Solidly/Aerodrome invariant `k = a*b` over
    decimal-scaled reserves. Surfaces the deployed-contract's
    `InvalidUint256` revert as `ZeroDivisionError`-tagged `ValueError`.

    # Errors

    Returns `ValueError` ("EVM Revert: Not a valid uint256") on overflow.
    """

def camelot_f(x0: Any, y: Any) -> Any:
    """
    `camelot_f` — the Camelot-variant invariant `f(x0, y)`.

    # Errors

    Only surfaces `PyErr` if the result-`int` conversion fails.
    """

def camelot_get_y_camelot(x_0: Any, xy: Any, y: Any) -> Any:
    """
    `camelot_get_y_camelot` — Newton's-method `y` solve for the Camelot
    invariant. Direct port of `camelot.get_y_camelot`. Takes `x_0, xy, y_seed`
    (3-arg form — the Python oracle's 5-arg shape ignores the decimals pair).

    # Errors

    Never reverts from the loop; surfaces `ValueError` only if the inner
    `calc_d` would divide by zero (the Python oracle propagates
    `ZeroDivisionError` from `calc_d`).
    """

def camelot_k(balance_0: Any, balance_1: Any, decimals_0: Any, decimals_1: Any) -> Any:
    """
    `camelot_k` — the Camelot-variant `k = a*b` invariant.

    # Errors

    Returns `ValueError` on overflow.
    """

def get_y_solidly(x0: Any, xy: Any, y: Any, decimals_0: Any, decimals_1: Any) -> Any:
    """
    `get_y_solidly` — Newton's-method `y` solve for the Solidly/Aerodrome
    invariant. Direct port of `solidly_stable.get_y_solidly`.

    # Errors

    Returns `ValueError` on non-convergence (after 255 iterations) or overflow.
    """

__all__ = [
    "calc_d",
    "calc_exact_in_stable_camelot",
    "calc_exact_in_stable_solidly",
    "calc_exact_in_volatile",
    "calc_exact_out_stable_solidly",
    "calc_f",
    "calc_k",
    "camelot_f",
    "camelot_get_y_camelot",
    "camelot_k",
    "get_y_solidly",
]
