# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
The `degenbot._ffi.submission` Python submodule (declarative
`#[pymodule]`), carrying the submission pyclasses + the
`finalize_fees_py` / `dispatch_and_submit_py` / `fetch_fee_history_py`
pyfunctions. The parent module registers the submodule itself and its
`sys.modules` entry.
"""

from collections.abc import Sequence
from typing import Any, final

from .provider import AsyncAlloyProvider

@final
class Dispatcher:
    """
    The coordination-state value object for the dispatch loop.

    Bundles the mutable containers `consume_result_batches` /
    `dispatch_profitable_results` / `monitor_pending_transaction` previously
    held as a Python mirror: pending nonces/pools, in-flight task count, the
    current-block reference, the block-time ring, per-block priority fees.
    `PathSuppression` is **not** composed ; it lives behind its
    own `Arc<Mutex<PathSuppression>>` on `PyDispatcher` so the simulation seam
    locks it directly, never the `Dispatcher`.

    Construct via [`PyDispatcher::for_block`]. The held [`Dispatcher`] is owned
    by Rust; Python drives it through the `PyO3` seam (the Rust leaves
    `dispatch_and_submit` / `fetch_fee_history` / `monitor_pending_transaction`
    receive the SAME `Arc<Mutex<Dispatcher>>` + lock it themselves).
    """
    def abort_all_tasks(self, /) -> None:
        """
        Abort all tracked tasks (cold-shutdown).
        """
    def active_task_count(self, /) -> int:
        """
        Count of in-flight spawned monitor/broadcast tasks (best-effort,
        reaped of finished entries).
        """
    def advance_block(self, /, block: int) -> None:
        """
        Update the current block (read by monitor tasks by reference).
        """
    @property
    def block_priority_fees(self, /) -> dict[int, dict[int, int]]:
        """
        The full per-block priority-fee ring (`{block: {percentile: wei}}`),
        empty when nothing recorded. Read by `_compute_priority_fee` (which
        does `max(ring)` for the latest block's percentiles) — preserves the
        Python `dispatcher.block_priority_fees` attribute shape unchanged.
        """
    def block_time_count(self, /) -> int:
        """
        Count of recorded block-time pairs (capped at the ring maxlen).
        """
    def block_times_oldest(self, /) -> tuple[int, int]:
        """
        The oldest `(block, timestamp)` pair in the ring (the latency baseline).

        Raises:
            `IndexError`: If the ring is empty.
        """
    def block_timestamp_for(self, /, block: int) -> int | None:
        """
        Look up the recorded timestamp for `block` (the in-process `evm` sim
        uses it as the EVM `block.timestamp` ). Returns `None` if
        `block` is outside the recorded window.
        """
    @property
    def current_block(self, /) -> int:
        """
        The current block (the by-reference block clock).
        """
    def discard_path(self, /, path_id: int) -> None:
        """
        Discard a path from suppression tracking (the result-batch `removed` set).
        """
    def divergent_pools(self, /, current_block: int) -> list[DivergentPool]:
        """
        The current divergent-pool set — `list[dict]`, one per pool flagged
        `SolverCalc` within the decay window. Each dict carries `family`
        (`"V2"`/`"V3"`/`"V4"`), the pool identity (`address` for V2/V3,
        `pool_id` bytes32 hex for V4), + `last_flagged_block`. Drives the
        operator's `[pool-divergence-memo]` monitoring view of the persistent
        memo state (distinct from the per-block `[pool-divergence]` signal the
        Python aggregator renders from `outcome.failures`).
        """
    @staticmethod
    def for_block(current_block: int) -> Dispatcher:
        """
        Construct a fresh dispatcher seeded at `current_block`.

        Args:
            `current_block`: The block to seed the by-reference block clock with.
        """
    def fot_tokens(self, /, current_block: int) -> list[str]:
        """
        The current confirmed-FoT token set — `list[str]`, one per token
        confirmed `FoT` (>= K distinct failing pools, 0 successes, within the
        decay window). Each entry is the token's checksummed address. Drives
        the operator's `[fot]` monitoring view + the denylist feed.

        Panics (crashes the driver) if any confirmed token is in the
        operator's verified-non-FoT set — the hard classifier-invariant guard
        (coarse, per the operator's directive).
        """
    def is_path_blocked(self, /, path_pools: set[str], committed_pools: set[str]) -> bool:
        """
        True iff any path pool is already locked (pending) or committed this batch.
        """
    def is_suppressed(self, /, path_id: int, current_block: int) -> bool:
        """
        True iff `path_id` is currently suppressed (retried every
        `PATH_SUPPRESS_RETRY_INTERVAL` blocks).
        """
    def latest_priority_fees(self, /) -> dict[int, int]:
        """
        The most-recently recorded per-block percentile fees (`{p: wei}`).

        Raises:
            `ValueError`: If no fees have been recorded yet (the ring is empty).
        """
    def pending_pool_count(self, /) -> int:
        """
        Count of pool keys reserved but not yet released.
        """
    def reap_finished(self, /) -> int:
        """
        Reap finished tasks; return the count reaped.
        """
    def record_block_time(self, /, block: int, timestamp: int) -> None:
        """
        Record a `(block, timestamp)` pair into the block-time ring (maxlen 60).
        """
    def record_failure(self, /, path_id: int) -> None:
        """
        Record a failed simulation for `path_id` (bumps its fail streak;
        suppresses after `PATH_SUPPRESS_THRESHOLD` consecutive failures).
        """
    def record_priority_fees(self, /, block: int, fees: dict[int, int]) -> None:
        """
        Record per-block percentile fees, pruning to the fee-history window.

        Args:
            `block`: The block the fees are for.
            `fees`: A `{percentile: wei}` dict (e.g. `{50: 1_000_000_000}`).
        """
    def record_success(self, /, path_id: int) -> None:
        """
        Record a successful simulation for `path_id` (clears its fail streak).
        """
    def release_pools(self, /, pools: set[str]) -> None:
        """
        Release Rust pool keys when a tx confirms or expires.
        """
    def reserve_pools(self, /, path_pools: set[str]) -> None:
        """
        Mark Rust pool keys as locked by an in-flight tx.
        """
    @property
    def total_divergent_dropped(self, /) -> int:
        """
        The lifetime-total paths dropped via the divergence skip.
        """
    @property
    def total_fot_dropped(self, /) -> int:
        """
        The lifetime-total paths dropped via the `FoT` skip.
        """
    def total_suppressed(self, /) -> int:
        """
        Count of paths currently in the suppressed set.
        """

@final
class DivergentPool:
    """
    The read-only view of one entry in `PyDispatcher.divergent_pools()` — a
    pool flagged `SolverCalc` within the decay window. Carries the `family`
    discriminator, the pool's chain identity (`address` for V2/V3, `pool_id`
    bytes32 hex for V4), + `last_flagged_block`.
    """
    @property
    def address(self, /) -> str | None:
        """
        The pool contract address (`0x`-prefixed checksummed) for V2/V3;
        `None` for V4 (V4 pools live inside the `PoolManager` — use `pool_id`).
        """
    @property
    def family(self, /) -> str:
        """
        The Uniswap family (`"V2"` / `"V3"` / `"V4"`).
        """
    @property
    def last_flagged_block(self, /) -> int:
        """
        The block the pool last flagged `SolverCalc` (decays after
        `POOL_DIVERGENCE_DECAY_BLOCKS` clean blocks).
        """
    @property
    def pool_id(self, /) -> str | None:
        """
        The V4 `poolId` bytes32 (`0x`-prefixed hex); `None` for V2/V3.
        """

@final
class SimSubmitPipeline:
    """
    A bounded concurrent sim fan-out with a single ordered submit lane.

    Construct with the two async callables and the in-flight sim cap; `enqueue`
    returns immediately while the core schedules the bounded sim and registers
    the batch in the FIFO submit queue. `raise_if_failed` re-raises the first
    leaf failure in the caller's frame; `shutdown` drains and joins.
    """
    def __new__(cls, /, sim: Any, submit: Any, concurrency: int) -> SimSubmitPipeline:
        """
        Build the pipeline over the two Python async leaves.

        The task locals (the running asyncio loop + contextvars) are captured
        here so the core's tokio tasks can await the Python callables.

        # Errors

        Raises when there is no running asyncio loop to bind the leaves to.
        """
    @property
    def concurrency(self, /) -> int:
        """
        The configured in-flight sim bound.
        """
    def enqueue(self, /, work: Any) -> None:
        """
        Background one batch's sim (bounded) and register it in the FIFO queue.
        """
    @property
    def enqueued(self, /) -> int:
        """
        How many batches have been enqueued.
        """
    def raise_if_failed(self, /) -> None:
        """
        Re-raise the first leaf failure in the caller's frame (loud abort).

        # Errors

        Raises `RuntimeError` when a sim or submit leaf failed.
        """
    def shutdown(self, /) -> Any:
        """
        Drain in-flight work and join the submitter.

        # Errors

        Raises `RuntimeError` when a sim or submit leaf failed.
        """
    @property
    def submitted(self, /) -> int:
        """
        How many batches the ordered submitter has drained.
        """

@final
class SubmitCandidate:
    """
    `PySubmitCandidate` — the builder the Python submit-tail constructs from
    each `gas_profitable` entry before handing the batch to
    [`dispatch_and_submit_py`].

    Fields mirror [`SubmitCandidate`] 1:1. Python passes:
     * `path_id`, `gas_used`: `int`
     * `gross_profit`, `net_profit`: `int` (wei)
     * `priority_fee`, `base_fee_next`: `int` (wei)
     * `execute_calldata`: `bytes`
     * `executor_address`: hex string
     * `access_list`: web3-shape list (optional; `None` to skip)
     * `path_pools`: `set[str]` (V4 `pool_id_hex` / V2-V3 `pool_address`)
    """
    def __new__(
        cls,
        /,
        path_id: int,
        gross_profit: Any,
        net_profit: Any,
        gas_used: int,
        priority_fee: int,
        base_fee_next: int,
        execute_calldata: bytes,
        executor_address: str,
        access_list: list | None = None,
        path_pools: Any | None = None,
    ) -> SubmitCandidate:
        """
        Build a submit candidate from the dispatch fan-out's per-path fields.

        All money fields are wei (`int`). The priority fee is the
        `_compute_priority_fee` output (computed Python-side — S3 stay-Python —
        + passed IN).
        """
    @property
    def execute_calldata(self, /) -> bytes:
        """
        The composed `execute(bytes, uint256)` calldata (the exact bytes the
        submit leaf signs + broadcasts). Forensic/fork-replay seam (R3b): a
        candidate judged submittable must be replayable at its solve block.
        """
    @property
    def gas_used(self, /) -> int: ...
    @property
    def gross_profit(self, /) -> Any: ...
    @property
    def net_profit(self, /) -> Any: ...
    @property
    def path_id(self, /) -> int: ...
    @property
    def path_pools(self, /) -> set[str]:
        """
        The mutual-exclusion pool-key set the join stamped (NUUJFA): the
        parity-test read surface — the payload arm's rows must carry the
        byte-identical set the FFI batch join derives for the same path. The
        strings are the `PoolKey` display forms (V4 `pool_id_hex`; V2/V3
        EIP-55 checksummed addresses).
        """
    @property
    def priority_fee(self, /) -> int: ...

@final
class TxParams:
    """
    The EIP-1559 transaction field set, minus `chain_id` (owned by
    [`PyTxSigner`](crate::submission::PyTxSigner)).

    Construction:
    ```python
    params = PyTxParams(
        to="0x0000...0000",
        data=execute_calldata,  # bytes
        gas_limit=250_000,
        nonce=7,
        value=0,  # optional, default 0
        access_list=[],  # optional, web3 shape
    )
    finalize_fees(params, base_fee_next, priority_fee)
    raw = signer.sign_eip1559(params)
    ```
    """
    def __new__(
        cls,
        /,
        to: str,
        data: bytes,
        gas_limit: int,
        nonce: int,
        value: int = 0,
        access_list: list | None = None,
    ) -> TxParams:
        """
        Create a new EIP-1559 transaction field set.

        Args:
            to: Recipient contract address (hex string)
            data: The ``execute()`` calldata (bytes)
            `gas_limit`: Gas limit (units)
            `nonce`: Sender account nonce
            `value`: Ether value to transfer in wei (default 0)
            `access_list`: EIP-2930 access list in the web3 `create_access_list`
                shape — a list of ``{"address": "0x...", "storageKeys":
                ["0x..."]}`` dicts. Default empty.
        """
    @property
    def max_fee_per_gas(self, /) -> int:
        """
        The ``maxFeePerGas`` (wei) set by [`finalize_fees_py`].
        """
    @property
    def max_priority_fee_per_gas(self, /) -> int:
        """
        The ``maxPriorityFeePerGas`` (wei) set by [`finalize_fees_py`].
        """

@final
class TxSigner:
    """
    An EIP-1559 transaction signer holding the operator key once.

    Constructed from the operator private key (hex or 32 raw bytes) + a chain
    id. ``sign_eip1559`` builds + signs a type-2 ``TxEnvelope`` and returns the
    raw signed bytes ready for ``eth_sendRawTransaction``.
    """
    def __new__(cls, /, key: Any, chain_id: int) -> TxSigner:
        """
        Create a new signer holding the operator key.

        Args:
            key: The operator private key, either a hex string (with or without
                ``0x`` prefix) or 32 raw bytes. The key is held in Rust for the
                signer's lifetime — it never crosses back into Python per-tx.
            `chain_id`: The chain id used for EIP-155 replay protection on every
                signed transaction.

        Raises:
            `ValueError`: If the key is malformed (bad hex, wrong length, or not
                a valid secp256k1 scalar).
        """
    @property
    def address(self, /) -> str:
        """
        The derived operator address (EIP-55 checksummed hex string).
        """
    @property
    def chain_id(self, /) -> int:
        """
        The chain id used for EIP-155 replay protection.
        """
    @staticmethod
    def recover_sender(raw_signed: bytes) -> str:
        """
        Recover the sender address from a raw signed transaction.

        Decodes the bytes produced by [`sign_eip1559`](Self::sign_eip1559) and
        recovers the signer. Used by the submission loop's receipt-validation
        path + the §4.2 round-trip parity test.

        Args:
            `raw_signed`: The raw signed transaction bytes.

        Returns:
            The recovered sender address (EIP-55 checksummed hex string).

        Raises:
            `ValueError`: If the bytes do not decode or the signature does not
                recover.
        """
    def sign_eip1559(self, /, tx_params: TxParams) -> bytes:
        """
        Sign a type-2 EIP-1559 transaction and return the raw signed bytes.

        Builds the ``TxEnvelope`` from ``tx_params`` (``to``/``data``/``gas``/
        ``nonce``/``value``/``accessList`` + the fee fields set by
        :func:`finalize_fees`), signs synchronously via the held
        ``LocalSigner`` (RFC 6979 deterministic ECDSA — ``eth_account``-parity),
        and encodes as ``Typed2718`` (``0x02`` prefix).

        Signing is synchronous (CPU-bound secp256k1, no network); the GIL is
        released for the duration.

        Args:
            `tx_params`: The `PyTxParams` to sign (fees must be finalized first).

        Returns:
            The raw signed transaction bytes (ready for `eth_sendRawTransaction`).

        Raises:
            `ValueError`: If ECDSA signing fails (never for a validly-constructed
                signer — only on key corruption).
        """

def dispatch_and_submit_py(
    candidates: list,
    dispatcher: Dispatcher,
    provider: AsyncAlloyProvider,
    signer: TxSigner,
    operator_nonce: int,
    current_block: int,
    dry_run: bool,
    inject_code: bool,
    broadcast_providers: Sequence[AsyncAlloyProvider] | None = None,
) -> Any:
    """
    Route a batch of profitable candidates through the Rust submit leaf.

    This replaces the Python submit-tail of `dispatch_profitable_results`
    (the mutual-excl guard → `claim_nonce` → access-list re-compute → sign →
    `eth_sendRawTransaction` → `reserve_pools` → monitor-spawn). Python builds
    the `PySubmitCandidate` list from `gas_profitable` (encode/sim/gas stays
    Python — S3 stay-Python), then hands the batch + the coordination args.

    Args:
        `candidates`: list of `PySubmitCandidate` (profit-descending is
            re-asserted by the leaf).
        `dispatcher`: the `PyDispatcher` holding the coordination state
            (the Rust leaves lock the SAME `Arc`).
        `provider`: the `AsyncAlloyProvider` (the typed RPC handle).
        `signer`: the `PyTxSigner` (per-tx key never crosses to Python).
        `operator_nonce`: the baseline account nonce.
        `current_block`: the by-ref block clock read.
        `dry_run`: skip live submission (commit pools anyway).
        `inject_code`: skip live submission (the injected contract doesn't
            exist on-chain).

    Returns:
        A list of record dicts — `{"kind": "submitted", "path_id": ...,
        "tx_hash": "0x...", "nonce": ...}` or `{"kind": "skipped",
        "path_id": ..., "reason": "pools_claimed"|"dry_run"|"inject_code"|
        "broadcast_failed", "detail": "..."?}`.

    # Errors
    `ValueError`: If the dispatch+submit leaf returns a `SubmissionError`
            (a non-"not-found" RPC error during broadcast/access-list/sign).
    """

def fetch_fee_history_py(
    provider: AsyncAlloyProvider,
    dispatcher: Dispatcher,
    block_count: int,
    last_block: int,
    reward_percentiles: Sequence[float],
) -> Any:
    """
    Route a single-block `eth_feeHistory` RPC + record into the dispatcher.

    Replaces `_apply_block_if_ready`'s `make_request('eth_feeHistory')` +
    hex-decode block. Returns `True` if the fee history was fetched + recorded
    (the dispatcher's `record_priority_fees` ran), `False` on RPC failure
    (matches the Python `except Web3Exception: pass` no-op).

    Args:
        `provider`: the `AsyncAlloyProvider`.
        `dispatcher`: the `PyDispatcher`.
        `block_count`: blocks to fetch (the Python passed `1`).
        `last_block`: the highest block in the range (hex-tag in Python).
        `reward_percentiles`: list of float percentiles (e.g. `[10., 50., 90.]`).

    # Errors
    `ValueError`: If the RPC `eth_feeHistory` call surfaces a non-"not-found"
            error (the leaf no-ops on `Web3Exception`, so this is rare).
    """

def finalize_fees(params: TxParams, base_fee_next: int, priority_fee: int) -> None:
    """
    `#[pyfunction]` wrapper over [`degenbot_submission::finalize_fees`].

    Sets ``params.max_priority_fee_per_gas = priority_fee`` and
    ``params.max_fee_per_gas = int(1.5 * base_fee_next) + priority_fee``
    (the Python oracle's inline fee computation, including the float→int
    truncate — see the core crate's `fee` module).

    Args:
        `params`: The `PyTxParams` to finalize fees onto (mutated in place)
        `base_fee_next`: The next-block base fee in wei
        `priority_fee`: The priority fee in wei (consumed from the Simulation
            leaf's `_compute_priority_fee` — submission does not compute it)

    # Errors

    Raises:
        `RuntimeError`: If the fee arithmetic overflows `u128` (impossible for
            realistic mainnet fees).
    """

__all__ = [
    "Dispatcher",
    "DivergentPool",
    "SimSubmitPipeline",
    "SubmitCandidate",
    "TxParams",
    "TxSigner",
    "dispatch_and_submit_py",
    "fetch_fee_history_py",
    "finalize_fees",
]
