# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2).
# Do not edit by hand — regenerate with `just gen-stubs`; generator gaps live only in tests/rust/stubtest_allowlist.txt (ADR-066 D3).

"""
Creates `degenbot._ffi.v2_math` and registers the two V2
constant-product calcs on it with un-prefixed names. The Python
companions `degenbot.uniswap.math` / `degenbot.aerodrome.math`
re-export these as the stable import path, decoupling consumers
from `degenbot._ffi`.

# Errors

Returns `PyErr` if any function fails to register.
The `degenbot._ffi.v2_math` Python submodule (declarative
`#[pymodule]`), carrying the V2 constant-product swap-math pyfunctions.
The parent module registers the submodule itself; the `sys.modules`
entry lives in the parent's shared helper.
"""

from typing import Any

def calc_exact_in_v2(
    reserves_in: Any, reserves_out: Any, amount_in: Any, fee_numer: Any, fee_denom: Any
) -> Any:
    """
    `calc_exact_in_v2` — V2 constant-product amount-OUT for an exact input
    (the on-chain getAmountOut):
    `y = (fee_denom - fee_numer) * r_out * amount_in / (fee_denom * r_in + (fee_denom - fee_numer) * amount_in)` (floor).

    # Errors

    Returns `ValueError` on invalid fee parameters or uint256 overflow.
    """

def calc_exact_out_v2(
    reserves_in: Any, reserves_out: Any, amount_out: Any, fee_numer: Any, fee_denom: Any
) -> Any:
    """
    `calc_exact_out_v2` — V2 constant-product amount-IN for an exact output
    (getAmountOut inverse): `x = 1 + r_in * amount_out * fee_denom /
    ((r_out - amount_out) * (fee_denom - fee_numer))` (floor).

    # Errors

    Returns `ValueError` on overdraw (`amount_out` >= `reserves_out`), invalid
    fee parameters, or uint256 overflow.
    """

__all__ = [
    "calc_exact_in_v2",
    "calc_exact_out_v2",
]
