"""Regenerate-and-diff drift gate over the committed `degenbot._ffi` stubs.

ADR-066 D2/D3 cutover: `src/degenbot/_ffi/*.pyi` is GENERATOR OUTPUT (the
`degenbot-stubgen` tool reading the introspection chunks embedded by the
binding layer's `experimental-inspect` build), not a hand-maintained set.
Source and stubs may only agree, so this gate regenerates the tree and diffs
it against the committed one — the REGEN pattern of
`docs/rust-config-keys.md` (`REGEN_CONFIG_DOCS=1 cargo test -p
degenbot-config`), here via `just gen-stubs --check` with `REGEN_STUBS=1` as
the deliberate-regeneration opt-in.

Any seam-source change that reaches the Python surface therefore fails a
plain test run until `just gen-stubs` re-records the generator's verdict.
Hand edits over generated output never reconcile a failure: generator gaps
live only in `tests/ffi/stubtest_allowlist.txt` (ADR-066 D3), and
`mypy.stubtest` (`just lint-stubtest`) verifies the generated stubs against
the running extension.

Build-graph coupling: `test_committed_stubs_match_generator_output` is the
only place a plain Python-suite run enters the compile graph —
`just gen-stubs --check` cargo-builds `degenbot_rs` (with the temporary
`experimental-inspect` feature) and `degenbot-stubgen` before statically
introspecting `rust/target/debug/libdegenbot_rs.so`. Run it with exclusive
use of the build graph: a concurrent `just dev` / `cargo build` in another
lane holds the debug build lock and can relink that `.so` — without the
introspection feature — while the check reads it, surfacing as an artifact
or mass-diff error unrelated to real drift. The regen test probes cargo's
debug-profile build lock (`rust/target/debug/.cargo-build-lock`, the lock
whose hold makes cargo print "Blocking waiting for file lock on build
directory") up front and fails with a distinct message when another build
is in progress; rerun it once the other build finishes. A foreign
build that starts after the probe still races the introspection, so a
suspicious failure is arbitrated by rerunning this test alone.
"""

from __future__ import annotations

import ast
import fcntl
import os
import pathlib
import subprocess

import pytest

_REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
_STUB_DIR = _REPO_ROOT / "src" / "degenbot" / "_ffi"
# First line of every file the generator emits (`degenbot-stubgen`'s
# GENERATED_HEADER): marks the tree as generator output so a hand-replaced
# stub is detectable without running the generator.
_GENERATED_MARK = "# Generated by `just gen-stubs` from the cdylib's embedded PyO3 introspection chunks (ADR-066 D2)."

# Debug-profile builds — `cargo build`, `cargo test`, and `just dev`'s
# `maturin develop` — serialize behind an flock on this file (cargo's own
# wait prints "Blocking waiting for file lock on build directory"), so a
# non-blocking probe of the same lock answers "is another lane mid-build
# right now" without the probe ever waiting on that lane. The lock file
# persists after release, so only a conflicting probe counts as busy; the
# file's absence, or an unopenable/failed probe, means "proceed": the check
# then behaves exactly as it does on a free graph.
_CARGO_BUILD_LOCK = _REPO_ROOT / "rust" / "target" / "debug" / ".cargo-build-lock"


def _busy_build_graph_reason() -> str | None:
    """Why the cargo build graph is unusable right now, or None when free."""
    if not _CARGO_BUILD_LOCK.is_file():
        return None
    fd = None
    try:
        fd = os.open(_CARGO_BUILD_LOCK, os.O_RDWR)
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except BlockingIOError:
        return (
            "the cargo build lock rust/target/debug/.cargo-build-lock is held"
            " by another process (a concurrent `just dev` / `cargo build` /"
            " `cargo test` in another lane)"
        )
    except OSError:
        return None
    else:
        fcntl.flock(fd, fcntl.LOCK_UN)
        return None
    finally:
        if fd is not None:
            os.close(fd)


def test_committed_stubs_carry_generator_header() -> None:
    """Every committed stub is marked generator output (ADR-066 D2)."""
    stubs = sorted(_STUB_DIR.glob("*.pyi"))
    assert stubs, f"stub tree missing at {_STUB_DIR}"
    unmarked = [
        str(p.relative_to(_REPO_ROOT))
        for p in stubs
        if not p.read_text(encoding="utf-8").startswith(_GENERATED_MARK)
    ]
    assert not unmarked, (
        "stub files without the generator header (hand-edited or foreign): "
        f"{unmarked} — regenerate with `just gen-stubs`, never hand-edit"
    )


# The regen-and-diff check rebuilds the cdylib with the `experimental-inspect`
# feature before generating, so it carries the workspace's toggle cost; the
# per-test timeout extends pytest-timeout's 300s default to cover a warm
# rebuild without parking the run on a hang.
@pytest.mark.timeout(900)
def test_committed_stubs_match_generator_output() -> None:
    """Committed stubs are byte-identical to `just gen-stubs --check` output.

    Set ``REGEN_STUBS=1`` to let the check rewrite the committed tree
    (deliberate regeneration only — never to reconcile a hand edit).
    """
    assert (_REPO_ROOT / "justfile").is_file(), "recipe run must start at the repo root"
    busy = _busy_build_graph_reason()
    assert busy is None, (
        f"{busy} — `just gen-stubs --check` cargo-builds the cdylib it"
        " introspects, so a concurrent build yields a half-written or"
        " feature-mismatched artifact error instead of a drift verdict;"
        " rerun this test once the other lane's build finishes."
    )
    proc = subprocess.run(
        ["just", "gen-stubs", "--check"],
        cwd=_REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert proc.returncode == 0, (
        f"`just gen-stubs --check` failed (rc={proc.returncode});\n{proc.stdout}\n{proc.stderr}"
    )

# The typed seam projection's stub face: the generator emits
# per-section `@type_check_only` face classes with one typed property per
# declared key, and `ConfigValues` inherits a face base carrying one property
# per top-level section (rust/tools/stubgen/src/config_projection.rs, spliced
# from the schema macro's SCHEMA/SECTION_PATHS tables). These assertions pin
# the committed tree's face; the regenerate-and-diff gate above proves the
# face regenerates byte-for-byte, and these checks make a silent fall-back to
# the machinery face (`__getattr__(name: str) -> Any`) a named failure instead
# of a quiet de-typing.
def _projection_class(tree: ast.Module, name: str) -> ast.ClassDef:
    classes = [
        node
        for node in tree.body
        if isinstance(node, ast.ClassDef) and node.name == name
    ]
    assert len(classes) == 1, f"expected exactly one {name} class in the stub"
    return classes[0]


def _properties(cls: ast.ClassDef) -> dict[str, ast.expr]:
    """{name: return annotation} for the class's read-only property members."""
    properties: dict[str, ast.expr] = {}
    for node in cls.body:
        if not isinstance(node, ast.FunctionDef):
            continue
        decorator_names = {getattr(d, "attr", None) for d in node.decorator_list}
        assert "setter" not in decorator_names, (
            f"{cls.name}.{node.name} carries a setter — the projection is read-only"
        )
        if any(getattr(d, "id", None) == "property" for d in node.decorator_list):
            annotation = node.returns
            assert annotation is not None, f"{cls.name}.{node.name} lacks a return type"
            properties[node.name] = annotation
    return properties


def test_config_projection_stubs_are_typed() -> None:
    """The config projection's stub face is typed, not machinery."""
    tree = ast.parse((_STUB_DIR / "__init__.pyi").read_text(encoding="utf-8"))

    # values.<section>: ConfigValues inherits the machine-emitted face base and
    # carries no __getattr__ of its own — the machinery face is gone.
    values = _projection_class(tree, "ConfigValues")
    assert len(values.bases) == 1 and values.bases[0].id == "_ConfigValuesFace", (
        "ConfigValues must inherit the machine-emitted face base"
    )
    assert not [
        node
        for node in values.body
        if isinstance(node, ast.FunctionDef) and node.name == "__getattr__"
    ], "ConfigValues still carries the machinery __getattr__"

    base = _projection_class(tree, "_ConfigValuesFace")
    base_properties = _properties(base)
    assert base_properties["dispatch"].id == "_ConfigDispatchFace"
    assert base_properties["strategy"].id == "_ConfigStrategyFace"

    # values.<section>.<field>: every declared key typed to its declared kind.
    dispatch = _properties(_projection_class(tree, "_ConfigDispatchFace"))
    assert dispatch["min_profit_margin_bps"].id == "int"
    assert dispatch["erc6909_profit"].id == "bool"
    # the closed projection: a name outside the declaration is not typed
    assert "not_a_key" not in dispatch

    diagnostics = _properties(_projection_class(tree, "_ConfigDiagnosticsFace"))
    assert diagnostics["tracemalloc_secs"].id == "float"

    # facet namespaces stay navigable: strategy.settlement projects its own face
    strategy = _properties(_projection_class(tree, "_ConfigStrategyFace"))
    assert strategy["settlement"].id == "_ConfigStrategySettlementFace"
    settlement = _properties(_projection_class(tree, "_ConfigStrategySettlementFace"))
    assert settlement, "the nested section face carries no declared keys"

    # the runtime section view keeps its honest machinery signature — the one
    # documented stubtest residual (runtime getattro slot, invisible to
    # introspection; see tests/ffi/stubtest_allowlist.txt)
    section = _projection_class(tree, "ConfigSectionValues")
    machinery = [
        node
        for node in section.body
        if isinstance(node, ast.FunctionDef) and node.name == "__getattr__"
    ]
    assert len(machinery) == 1, "ConfigSectionValues must keep its machinery __getattr__"
    param = (machinery[0].args.posonlyargs or machinery[0].args.args)[1]
    assert isinstance(param.annotation, ast.Name) and param.annotation.id == "str"
